<?php
namespace Database\Seeders;
use App\Models\{AdminRecord,Category,Company,ContentPage,Currency,Discount,IntegrationConnection,Language,Permission,Product,ProductVariant,Role,SeoSetting,ShippingMethod,User};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder {
 public function run():void {
  $company=Company::updateOrCreate(['code'=>'ERL'],['name'=>'Emerald Rozalia','legal_name'=>'Emerald Rozalia Limited','country_code'=>'IE','base_currency'=>'EUR','default_locale'=>'en','active'=>true]);
  Currency::updateOrCreate(['code'=>'EUR'],['name'=>'Euro','symbol'=>'€','decimals'=>2,'active'=>true]); Language::updateOrCreate(['locale'=>'en'],['name'=>'English','native_name'=>'English','active'=>true]);
  $company->currencies()->syncWithoutDetaching(['EUR'=>['is_base'=>true,'enabled_storefront'=>true]]); $company->languages()->syncWithoutDetaching(['en'=>['is_default'=>true]]);
  $categories=[]; foreach([['Baseball Caps','baseball-caps'],['Bucket Hats','bucket-hats'],['Snapbacks','snapbacks'],['Irish Traditional Flat Caps','irish-traditional-flat-caps'],['Irish Heritage Hats','irish-heritage-hats'],['Beanies & More','beanies-more'],['GAA Baseball Caps','gaa-baseball-caps'],['GAA Bucket Hats','gaa-bucket-hats'],['GAA Beanie Hats','gaa-beanie-hats']] as $i=>$c)$categories[]=Category::updateOrCreate(['slug'=>$c[1]],['company_id'=>$company->id,'name'=>$c[0],'description'=>'Premium Emerald Rozalia headwear made in Limerick, Ireland.','sort_order'=>$i,'is_active'=>true]);
  foreach([['Classic Emerald Cap',3499],['Emerald Signature Cap',3499],['Rozalia Snapback',3699],['Emerald Flat Cap',4499],['Emerald Beanie',2999],['Emerald Trucker Cap',3499]] as $i=>$seed){$p=Product::updateOrCreate(['sku'=>'ER-'.str_pad((string)($i+1),4,'0',STR_PAD_LEFT)],['company_id'=>$company->id,'category_id'=>$categories[$i]->id,'name'=>$seed[0],'slug'=>str($seed[0])->slug(),'description'=>'Premium quality, Irish character and expert craftsmanship.','price'=>$seed[1]/100,'stock'=>100,'material'=>'Premium headwear fabric','is_new'=>true,'is_active'=>true,'status'=>'active','brand'=>'Emerald Rozalia']);ProductVariant::updateOrCreate(['sku'=>$p->sku.'-STD'],['product_id'=>$p->id,'colour'=>'Emerald / Black','size'=>'Adjustable','price'=>$p->price,'stock'=>100,'is_active'=>true]);}
  ShippingMethod::updateOrCreate(['code'=>'IE_STANDARD'],['company_id'=>$company->id,'name'=>'Ireland Standard Delivery','country'=>'IE','price'=>6.95,'free_over'=>100,'is_active'=>true]); Discount::updateOrCreate(['code'=>'WELCOME10'],['company_id'=>$company->id,'type'=>'percent','value'=>10,'minimum_order'=>50,'is_active'=>true]);
  throw_if(blank(env('ADMIN_EMAIL'))||blank(env('ADMIN_PASSWORD')),\RuntimeException::class,'ADMIN_EMAIL and ADMIN_PASSWORD must be set before seeding.');
  $admin=User::updateOrCreate(['email'=>env('ADMIN_EMAIL')],['name'=>env('ADMIN_NAME','Project Owner'),'password'=>Hash::make(env('ADMIN_PASSWORD')),'is_admin'=>true,'email_verified_at'=>now()]); $company->users()->syncWithoutDetaching([$admin->id=>['role'=>'owner','is_default'=>true]]);
  foreach(['website','products','pages','online_sales','orders','customers','franchise','communications','reports','users','integrations','settings','audit','automation','backup','maintenance'] as $group)foreach(['view','create','update','delete','approve','export'] as $action)Permission::firstOrCreate(['name'=>"$group.$action"],['group'=>$group]);
  $owner=Role::firstOrCreate(['name'=>'owner'],['label'=>'Owner']);$owner->permissions()->sync(Permission::pluck('id'));$admin->roles()->syncWithoutDetaching([$owner->id]); foreach(['admin'=>'Administrator','manager'=>'Manager','editor'=>'Website Editor','support'=>'Communication Support','franchise'=>'Franchise Manager','reporting'=>'Reporting Analyst'] as $name=>$label)Role::firstOrCreate(['name'=>$name],['label'=>$label]);
  foreach(['payment','whatsapp','social','shipping','try_on','product_360'] as $service)IntegrationConnection::updateOrCreate(['service'=>$service],['enabled'=>false,'health'=>'not_configured']);
  foreach(['collections'=>'Collections','new-arrivals'=>'New Arrivals','corporate-orders'=>'Corporate Order','bulk-orders'=>'Bulk Order','franchise'=>'Franchise Apply','careers'=>'Hiring Apply','contact'=>'Contact Us','global-network'=>'Our Global Network','factory'=>'Our Manufacturing Story','virtual-tryon'=>'Virtual Try-On','irish-traditional'=>'Irish Traditional Hats','irish-heritage'=>'Irish Heritage Collection'] as $slug=>$title)ContentPage::firstOrCreate(['slug'=>$slug],['title'=>$title,'status'=>'published','locale'=>'en','template'=>'standard','navigation_visible'=>in_array($slug,['collections','new-arrivals','corporate-orders','bulk-orders','franchise','careers']),'published_at'=>now(),'intro'=>"$title by Emerald Rozalia Limited.",'body'=>'Managed through the Project 1 Page Manager.']);
  SeoSetting::updateOrCreate(['company_id'=>$company->id,'key'=>'home_meta'],['value'=>['title'=>'Emerald Rozalia — Irish Made Hats & Caps','description'=>'Discover Irish-made hats and caps from Emerald Rozalia Limited, proudly based in Limerick, Ireland.','focus_keyword'=>'emerald rozalia hats','noindex'=>false]]);
  SeoSetting::updateOrCreate(['company_id'=>$company->id,'key'=>'robots_txt'],['value'=>"User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /account\nDisallow: /checkout\n\nSitemap: https://emeraldrozalia.com/sitemap.xml\n"]);
  SeoSetting::updateOrCreate(['company_id'=>$company->id,'key'=>'organization_schema'],['value'=>['@context'=>'https://schema.org','@type'=>'Organization','name'=>'Emerald Rozalia Limited','url'=>'https://emeraldrozalia.com','logo'=>'https://emeraldrozalia.com/assets/brand/emerald-rozalia-wordmark.png','address'=>['@type'=>'PostalAddress','addressLocality'=>'Limerick','addressCountry'=>'IE']]]);
  SeoSetting::updateOrCreate(['company_id'=>$company->id,'key'=>'keywords'],['value'=>[['keyword'=>'emerald rozalia hats','position'=>null,'change'=>null,'target'=>'/'],['keyword'=>'luxury caps ireland','position'=>null,'change'=>null,'target'=>'/shop'],['keyword'=>'premium baseball caps','position'=>null,'change'=>null,'target'=>'/category/baseball-caps'],['keyword'=>'emerald signature cap','position'=>null,'change'=>null,'target'=>'/product/emerald-signature-cap'],['keyword'=>'franchise hats ireland','position'=>null,'change'=>null,'target'=>'/franchise']]]);
  foreach(['website-products','online-sales','customers','franchise-management','communication-center','reports','users-roles','integrations','settings','audit-logs','automation','backup-recovery','system-maintenance','returns-refunds','media-manager'] as $module)AdminRecord::firstOrCreate(['module'=>$module,'reference'=>'ER-READY'],['company_id'=>$company->id,'title'=>str($module)->headline().' readiness','status'=>'active','user_id'=>$admin->id,'data'=>['seeded'=>true]]);
 }
}
