<div class="vm-form-grid">
<label class="wide">Product<select name="product_id" data-field="product_id" required><option value="">Choose product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} — {{ $product->sku }}</option>@endforeach</select></label>
<label>Variant SKU<input name="sku" data-field="sku" maxlength="120" placeholder="Auto-generated if blank"></label><label>Barcode<input name="barcode" data-field="barcode" maxlength="120"></label>
<label>Colour<input name="colour" data-field="colour" maxlength="120"></label><label>Size<input name="size" data-field="size" maxlength="120"></label><label>Material<input name="material" data-field="material" maxlength="120"></label><label>Style<input name="style" data-field="style" maxlength="120"></label>
<label>Price<input type="number" step="0.01" min="0" name="price" data-field="price"></label><label>Compare Price<input type="number" step="0.01" min="0" name="compare_price" data-field="compare_price"></label><label>Cost Price<input type="number" step="0.01" min="0" name="cost_price" data-field="cost_price"></label>
<label>Available Stock<input type="number" min="0" name="stock" data-field="stock" value="0" required></label><label>Total Stock<input type="number" min="0" name="stock_total" data-field="stock_total" value="0"></label><label>Low Stock Threshold<input type="number" min="0" name="low_stock_threshold" data-field="low_stock_threshold" value="{{ $settings->low_stock_threshold }}"></label>
<label>Status<select name="status" data-field="status" required><option value="active">Active</option><option value="inactive">Inactive</option><option value="discontinued">Discontinued</option></select></label>
<label class="vm-check"><input type="hidden" name="track_inventory" value="0"><input type="checkbox" name="track_inventory" value="1" data-field="track_inventory" @checked($settings->track_variant_inventory)> Track inventory</label><label class="vm-check"><input type="hidden" name="backorder" value="0"><input type="checkbox" name="backorder" value="1" data-field="backorder" @checked($settings->backorder)> Allow backorder</label>
</div>
