@extends('layouts.admin')
@section('title', 'Cart & Checkout')
@section('content')
<style>
.cc-dashboard{--cc-ink:#17231d;--cc-muted:#68766e;--cc-line:#e2e8e4;--cc-green:#08753d;color:var(--cc-ink);font-family:Inter,Arial,sans-serif;font-size:12px;display:grid;gap:14px;min-width:0}
.cc-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:20px}.cc-heading h1{margin:0 0 4px;font-size:24px;line-height:1.15}.cc-heading p{margin:0;color:var(--cc-muted);font-size:12px}.cc-heading-actions{display:flex;align-items:center;gap:10px}.cc-date{display:flex;align-items:center;gap:10px;border:1px solid var(--cc-line);border-radius:7px;background:#fff;padding:9px 12px;white-space:nowrap}.cc-date .ui-icon{color:var(--cc-green)}.cc-date span{display:grid;gap:2px}.cc-date small{color:var(--cc-muted);font-size:10px}.cc-date strong{font-size:12px}
.cc-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid #cfdad2;border-radius:6px;background:#fff;color:var(--cc-ink);padding:9px 12px;font-size:11px;font-weight:700;cursor:pointer}.cc-btn:hover{border-color:#80b38e;background:#f7fbf8}.cc-btn-primary{background:var(--cc-green);border-color:var(--cc-green);color:#fff}
.cc-state{display:flex;align-items:flex-start;gap:8px;border:1px solid #cfe2d4;background:#f4fbf5;color:#355341;padding:10px 12px;border-radius:7px;font-size:11px}.cc-state--period{border-color:#d8e2ed;background:#f6f9fc;color:#425b70}.cc-state .ui-icon{color:var(--cc-green);flex:none}.cc-state strong{display:block;color:#20392a;margin-bottom:2px}.cc-state small{display:block;color:inherit;font-size:10px}
.cc-kpis{display:grid;grid-template-columns:repeat(6,minmax(150px,1fr));gap:10px}.cc-kpi{position:relative;min-height:102px;border:1px solid var(--cc-line);border-radius:8px;background:#fff;padding:14px 9px 11px 54px}.cc-kpi-icon{position:absolute;left:13px;top:16px;width:34px;height:34px;display:grid;place-items:center;border-radius:50%;color:#fff}.cc-kpi-icon.green{background:#08753d}.cc-kpi-icon.orange{background:#f07d1a}.cc-kpi-icon.blue{background:#246fc7}.cc-kpi-icon.purple{background:#6844ae}.cc-kpi-icon.teal{background:#187a7b}.cc-kpi-icon.red{background:#d83952}.cc-kpi label{display:block;color:var(--cc-muted);font-weight:700;font-size:10px;line-height:1.25}.cc-kpi strong{display:block;color:#101b16;font-size:20px;margin:7px 0 5px;white-space:nowrap}.cc-kpi small{display:block;color:var(--cc-muted);font-size:9px;line-height:1.3}
.cc-layout{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:14px;align-items:start}.cc-main{min-width:0}.cc-tabs{display:flex;gap:19px;overflow-x:auto;border-bottom:1px solid var(--cc-line);margin-bottom:12px}.cc-tab{padding:10px 0;color:#526159;white-space:nowrap;border-bottom:2px solid transparent;font-weight:700;font-size:11px}.cc-tab.active{color:var(--cc-green);border-bottom-color:var(--cc-green)}
.cc-toolbar{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-bottom:12px}.cc-search{display:flex;align-items:center;gap:7px;flex:1;min-width:200px;max-width:310px;border:1px solid #cfdad2;background:#fff;border-radius:6px;padding:0 9px}.cc-search .ui-icon{color:#718077}.cc-search input{width:100%;border:0;background:transparent;color:var(--cc-ink);padding:9px 0;outline:0;font-size:11px}.cc-select{border:1px solid #cfdad2;background:#fff;border-radius:6px;color:var(--cc-ink);padding:9px 25px 9px 9px;font-size:11px}.cc-reset{color:var(--cc-muted);font-size:11px}
.cc-table-wrap{overflow-x:auto;border:1px solid var(--cc-line);border-radius:8px;background:#fff}.cc-table{width:100%;border-collapse:collapse;min-width:940px}.cc-table th,.cc-table td{padding:11px 10px;border-bottom:1px solid #edf1ee;text-align:left;vertical-align:middle}.cc-table th{background:#fbfcfb;color:#6a776f;font-size:9px;text-transform:uppercase;letter-spacing:.02em;white-space:nowrap}.cc-table tbody tr:hover{background:#fbfefc}.cc-table tbody tr:last-child td{border-bottom:0}.cc-customer strong{display:block;font-size:11px;white-space:nowrap}.cc-customer small,.cc-id small{display:block;color:var(--cc-muted);font-size:9px;margin-top:3px;white-space:nowrap}.cc-id strong{font-size:10px;white-space:nowrap}.cc-source{display:flex;align-items:center;gap:5px;color:#42534a;white-space:nowrap}.cc-status{display:inline-flex;align-items:center;border-radius:4px;padding:4px 7px;font-size:9px;font-weight:700;white-space:nowrap}.cc-status.active,.cc-status.completed{background:#daf2e1;color:#14723c}.cc-status.abandoned{background:#ffe3e2;color:#c73637}.cc-status.checkout_started{background:#dcecff;color:#2562ae}.cc-status.payment_pending{background:#fff0d4;color:#bd6910}.cc-status.saved{background:#eee5ff;color:#6640a5}.cc-status.cancelled,.cc-status.refunded,.cc-status.unknown{background:#eef1f0;color:#5e6d65}.cc-progress{display:flex;align-items:center;gap:7px;min-width:110px}.cc-progress-track{width:72px;height:5px;border-radius:3px;background:#e4e9e6;overflow:hidden}.cc-progress-track i{display:block;height:100%;background:var(--cc-green);border-radius:3px}.cc-progress small{color:#55645b;font-size:9px;white-space:nowrap}.cc-money{font-weight:700;white-space:nowrap}.cc-last{white-space:nowrap;color:#56645d;font-size:10px}.cc-actions{display:flex;gap:5px}.cc-icon-btn{display:grid;place-items:center;width:27px;height:27px;border:1px solid #dce4df;border-radius:5px;background:#fff;color:#607067;cursor:pointer}.cc-icon-btn:hover{border-color:#83bb92;color:var(--cc-green);background:#f5fbf7}
.cc-pagination{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 2px;color:#627069;font-size:10px}.cc-pagination nav{display:flex;align-items:center;gap:5px}.cc-pagination nav a,.cc-pagination nav span{display:grid;place-items:center;min-width:26px;height:26px;border:1px solid #dce4df;border-radius:5px;background:#fff;color:#435249}.cc-pagination nav span[aria-current=page]{background:var(--cc-green);border-color:var(--cc-green);color:#fff}
.cc-side{display:grid;gap:12px}.cc-panel{border:1px solid var(--cc-line);border-radius:8px;background:#fff;padding:14px}.cc-panel h2{margin:0 0 12px;color:var(--cc-green);font-size:11px;text-transform:uppercase;letter-spacing:.03em}.cc-panel h2 span{color:#78867e;text-transform:none;font-weight:400}.cc-summary-list{display:grid;gap:9px}.cc-summary-row{display:flex;justify-content:space-between;gap:10px;color:#59665f;font-size:10px}.cc-summary-row strong{color:#17231d;text-align:right}.cc-summary-link{display:flex;align-items:center;justify-content:space-between;border-top:1px solid #edf1ee;padding-top:10px;margin-top:4px;color:var(--cc-green);font-weight:700;font-size:10px}.cc-data-source{color:#78867e;font-size:9px;font-weight:400}.cc-insight{display:flex;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #eef2ef;font-size:10px}.cc-insight:last-of-type{border-bottom:0}.cc-insight b{color:#1b2b22;text-align:right}.cc-insight em{color:#2c8b50;font-style:normal;font-weight:700}.cc-insight small{display:block;color:#78867e;font-size:8px;margin-top:3px}.cc-quick{display:grid;gap:9px}.cc-quick a{display:flex;align-items:center;gap:8px;color:#33443a;font-size:10px}.cc-quick a:hover{color:var(--cc-green)}.cc-quick .ui-icon{color:#617169}.cc-activity{display:grid;gap:9px}.cc-activity-row{display:flex;gap:7px;align-items:flex-start;font-size:10px}.cc-activity-dot{width:7px;height:7px;border-radius:50%;background:#19864a;flex:none;margin-top:3px}.cc-activity-dot.orange{background:#ee8a1d}.cc-activity-dot.blue{background:#2c77cd}.cc-activity-dot.purple{background:#7b55be}.cc-activity-row small{display:block;color:#829087;font-size:9px;margin-top:2px}.cc-empty{padding:28px;text-align:center;color:#718078}.cc-empty strong{display:block;color:#25372c;font-size:13px;margin-bottom:5px}.cc-empty-inline{padding:10px 0;color:#718078;font-size:10px}
.cc-bottom{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr 1fr;gap:12px}.cc-bottom .cc-panel{min-height:205px}.cc-funnel{display:grid;gap:6px;margin-top:9px}.cc-funnel-row{display:grid;grid-template-columns:104px 1fr 46px;align-items:center;gap:7px;font-size:9px}.cc-funnel-row span{white-space:nowrap;color:#58665e}.cc-funnel-bar{height:13px;background:#e8eeea;border-radius:3px;overflow:hidden}.cc-funnel-bar i{display:block;height:100%;border-radius:3px}.cc-funnel-row strong{font-size:9px;text-align:right;white-space:nowrap}.cc-bars{display:flex;align-items:flex-end;justify-content:space-around;height:125px;border-bottom:1px solid #dfe7e2;padding:10px 8px 0}.cc-bars i{width:13%;min-height:3px;border-radius:4px 4px 0 0;background:#2179d0}.cc-bars i:nth-child(2){background:#f28a21}.cc-bars i:nth-child(3){background:#18834a}.cc-bars i:nth-child(4){background:#754bb3}.cc-bars i:nth-child(5){background:#159c9d}.cc-mini-donut{display:grid;place-items:center;width:112px;height:112px;margin:9px auto;border-radius:50%;background:conic-gradient(#e8eeea 0 100%);position:relative}.cc-mini-donut:after{content:'';position:absolute;inset:25px;background:#fff;border-radius:50%}.cc-mini-donut strong{position:relative;z-index:1;font-size:16px}.cc-legend{display:grid;gap:5px;font-size:9px;color:#637168}.cc-legend span{display:flex;justify-content:space-between;gap:8px}.cc-legend b{font-weight:600}.cc-legend em{font-style:normal;text-align:right;white-space:nowrap}.cc-legend i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px;background:#147841}.cc-legend i.blue{background:#2573c6}.cc-legend i.orange{background:#ee8b20}.cc-legend i.purple{background:#724aaf}.cc-legend i.teal{background:#159c9d}
@media(max-width:1300px){.cc-kpis{grid-template-columns:repeat(3,1fr)}.cc-bottom{grid-template-columns:repeat(2,1fr)}.cc-bottom .cc-panel:first-child{grid-column:span 2}}@media(max-width:980px){.cc-layout{grid-template-columns:1fr}.cc-side{grid-template-columns:repeat(2,minmax(0,1fr))}.cc-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.cc-heading{display:grid}.cc-heading-actions{justify-content:space-between;flex-wrap:wrap}.cc-kpis{grid-template-columns:1fr 1fr}.cc-side,.cc-bottom{grid-template-columns:1fr}.cc-bottom .cc-panel:first-child{grid-column:auto}.cc-pagination{align-items:flex-start;flex-direction:column}}
</style>

<div class="cc-dashboard">
    <header class="cc-heading">
        <div>
            <small style="color:#16824a;font-weight:700;letter-spacing:.05em">ONLINE SALES / CART &amp; CHECKOUT</small>
            <h1>Cart &amp; Checkout</h1>
            <p>Monitor carts, checkout activity, conversions and abandonment using recorded Project 1 data.</p>
        </div>
        <div class="cc-heading-actions">
            <a class="cc-btn" href="{{ route('admin.cart-checkout.export', request()->query()) }}"><x-icon name="download" size="14" /> Export Report (CSV)</a>
            <div class="cc-date"><x-icon name="calendar" size="19" /><span><small>Today</small><strong>{{ now()->format('l, d M Y') }}</strong></span></div>
        </div>
    </header>

    @if(! $hasLiveData)
        <div class="cc-state" role="status"><x-icon name="info" size="14" /><span><strong>No live checkout activity recorded yet.</strong>Checkout tracking has not recorded any live carts or online orders. Operational values will appear after real checkout data is stored.</span></div>
    @elseif(! $periodHasData)
        <div class="cc-state cc-state--period" role="status"><x-icon name="info" size="14" /><span><strong>No checkout activity recorded in {{ $periodLabel }}.</strong>Live records exist outside the current reporting period, so this month's KPI and analysis panels remain zero or unrecorded.</span></div>
    @endif

    <section class="cc-kpis" aria-label="Checkout metrics">
        @foreach($metrics as $metric)
            <article class="cc-kpi">
                <span class="cc-kpi-icon {{ $metric['tone'] }}"><x-icon name="{{ $metric['icon'] }}" size="18" /></span>
                <label>{{ $metric['label'] }}</label>
                <strong>{{ $metric['value'] }}</strong>
                <small>{{ $metric['source'] }}</small>
            </article>
        @endforeach
    </section>

    <div class="cc-layout">
        <section class="cc-main">
            <nav class="cc-tabs" aria-label="Cart and checkout sections">
                @foreach($tabs as $tabKey => $tabLabel)
                    <a class="cc-tab {{ $tab === $tabKey ? 'active' : '' }}" href="{{ route('admin.cart-checkout', array_merge(request()->except('page','tab'), ['tab' => $tabKey])) }}">{{ $tabLabel }}</a>
                @endforeach
            </nav>

            <form class="cc-toolbar" method="get" action="{{ route('admin.cart-checkout') }}">
                <input type="hidden" name="tab" value="{{ $tab }}">
                <label class="cc-search"><x-icon name="search" size="14" /><input name="q" value="{{ $search }}" placeholder="Search by cart ID, customer, email, phone, or UUID..." aria-label="Search carts and checkouts"></label>
                <select class="cc-select" name="status" aria-label="Filter by status"><option value="">All Cart Status</option>@foreach($statusOptions as $value => $label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select>
                <select class="cc-select" name="source" aria-label="Filter by source"><option value="">All Sources</option>@foreach($sourceOptions as $value)<option value="{{ $value }}" @selected($source === $value)>{{ $value }}</option>@endforeach</select>
                <button class="cc-btn cc-btn-primary" type="submit"><x-icon name="filter" size="13" /> Apply</button>
                <a class="cc-reset" href="{{ route('admin.cart-checkout', ['tab' => $tab]) }}"><x-icon name="refresh" size="12" /> Reset</a>
            </form>

            <div class="cc-table-wrap">
                <table class="cc-table">
                    <thead><tr><th>TYPE</th><th>CART / CHECKOUT ID</th><th>CUSTOMER</th><th>SOURCE / CHANNEL</th><th>STATUS</th><th>CART VALUE</th><th>PROGRESS</th><th>LAST ACTIVITY</th><th>ACTIONS</th></tr></thead>
                    <tbody>
                    @forelse($rows as $row)
                        <tr>
                            <td><x-icon name="{{ $row->status === 'completed' ? 'check' : 'shopping-bag' }}" size="15" style="color:{{ $row->status === 'completed' ? '#784bb2' : '#08753d' }}" /></td>
                            <td class="cc-id"><strong>{{ $row->reference }}</strong><small>{{ $row->public_uuid }}</small></td>
                            <td class="cc-customer"><strong>{{ $row->customer }}</strong><small>{{ $row->email }}</small></td>
                            <td><span class="cc-source"><x-icon name="{{ str_contains(strtolower($row->source), 'app') ? 'phone' : (str_contains(strtolower($row->source), 'portal') ? 'briefcase' : 'globe') }}" size="13" /> {{ $row->source }}</span></td>
                            <td><span class="cc-status {{ $row->status }}">{{ $row->status_label }}</span></td>
                            <td class="cc-money">@if($row->amount !== null){{ $row->currency }} {{ number_format($row->amount, 2) }}@else—@endif</td>
                            <td><div class="cc-progress"><span class="cc-progress-track"><i style="width:{{ $row->progress_percent }}%"></i></span><small>{{ $row->progress_label }}</small></div></td>
                            <td class="cc-last">{{ $row->last_activity }}</td>
                            <td><div class="cc-actions">
                                @if($row->order_id)<a class="cc-icon-btn" href="{{ route('admin.order-master.show', ['online', $row->order_id]) }}" title="View order"><x-icon name="eye" size="14" /></a>@endif
                                @if($row->record_id && in_array($row->status, ['abandoned', 'saved'], true))<form method="post" action="{{ route('admin.cart-checkout.action', $row->record_id) }}">@csrf<input type="hidden" name="action" value="restore"><button class="cc-icon-btn" type="submit" title="Restore cart"><x-icon name="refresh" size="14" /></button></form>@endif
                                @if($row->record_id && in_array($row->status, ['abandoned', 'saved'], true) && $row->email !== 'Not recorded')<form method="post" action="{{ route('admin.cart-checkout.action', $row->record_id) }}">@csrf<input type="hidden" name="action" value="send_recovery"><button class="cc-icon-btn" type="submit" title="Request recovery message"><x-icon name="mail" size="14" /></button></form>@endif
                                @if($row->record_id && in_array($row->status, ['active', 'checkout_started', 'payment_pending'], true))<form method="post" action="{{ route('admin.cart-checkout.action', $row->record_id) }}">@csrf<input type="hidden" name="action" value="complete"><button class="cc-icon-btn" type="submit" title="Mark checkout complete"><x-icon name="check" size="14" /></button></form>@endif
                            </div></td>
                        </tr>
                    @empty
                        <tr><td colspan="9"><div class="cc-empty"><strong>{{ $hasLiveData ? 'No checkout records match these filters' : 'No live carts or online orders recorded' }}</strong><span>{{ $hasLiveData ? 'Try resetting the filters or choose another checkout section.' : 'This table will populate from the cart tracker and online order records.' }}</span></div></td></tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="cc-pagination"><span>Showing {{ $rows->firstItem() ?: 0 }} to {{ $rows->lastItem() ?: 0 }} of {{ number_format($rows->total()) }} records</span>{{ $rows->onEachSide(1)->links() }}</div>
        </section>

        <aside class="cc-side">
            <section class="cc-panel"><h2>Checkout Summary <span>({{ $periodLabel }})</span></h2><div class="cc-summary-list"><div class="cc-summary-row"><span>Total Carts</span><strong>{{ $summary['total_carts'] }}</strong></div><div class="cc-summary-row"><span>Active Carts</span><strong>{{ $summary['active_carts'] }}</strong></div><div class="cc-summary-row"><span>Abandoned Carts</span><strong>{{ $summary['abandoned_carts'] }}</strong></div><div class="cc-summary-row"><span>Checkout Started</span><strong>{{ $summary['checkout_started'] }}</strong></div><div class="cc-summary-row"><span>Completed Orders</span><strong>{{ $summary['completed_orders'] }}</strong></div><div class="cc-summary-row"><span>Conversion Rate</span><strong>{{ $summary['conversion_rate'] }}</strong></div><div class="cc-summary-row"><span>Revenue</span><strong>{{ $summary['revenue'] }}</strong></div></div><a class="cc-summary-link" href="{{ route('admin.resource','sales-reports') }}">View Full Checkout Report <x-icon name="arrow-right" size="13" /></a></section>
            <section class="cc-panel"><h2>Abandonment Insights</h2><div class="cc-insight"><span>Abandonment Rate<small>{{ $insights['abandonment_rate']['source'] }}</small></span><b>{{ $insights['abandonment_rate']['value'] }}</b></div><div class="cc-insight"><span>Most Abandoned Step<small>{{ $insights['most_abandoned_step']['source'] }}</small></span><b>{{ $insights['most_abandoned_step']['value'] }}</b></div><div class="cc-insight"><span>Avg. Abandoned Cart Value<small>{{ $insights['average_abandoned_value']['source'] }}</small></span><b>{{ $insights['average_abandoned_value']['value'] }}</b></div><div class="cc-insight"><span>Recovery Messages Requested<small>{{ $insights['recovery_requested']['source'] }}</small></span><b>{{ $insights['recovery_requested']['value'] }}</b></div><div class="cc-insight"><span>Recovered Carts<small>{{ $insights['recovered_carts']['source'] }}</small></span><b>{{ $insights['recovered_carts']['value'] }}</b></div><a class="cc-summary-link" href="{{ route('admin.cart-checkout', ['tab'=>'abandoned']) }}">View Abandonment Report <x-icon name="arrow-right" size="13" /></a></section>
            <section class="cc-panel"><h2>Quick Actions</h2><div class="cc-quick"><a href="{{ route('admin.cart-checkout', ['tab'=>'abandoned']) }}"><x-icon name="eye" size="14" /> View Abandoned Carts</a><a href="{{ route('admin.cart-checkout', ['tab'=>'abandoned']) }}"><x-icon name="mail" size="14" /> Review Recovery Candidates</a><a href="{{ route('admin.resource','discounts-coupons') }}"><x-icon name="tag" size="14" /> Create Promo for Abandoners</a><a href="{{ route('admin.cart-checkout', ['tab'=>'saved']) }}"><x-icon name="heart" size="14" /> View Saved Carts</a><a href="{{ route('admin.resource','shipping-delivery') }}"><x-icon name="truck" size="14" /> Manage Shipping Methods</a><a href="{{ route('admin.resource','payment-settings') }}"><x-icon name="settings" size="14" /> Checkout Settings</a></div></section>
            <section class="cc-panel"><h2>Recent Activity <a href="{{ route('admin.cart-checkout') }}" style="float:right;text-transform:none;color:#157743;font-size:9px">View All</a></h2><div class="cc-activity">@forelse($recentActivity as $activity)<div class="cc-activity-row"><i class="cc-activity-dot {{ $activity['tone'] }}"></i><div>{{ $activity['label'] }}<small>{{ $activity['time'] }}</small></div></div>@empty<div class="cc-empty-inline">No recent checkout activity recorded.</div>@endforelse</div></section>
        </aside>
    </div>

    <section class="cc-bottom">
        <div class="cc-panel"><h2>Checkout Steps Funnel <span>({{ $periodLabel }})</span></h2><div class="cc-funnel">@foreach($funnel as $step)<div class="cc-funnel-row"><span>{{ $step['label'] }}</span><span class="cc-funnel-bar"><i style="width:{{ min(100, max(0, $step['percent'])) }}%;background:{{ $step['tone'] === 'green' ? '#147b43' : ($step['tone'] === 'blue' ? '#2578d4' : ($step['tone'] === 'purple' ? '#714bb1' : '#ed861e')) }}"></i></span><strong>{{ $step['value'] }} <small>({{ $step['percent'] }}%)</small></strong></div>@endforeach</div><a class="cc-summary-link" href="{{ route('admin.cart-checkout', ['tab'=>'funnel']) }}">View Funnel Analysis <x-icon name="arrow-right" size="13" /></a></div>
        <div class="cc-panel"><h2>Carts by Source <span>({{ $periodLabel }})</span></h2><div class="cc-mini-donut" style="background:{{ $sourceDonutStyle }}"><strong>{{ $summary['total_carts'] }}</strong></div><div class="cc-legend">@forelse($sources as $sourceRow)<span><b><i class="{{ $loop->index === 1 ? 'blue' : ($loop->index === 2 ? 'orange' : ($loop->index === 3 ? 'purple' : ($loop->index === 4 ? 'teal' : ''))) }}"></i>{{ $sourceRow['label'] }}</b><em>{{ $sourceRow['count'] }} ({{ $sourceRow['percent'] }}%)</em></span>@empty<div class="cc-empty-inline">No source data recorded.</div>@endforelse</div></div>
        <div class="cc-panel"><h2>Top Abandoned Reasons <span>({{ $periodLabel }})</span></h2><div class="cc-funnel">@forelse($abandonedReasons as $reason)<div class="cc-funnel-row"><span>{{ $reason['label'] }}</span><span class="cc-funnel-bar"><i style="width:{{ min(100, max(0, $reason['bar_percent'])) }}%;background:#2179d0"></i></span><strong>{{ $reason['percent'] }}% <small>({{ $reason['count'] }})</small></strong></div>@empty<div class="cc-empty-inline">No abandonment reasons recorded.</div>@endforelse</div><a class="cc-summary-link" href="{{ route('admin.cart-checkout', ['tab'=>'analytics']) }}">View Abandonment Reasons <x-icon name="arrow-right" size="13" /></a></div>
        @php($deviceTotal = collect($devices)->sum('count'))
        <div class="cc-panel"><h2>Devices <span>({{ $periodLabel }})</span></h2><div class="cc-mini-donut" style="background:{{ $deviceDonutStyle }}"><strong>{{ number_format($deviceTotal) }}</strong></div><div class="cc-legend">@forelse($devices as $device)<span><b><i class="{{ $loop->index === 1 ? 'blue' : ($loop->index === 2 ? 'orange' : ($loop->index === 3 ? 'purple' : ($loop->index === 4 ? 'teal' : ''))) }}"></i>{{ $device['label'] }}</b><em>{{ $device['count'] }} ({{ $device['percent'] }}%)</em></span>@empty<div class="cc-empty-inline">No device data recorded.</div>@endforelse</div></div>
        <div class="cc-panel"><h2>Payment Preferences <span>(Orders)</span></h2>@if($paymentPreferences)<div class="cc-bars">@foreach($paymentPreferences as $payment)<i style="height:{{ max(3, min(100, $payment['percent'])) }}%" title="{{ $payment['label'] }}: {{ $payment['count'] }}"></i>@endforeach</div><div class="cc-legend" style="margin-top:8px">@foreach($paymentPreferences as $payment)<span><b><i class="{{ $loop->index === 1 ? 'blue' : ($loop->index === 2 ? 'orange' : ($loop->index === 3 ? 'purple' : ($loop->index === 4 ? 'teal' : ''))) }}"></i>{{ $payment['label'] }}</b><em>{{ $payment['count'] }} ({{ $payment['percent'] }}%)</em></span>@endforeach</div>@else<div class="cc-empty-inline">No payment preference data recorded.</div>@endif</div>
    </section>
</div>
@endsection
