@extends('layouts.admin')
@section('title','Dashboard')
@section('content')
<div class="admin-title"><div><h1>Welcome back, Admin! 👋</h1><p>Here’s what’s happening with Emerald Rozalia today.</p></div><a class="btn" href="/">Visit Website →</a></div>
<div class="admin-kpis">
    <div><span class="kpi-icon">♙</span><small>Franchise Applications</small><b>{{$franchiseApplications}}</b><em>Live records</em></div>
    <div><span class="kpi-icon">♙♙</span><small>Active Franchisees</small><b>{{$activeFranchisees}}</b><em>Approved / active</em></div>
    <div><span class="kpi-icon">▣</span><small>Franchise Retail Stores</small><b>{{$retailStores}}</b><em>Active / published</em></div>
    <div><span class="kpi-icon">♧</span><small>Franchise Orders</small><b>{{$franchiseOrders}}</b><em>All recorded orders</em></div>
    <div><span class="kpi-icon">◉</span><small>Total Sales</small><b>€{{number_format($revenue,2)}}</b><em>Paid orders</em></div>
    <div><span class="kpi-icon">◌</span><small>Open Conversations</small><b>{{$openConversations}}</b><em>New / open / pending</em></div>
</div>
<div class="admin-dashboard-grid">
    <section class="panel dashboard-panel"><div class="panel-heading"><h2>Franchise Pipeline Overview</h2><a href="{{route('admin.resource','franchise-management')}}">View details →</a></div><div class="pipeline"><div class="pipeline-bar"><i></i><i></i><i></i><i></i><i></i></div><div class="pipeline-legend"><span><b>{{$franchiseApplications}}</b> Applications received</span><span><b>{{$activeFranchisees}}</b> Approved / active</span><span><b>{{$retailStores}}</b> Retail stores</span></div><p class="empty-note">Pipeline stages will populate as franchise applications move through review.</p></div></section>
    <section class="panel dashboard-panel"><div class="panel-heading"><h2>Franchise Retail Store Map</h2><a href="{{route('admin.resource','franchise-management')}}">Manage stores →</a></div><div class="map-placeholder"><span>◎</span><p>Store locations appear here when retail stores have a mapped address.</p></div></section>
    <section class="panel dashboard-panel"><div class="panel-heading"><h2>Franchise Performance</h2><span class="panel-caption">All time</span></div><div class="performance"><div class="donut"><span>€{{number_format($revenue,2)}}</span></div><ul><li>Paid sales <b>€{{number_format($revenue,2)}}</b></li><li>Franchise orders <b>{{$franchiseOrders}}</b></li><li>Total orders <b>{{$totalOrders}}</b></li></ul></div></section>
    <section class="panel dashboard-panel activities"><div class="panel-heading"><h2>Recent Activities</h2><a href="{{route('admin.resource','audit-logs')}}">View all →</a></div>@forelse($orders->take(5) as $order)<div class="activity-row"><span class="activity-dot"></span><div><b>Order {{$order->number}}</b><small>{{$order->status}} · {{$order->created_at?->diffForHumans()}}</small></div></div>@empty<p class="empty-note">No recent orders recorded.</p>@endforelse</section>
    <section class="panel dashboard-panel order-categories"><div class="panel-heading"><h2>Order Categories</h2><span class="panel-caption">All order masters</span></div><div class="category-grid">@foreach(['online'=>'Online Orders','corporate'=>'Corporate Orders','bulk'=>'Bulk Orders','franchise'=>'Franchise Orders','franchise_retail'=>'Franchise Retail','buyer'=>'Buyer Orders'] as $type=>$label)<a href="{{route('admin.order-master',$type)}}"><b>{{\App\Models\Order::where('order_type',$type)->count()}}</b><span>{{$label}}</span><small>View orders →</small></a>@endforeach</div></section>
    <section class="panel dashboard-panel"><div class="panel-heading"><h2>System Overview</h2></div><div class="system-list"><p>Products <b>{{$products}}</b></p><p>Customers <b>{{$customers}}</b></p><p>Low stock products <b>{{$lowStock}}</b></p><p>New enquiries <b>{{$inquiries}}</b></p><p>Website <b class="good">Online</b></p><p>Database <b class="good">Connected</b></p></div></section>
</div>
<section class="panel business-flow"><div class="panel-heading"><h2>Franchise Business Flow — Application to Active Store</h2><span class="panel-caption">Live workflow stages</span></div><div class="flow-steps">@foreach(['Application received','Initial screening','Meeting scheduled','Due diligence','Agreement sent','Approved','Store setup','Store opened','Active & growing'] as $i=>$stage)<div class="flow-step"><span>{{$i+1}}</span><b>{{$stage}}</b><small>Tracked in Project 1</small></div>@endforeach</div></section>
@endsection
