@extends('layouts.admin')

@section('title', $title)

@push('styles')
    <link rel="stylesheet" href="/css/reports-reference.css?v=20260913-b20-1">
@endpush

@php
    $url = fn (string $name, array $params = []) => route('admin.reports.'.$name, $params);
    $cards = $metrics ?? $returnMetrics ?? $historyMetrics ?? $roleMetrics ?? [];
    $metricTone = fn ($tone) => ['green'=>'green','blue'=>'blue','purple'=>'purple','orange'=>'orange','red'=>'red','teal'=>'teal','gold'=>'gold'][$tone] ?? 'green';
    $pillTone = fn ($status) => in_array(strtolower((string) $status), ['success','approved','active','healthy'], true) ? 'success' : (in_array(strtolower((string) $status), ['failed','rejected','danger','deleted','cancelled'], true) ? 'danger' : 'warning');
    $nav = ['overview'=>'Overview','approvals'=>'Approvals','custom'=>'Custom Reports','history'=>'History','returns'=>'Returns & Refunds','roles'=>'Roles & Permissions','scheduler'=>'Scheduler'];
@endphp

@section('content')
<div class="reports-page" data-reports-root>
    <header class="reports-header">
        <div><h1>{{ $title }}</h1><p>{{ $subtitle }}</p></div>
        <div class="reports-header-actions">
            <a class="reports-btn reports-btn-soft" href="{{ $url('export', ['name' => $section]) }}">⇩ Export</a>
            @if($section !== 'custom')<a class="reports-btn reports-btn-primary" href="{{ $url('custom') }}">＋ Build Report</a>@endif
        </div>
    </header>

    <nav class="reports-tabs" aria-label="Report sections">
        @foreach($nav as $key => $label)<a class="{{ $section === $key ? 'active' : '' }}" href="{{ $url($key) }}">{{ $label }}</a>@endforeach
    </nav>

    @if(isset($dataNote))
        <div class="reports-toolbar-note" role="status"><x-icon name="info" size="14" /> {{ $dataNote }}</div>
    @endif

    @if($section === 'overview')
        <div class="reports-toolbar">
            <form method="GET" action="{{ $url('overview') }}" class="reports-filters">
                <label><span>Company / Entity</span><select name="company"><option value="All Companies">All Companies</option><option value="Emerald Rozalia Ltd." @selected(($filters['company'] ?? '') === 'Emerald Rozalia Ltd.')>Emerald Rozalia Ltd.</option></select></label>
                <label><span>Module</span><select name="module"><option value="all">All Modules</option>@foreach(($moduleOptions ?? []) as $module)<option value="{{ $module }}" @selected(($filters['module'] ?? request('module')) === $module)>{{ $module }}</option>@endforeach</select></label>
                <label><span>Date Range</span><input type="date" name="from" value="{{ $filters['from']->format('Y-m-d') }}"><b>–</b><input type="date" name="to" value="{{ $filters['to']->format('Y-m-d') }}"></label>
                <label><span>Compare With</span><select name="compare"><option value="previous_period" @selected(($filters['compare'] ?? '') === 'previous_period')>Previous Period</option><option value="previous_year" @selected(($filters['compare'] ?? '') === 'previous_year')>Previous Year</option></select></label>
                <label><span>Data View</span><select name="view"><option value="summary" @selected(($filters['view'] ?? '') === 'summary')>Summary</option><option value="detailed" @selected(($filters['view'] ?? '') === 'detailed')>Detailed</option></select></label>
                <button class="reports-btn reports-btn-soft" type="submit">Apply Filters</button>
            </form>
            <span>Live database data · {{ $filters['from_label'] }} – {{ $filters['to_label'] }}</span>
        </div>

        <section class="reports-metric-grid reports-metric-grid--eight">
            @foreach($cards as $card)<article class="reports-metric"><span class="reports-metric-icon reports-tone-{{ $metricTone($card['tone']) }}"><x-icon name="{{ $card['icon'] }}" size="18" /></span><div><small>{{ $card['label'] }}</small><strong>{{ $card['value'] }}</strong><em>{{ $card['change'] ?? 'Live' }}</em></div></article>@endforeach
        </section>

        <div class="reports-three-grid">
            <section class="reports-card"><div class="reports-card-head"><div><h2>Report Library by Module</h2><p>Only persisted report records are counted.</p></div><a href="{{ $url('custom') }}">Manage</a></div><div class="reports-library">
                @forelse($moduleRows as $row)<a href="{{ $url('history', ['module' => $row['label']]) }}"><x-icon name="folder" size="15" /><span>{{ $row['label'] }}</span><b>{{ number_format($row['count']) }}</b></a>@empty<div class="reports-empty">No persisted report modules in this period.</div>@endforelse
            </div></section>
            <section class="reports-card"><div class="reports-card-head"><div><h2>Recent Report Runs</h2><p>Latest persisted executions.</p></div><a href="{{ $url('history') }}">View All</a></div><table class="reports-table"><thead><tr><th>Report</th><th>Module</th><th>Records</th><th>Run On</th></tr></thead><tbody>
                @forelse($runs as $run)<tr><td><strong>{{ $run->title }}</strong></td><td>{{ data_get($run->data, 'module') ?: 'Not recorded' }}</td><td>{{ data_get($run->data, 'records') ?? 'Not recorded' }}</td><td>{{ $run->created_at?->format('d M Y, H:i') ?: 'Not recorded' }}</td></tr>@empty<tr><td colspan="4" class="reports-empty">No report runs recorded.</td></tr>@endforelse
            </tbody></table></section>
            <section class="reports-card"><div class="reports-card-head"><div><h2>Saved Schedules</h2><p>Persisted schedule configurations.</p></div><a href="{{ $url('scheduler') }}">Manage</a></div><table class="reports-table"><thead><tr><th>Name</th><th>Frequency</th><th>Time</th><th>Status</th></tr></thead><tbody>
                @forelse($schedules as $schedule)<tr><td><strong>{{ $schedule->title }}</strong></td><td>{{ data_get($schedule->data, 'frequency') ?: 'Not recorded' }}</td><td>{{ data_get($schedule->data, 'time') ?: 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($schedule->status) }}">{{ str($schedule->status)->headline() }}</span></td></tr>@empty<tr><td colspan="4" class="reports-empty">No report schedules recorded.</td></tr>@endforelse
            </tbody></table></section>
        </div>

        <div class="reports-three-grid reports-three-grid--lower">
            <section class="reports-card"><div class="reports-card-head"><div><h2>Order Summary</h2><p>Live order data for the selected period.</p></div><a href="{{ route('admin.reports.order', ['from'=>$filters['from']->format('Y-m-d'),'to'=>$filters['to']->format('Y-m-d')]) }}">Open</a></div><dl class="reports-summary-list"><div><dt>Total Orders</dt><dd>{{ number_format($summary['total']) }}</dd></div><div><dt>Paid Orders</dt><dd>{{ number_format($summary['approved']) }}</dd></div><div><dt>Paid Revenue</dt><dd>€{{ number_format($summary['revenue'], 2) }}</dd></div><div><dt>Saved Custom Reports</dt><dd>{{ number_format($summary['custom']) }}</dd></div></dl></section>
            <section class="reports-card"><div class="reports-card-head"><div><h2>Report Data Sources</h2><p>Sources recorded on saved custom reports.</p></div><a href="{{ $url('custom') }}">Add Source</a></div><div class="reports-legend reports-legend--stack">@forelse($sourceRows as $row)<span><i class="reports-dot reports-dot-{{ $loop->index % 2 ? 'blue' : 'green' }}"></i>{{ $row['label'] }} <b>{{ $row['value'] }} ({{ $row['share'] }}%)</b></span>@empty<div class="reports-empty">No custom report data sources recorded.</div>@endforelse</div></section>
            <section class="reports-card"><div class="reports-card-head"><div><h2>Favorites &amp; Alerts</h2><p>Persisted user choices and actual operational signals.</p></div></div><div class="reports-favorite-list">@forelse($favorites as $favorite)<div><span>☆</span><strong>{{ $favorite['title'] }}</strong><small>{{ $favorite['module'] }}</small></div>@empty<div class="reports-empty">No favorite reports recorded.</div>@endforelse</div><div class="reports-alert-list">@forelse($alerts as $alert)<div><i class="reports-alert-dot reports-alert-dot--{{ $alert['tone'] }}"></i><span>{{ $alert['label'] }}</span><small>{{ $alert['date'] }}</small></div>@empty<div class="reports-empty">No report alerts recorded.</div>@endforelse</div></section>
        </div>

    @elseif($section === 'approvals')
        <section class="reports-metric-grid">@foreach($cards as $card)<article class="reports-metric"><span class="reports-metric-icon reports-tone-{{ $metricTone($card['tone']) }}"><x-icon name="{{ $card['icon'] }}" size="18" /></span><div><small>{{ $card['label'] }}</small><strong>{{ $card['value'] }}</strong><em>Live</em></div></article>@endforeach</section>
        <div class="reports-three-grid">
            <section class="reports-card reports-chart-card"><h2>Approvals by Status</h2><div class="reports-donut reports-donut--approval"><strong>{{ number_format($approvalStats['total']) }}</strong><small>Total</small></div><div class="reports-legend reports-legend--stack">@forelse($statusRows as $row)<span><i class="reports-dot reports-dot-{{ $row['tone'] }}"></i>{{ $row['label'] }} <b>{{ number_format($row['value']) }} ({{ $row['percent'] }}%)</b></span>@empty<div class="reports-empty">No approval statuses recorded.</div>@endforelse</div></section>
            <section class="reports-card reports-wide-table"><div class="reports-card-head"><h2>Approvals by Request Type</h2></div><table class="reports-table"><thead><tr><th>Type</th><th>Requests</th><th>Approved</th><th>Pending</th><th>Rejected</th><th>Avg. TAT</th></tr></thead><tbody>@forelse($moduleRows as $row)<tr><td><strong>{{ $row['label'] }}</strong></td><td>{{ $row['requests'] }}</td><td>{{ $row['approved'] }}</td><td>{{ $row['pending'] }}</td><td>{{ $row['rejected'] }}</td><td>{{ $row['tat'] }}</td></tr>@empty<tr><td colspan="6" class="reports-empty">No approval requests recorded.</td></tr>@endforelse</tbody></table></section>
            <section class="reports-card"><h2>Approvals Over Time</h2><div class="reports-bars">@php($approvalMax = max(1, collect($approvalTrend)->max('value') ?: 1)) @foreach($approvalTrend as $point)<div><span>{{ $point['label'] }}</span><i><b style="width:{{ min(100, ($point['value'] / $approvalMax) * 100) }}%"></b></i><strong>{{ $point['value'] }}</strong></div>@endforeach</div></section>
        </div>
        <div class="reports-three-grid reports-three-grid--lower">
            <section class="reports-card"><h2>Turnaround &amp; SLA</h2><dl class="reports-summary-list"><div><dt>Overall Average</dt><dd>{{ $tatStats['overall'] }}</dd></div><div><dt>Fastest</dt><dd>{{ $tatStats['fastest'] }}</dd></div><div><dt>Slowest</dt><dd>{{ $tatStats['slowest'] }}</dd></div><div><dt>Within SLA</dt><dd>{{ $tatStats['within_sla'] }}</dd></div><div><dt>SLA Breaches</dt><dd>{{ number_format($tatStats['breaches']) }}</dd></div></dl></section>
            <section class="reports-card reports-wide-table"><div class="reports-card-head"><h2>Approvals by Approver</h2></div><table class="reports-table"><thead><tr><th>Approver</th><th>Requests</th><th>Approved</th><th>Pending</th><th>Rejected</th><th>Avg. TAT</th></tr></thead><tbody>@forelse($approvers as $row)<tr><td><strong>{{ $row['label'] }}</strong>@if($row['role'])<small>{{ $row['role'] }}</small>@endif</td><td>{{ $row['requests'] }}</td><td>{{ $row['approved'] }}</td><td>{{ $row['pending'] }}</td><td>{{ $row['rejected'] }}</td><td>{{ $row['tat'] }}</td></tr>@empty<tr><td colspan="6" class="reports-empty">No approver assignments recorded.</td></tr>@endforelse</tbody></table></section>
            <section class="reports-card"><div class="reports-card-head"><h2>Pending Approvals</h2></div><table class="reports-table"><thead><tr><th>Request</th><th>Module</th><th>Age</th><th>Priority</th></tr></thead><tbody>@forelse($pendingRows as $row)<tr><td><strong>{{ $row['request'] }}</strong><small>{{ $row['reference'] }}</small></td><td>{{ $row['module'] }}</td><td>{{ $row['age'] }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($row['priority']) }}">{{ $row['priority'] }}</span></td></tr>@empty<tr><td colspan="4" class="reports-empty">No pending approvals recorded.</td></tr>@endforelse</tbody></table></section>
        </div>
        <div class="reports-three-grid reports-three-grid--bottom">
            <section class="reports-card"><h2>Request Type Distribution</h2><div class="reports-legend reports-legend--stack">@forelse($requestTypes as $row)<span><i class="reports-dot reports-dot-{{ $loop->index % 2 ? 'blue' : 'green' }}"></i>{{ $row['label'] }} <b>{{ $row['value'] }} ({{ $row['percent'] }}%)</b></span>@empty<div class="reports-empty">No request types recorded.</div>@endforelse</div></section>
            <section class="reports-card"><h2>Recent Approval Activity</h2><table class="reports-table"><thead><tr><th>Request</th><th>Status</th><th>By</th><th>When</th></tr></thead><tbody>@forelse($activity as $row)<tr><td><strong>{{ $row['request'] }}</strong><small>{{ $row['reference'] }}</small></td><td><span class="reports-pill reports-pill--{{ $pillTone($row['status']) }}">{{ $row['status'] }}</span></td><td>{{ $row['by'] }}</td><td>{{ $row['time'] }}</td></tr>@empty<tr><td colspan="4" class="reports-empty">No approval activity recorded.</td></tr>@endforelse</tbody></table></section>
            <section class="reports-card"><h2>Approval Source</h2><p>Every value on this page is derived from the persisted approval request table and selected date window.</p></section>
        </div>

    @elseif($section === 'custom')
        <section class="reports-card reports-builder-form-wrap"><div class="reports-card-head"><div><h2>Build a Custom Report</h2><p>Save report definitions from real system fields. Execution results are recorded only after a run.</p></div></div><form id="report-builder" method="POST" action="{{ route('admin.reports.custom.store') }}" class="reports-builder-form">@csrf
            <div class="reports-builder-grid">
                <section class="reports-card"><h2>1. Report Details</h2><label class="reports-form-label">Report Name *<input required name="name" value="{{ old('name') }}"></label><label class="reports-form-label">Description<textarea name="description">{{ old('description') }}</textarea></label><label class="reports-form-label">Report Type<select name="report_type" required>@foreach($reportTypes as $type)<option value="{{ $type }}" @selected(old('report_type', $reportTypes[0] ?? '') === $type)>{{ $type }}</option>@endforeach</select></label></section>
                <section class="reports-card"><h2>2. Data Source</h2><label class="reports-form-label">Primary Module<select name="module" required>@foreach($modules as $module)<option value="{{ $module }}" @selected(old('module', $modules[0] ?? '') === $module)>{{ $module }}</option>@endforeach</select></label><label class="reports-form-label">Data Source<select name="data_source" required>@foreach(['Operational Database','Analytics Database','Communication Logs'] as $source)<option value="{{ $source }}" @selected(old('data_source', 'Operational Database') === $source)>{{ $source }}</option>@endforeach</select></label><div class="reports-check-grid">@foreach($modules as $module)<label><input type="checkbox" name="selected_modules[]" value="{{ $module }}" @checked(in_array($module, old('selected_modules', []), true))> {{ $module }}</label>@endforeach</div></section>
                <section class="reports-card"><h2>3. Fields &amp; Filters</h2><div class="reports-check-grid">@foreach($fields as $field)<label><input type="checkbox" name="fields[]" value="{{ $field }}" @checked(in_array($field, old('fields', []), true))> {{ $field }}</label>@endforeach</div><table class="reports-filter-table"><thead><tr><th>Field</th><th>Condition</th><th>Value</th><th>Logic</th></tr></thead><tbody>@foreach($filterFields as $index => $field)<tr><td><select name="filters[{{ $index }}][field]"><option value="{{ $field }}">{{ $field }}</option></select></td><td><select name="filters[{{ $index }}][condition]"><option value="equals">Equals</option><option value="greater_than">Greater Than</option><option value="in">In</option></select></td><td><input name="filters[{{ $index }}][value]" value="{{ old('filters.'.$index.'.value') }}" placeholder="Optional value"></td><td><select name="filters[{{ $index }}][logic]"><option value="and">AND</option><option value="or">OR</option></select></td></tr>@endforeach</tbody></table><button class="reports-btn reports-btn-soft" type="button" data-report-add-filter>＋ Add Filter</button></section>
                <section class="reports-card"><h2>4. Grouping &amp; Sorting</h2><label class="reports-form-label">Group By<select name="group_by"><option value="">No grouping</option>@foreach(['Order Type','Order Status','Payment Status','Order Date'] as $group)<option value="{{ $group }}">{{ $group }}</option>@endforeach</select></label><div class="reports-sort-row" data-report-sort-row>1 <select name="sorts[0][field]"><option value="Order Date">Order Date</option><option value="Order Value (EUR)">Order Value (EUR)</option><option value="Order Status">Order Status</option></select><select name="sorts[0][direction]"><option value="desc">Desc</option><option value="asc">Asc</option></select></div><button class="reports-btn reports-btn-soft" type="button" data-report-add-sort>＋ Add Sort</button></section>
                <section class="reports-card"><h2>5. Sharing &amp; Actions</h2><label class="reports-form-label">Share With<input name="share_with" value="{{ old('share_with') }}" placeholder="User, role or email"></label><label><input type="checkbox" name="favorite" value="1" @checked(old('favorite'))> Save as favorite</label><label><input type="checkbox" name="make_public" value="1" @checked(old('make_public'))> Make available to permitted users</label><label><input type="checkbox" name="schedule" value="1" @checked(old('schedule'))> Create an owner-recipient weekly schedule</label><label class="reports-form-label">Calculated Fields<div data-report-calculated-fields></div></label><button class="reports-btn reports-btn-soft" type="button" data-report-add-calculated>＋ Add Calculated Field</button></section>
                <section class="reports-card"><h2>6. Save &amp; Run</h2><p>There is no fabricated preview. Save the definition, then run it to record a live query result.</p><button class="reports-btn reports-btn-primary" type="submit">Save Report Definition</button></section>
            </div>
        </form></section>
        <div class="reports-three-grid reports-three-grid--lower"><section class="reports-card"><h2>Saved Reports</h2><table class="reports-table"><thead><tr><th>Name</th><th>Type</th><th>Module</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($customReports as $report)<tr><td><strong>{{ $report->title }}</strong><small>{{ $report->public_uuid }}</small></td><td>{{ data_get($report->data, 'report_type') ?: 'Not recorded' }}</td><td>{{ data_get($report->data, 'module') ?: 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($report->status) }}">{{ str($report->status)->headline() }}</span></td><td><form method="POST" action="{{ route('admin.reports.run') }}">@csrf<input type="hidden" name="report" value="{{ $report->title }}"><input type="hidden" name="module" value="{{ data_get($report->data, 'module') }}"><button class="reports-btn reports-btn-soft" type="submit">Run Live Query</button></form></td></tr>@empty<tr><td colspan="5" class="reports-empty">No saved custom reports recorded.</td></tr>@endforelse</tbody></table>{{ $customReports->links() }}</section><section class="reports-card"><h2>Saved Templates</h2>@forelse($templates as $template)<div class="reports-ranking-row"><strong>{{ $template['name'] }}</strong><span>{{ $template['type'] }}</span><small>{{ $template['uuid'] }}</small></div>@empty<div class="reports-empty">No saved report templates recorded.</div>@endforelse</section><section class="reports-card"><h2>Execution Boundary</h2><p>Report definitions are persisted and auditable. A run currently records the live row count for the selected module; file generation and delivery remain explicit scheduler concerns.</p></section></div>

    @elseif($section === 'history')
        <section class="reports-metric-grid">@foreach($cards as $card)<article class="reports-metric"><span class="reports-metric-icon reports-tone-{{ $metricTone($card['tone']) }}"><x-icon name="{{ $card['icon'] }}" size="18" /></span><div><small>{{ $card['label'] }}</small><strong>{{ $card['value'] }}</strong><em>Live</em></div></article>@endforeach</section>
        <form method="GET" action="{{ $url('history') }}" class="reports-history-filters"><input name="q" value="{{ request('q') }}" placeholder="Search by report name..." aria-label="Search by report name"><select name="module"><option value="all">All Modules</option>@foreach(($moduleOptions ?? []) as $module)<option value="{{ $module }}" @selected(request('module') === $module)>{{ $module }}</option>@endforeach</select><select name="status"><option value="all">All Statuses</option><option value="success" @selected(request('status') === 'success')>Success</option><option value="failed" @selected(request('status') === 'failed')>Failed</option><option value="in_progress" @selected(request('status') === 'in_progress')>In Progress</option></select><input type="date" name="from" value="{{ $filters['from']->format('Y-m-d') }}"><input type="date" name="to" value="{{ $filters['to']->format('Y-m-d') }}"><button class="reports-btn reports-btn-soft" type="submit">Apply Filters</button><a class="reports-btn reports-btn-soft" href="{{ $url('history') }}">Reset</a></form>
        <div class="reports-history-grid"><section class="reports-card reports-wide-table"><div class="reports-card-head"><h2>Report Runs <span class="reports-result-count">{{ number_format($history->total()) }} Results</span></h2></div><table class="reports-table"><thead><tr><th>Run Date &amp; Time</th><th>Report Name</th><th>Module</th><th>Run By</th><th>Format</th><th>Status</th><th>Duration</th><th>Delivery</th><th>Actions</th></tr></thead><tbody>@forelse($history as $run)<tr><td>{{ $run->created_at?->format('d M Y, H:i') ?: 'Not recorded' }}</td><td><strong>{{ $run->title }}</strong></td><td>{{ data_get($run->data, 'module') ?: 'Not recorded' }}</td><td>{{ $run->user?->name ?: ($run->user_id ? 'User #'.$run->user_id : 'System') }}</td><td>{{ data_get($run->data, 'format') ?: 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($run->status) }}">{{ str($run->status)->headline() }}</span></td><td>{{ data_get($run->data, 'duration') ?: 'Not recorded' }}</td><td>{{ data_get($run->data, 'delivery') ?: 'Not recorded' }}</td><td class="reports-row-actions"><a class="reports-icon-action" href="{{ $url('export', ['name'=>str($run->title)->slug()]) }}" aria-label="Export report">⇩</a><form method="POST" action="{{ route('admin.reports.run') }}">@csrf<input type="hidden" name="report" value="{{ $run->title }}"><input type="hidden" name="module" value="{{ data_get($run->data, 'module') }}"><button class="reports-icon-action" type="submit" aria-label="Run report again">◉</button></form><a class="reports-icon-action" href="{{ $url('history', ['selected'=>$run->id]) }}" aria-label="View report run details">⋮</a></td></tr>@empty<tr><td colspan="9" class="reports-empty">No report runs match the selected filters.</td></tr>@endforelse</tbody></table>{{ $history->links() }}</section>
            <aside class="reports-card reports-run-detail">@if($selectedRun)<span class="reports-pill reports-pill--{{ $pillTone($selectedRun->status) }}">{{ str($selectedRun->status)->headline() }}</span><h2>{{ $selectedRun->title }}</h2><dl><dt>Run ID</dt><dd>{{ $selectedRun->public_uuid }}</dd><dt>Run Date &amp; Time</dt><dd>{{ $selectedRun->created_at?->format('d M Y, H:i') ?: 'Not recorded' }}</dd><dt>Module</dt><dd>{{ data_get($selectedRun->data, 'module') ?: 'Not recorded' }}</dd><dt>Run By</dt><dd>{{ $selectedRun->user?->name ?: ($selectedRun->user_id ? 'User #'.$selectedRun->user_id : 'System') }}</dd><dt>Records</dt><dd>{{ data_get($selectedRun->data, 'records') ?? 'Not recorded' }}</dd><dt>Format</dt><dd>{{ data_get($selectedRun->data, 'format') ?: 'Not recorded' }}</dd><dt>Delivery</dt><dd>{{ data_get($selectedRun->data, 'delivery') ?: 'Not recorded' }}</dd></dl><div class="reports-detail-actions"><a class="reports-btn reports-btn-primary" href="{{ $url('export', ['name'=>str($selectedRun->title)->slug()]) }}">Export</a><form method="POST" action="{{ route('admin.reports.run') }}">@csrf<input type="hidden" name="report" value="{{ $selectedRun->title }}"><input type="hidden" name="module" value="{{ data_get($selectedRun->data, 'module') }}"><button class="reports-btn reports-btn-soft" type="submit">Run Again</button></form></div>@else<div class="reports-empty">Select a persisted run to inspect details.</div>@endif</aside>
        </div>
        <div class="reports-three-grid reports-three-grid--bottom"><section class="reports-card"><h2>Status Breakdown</h2>@forelse($statusBreakdown as $row)<div class="reports-breakdown-row"><i class="reports-dot reports-dot-{{ $row['tone'] }}"></i>{{ $row['label'] }}<b>{{ $row['value'] }} ({{ $row['percent'] }}%)</b></div>@empty<div class="reports-empty">No status data recorded.</div>@endforelse</section><section class="reports-card"><h2>Top Reports by Runs</h2>@forelse($topReports as $row)<div class="reports-ranking-row"><strong>{{ $row['title'] }}</strong><b>{{ $row['count'] }}</b></div>@empty<div class="reports-empty">No report ranking data recorded.</div>@endforelse</section><section class="reports-card"><h2>History Actions</h2><div class="reports-quick-actions"><a href="{{ $url('custom') }}">＋ Run New Report</a><a href="{{ $url('scheduler') }}">▣ Schedule Report</a><a href="{{ $url('export', ['name'=>'report-history']) }}">⇩ Export History</a><form method="POST" action="{{ route('admin.reports.history.prune') }}" class="reports-inline-form" onsubmit="return confirm('Archive report runs older than 90 days?')">@csrf<button class="reports-btn reports-btn-danger" type="submit">Archive Old History</button></form></div></section></div>

    @elseif($section === 'returns')
        <section class="reports-metric-grid">@foreach($cards as $card)<article class="reports-metric"><span class="reports-metric-icon reports-tone-{{ $metricTone($card['tone']) }}"><x-icon name="{{ $card['icon'] }}" size="18" /></span><div><small>{{ $card['label'] }}</small><strong>{{ $card['value'] }}</strong><em>Live</em></div></article>@endforeach</section>
        <div class="reports-three-grid"><section class="reports-card"><h2>Returns Trend</h2><div class="reports-bars">@php($returnMax = max(1, collect($returnTrend)->max('value') ?: 1)) @foreach($returnTrend as $point)<div><span>{{ $point['label'] }}</span><i><b style="height:{{ min(100, ($point['value'] / $returnMax) * 100) }}%"></b></i><strong>{{ $point['value'] }}</strong></div>@endforeach</div></section><section class="reports-card reports-chart-card"><h2>Returns by Status</h2><div class="reports-donut reports-donut--return"><strong>{{ $returnMetrics[0]['value'] }}</strong><small>Total</small></div><div class="reports-legend reports-legend--stack">@forelse($returnStatus as $row)<span><i class="reports-dot reports-dot-{{ $row['tone'] }}"></i>{{ $row['label'] }} <b>{{ $row['value'] }} ({{ $row['percent'] }})</b></span>@empty<div class="reports-empty">No return statuses recorded.</div>@endforelse</div></section><section class="reports-card"><h2>Returns by Reason</h2><div class="reports-bars">@forelse($reasonRows as $row)<div><span>{{ $row['label'] }}</span><i><b style="width:{{ $row['bar_percent'] }}%"></b></i><strong>{{ $row['value'] }} ({{ $row['percent'] }}%)</strong></div>@empty<div class="reports-empty">No return reasons recorded.</div>@endforelse</div></section></div>
        <div class="reports-three-grid reports-three-grid--lower"><section class="reports-card reports-wide-table"><div class="reports-card-head"><h2>Returns by Order Type</h2></div><table class="reports-table"><thead><tr><th>Type</th><th>Returns</th><th>Return Rate</th><th>Refunds</th><th>Avg. Process Time</th></tr></thead><tbody>@forelse($moduleRows as $row)<tr><td><strong>{{ $row['label'] }}</strong></td><td>{{ $row['returns'] }}</td><td>{{ $row['rate'] }}</td><td>{{ $row['refunds'] }}</td><td>{{ $row['time'] }}</td></tr>@empty<tr><td colspan="5" class="reports-empty">No return records linked to order types.</td></tr>@endforelse</tbody></table></section><section class="reports-card"><h2>Associated Products</h2><p>Refund values are allocated from linked order totals because this schema has no item-level refund amount.</p><table class="reports-table"><thead><tr><th>Product</th><th>Returns</th><th>Refunds</th></tr></thead><tbody>@forelse($productRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['returns'] }}</td><td>{{ $row['refunds'] }}</td></tr>@empty<tr><td colspan="3" class="reports-empty">No return-to-item links recorded.</td></tr>@endforelse</tbody></table></section><section class="reports-card"><h2>Refunds by Payment Method</h2><table class="reports-table"><thead><tr><th>Method</th><th>Refunds</th><th>Share</th></tr></thead><tbody>@forelse($paymentRows as $row)<tr><td>{{ $row['label'] }}</td><td>{{ $row['value'] }}</td><td>{{ $row['percent'] }}</td></tr>@empty<tr><td colspan="3" class="reports-empty">No linked refund payment data recorded.</td></tr>@endforelse</tbody></table></section></div>
        <div class="reports-three-grid reports-three-grid--bottom"><section class="reports-card"><h2>Refunds Over Time</h2><div class="reports-bars">@php($refundMax = max(1, (float) (collect($refundTrend)->max('value') ?: 1))) @foreach($refundTrend as $point)<div><span>{{ $point['label'] }}</span><i><b style="height:{{ min(100, ($point['value'] / $refundMax) * 100) }}%"></b></i><strong>€{{ number_format($point['value'], 2) }}</strong></div>@endforeach</div></section><section class="reports-card reports-wide-table"><h2>Recent Returns</h2><table class="reports-table"><thead><tr><th>Return ID</th><th>Date</th><th>Status</th><th>Linked Order</th></tr></thead><tbody>@forelse($recentReturns as $return)<tr><td><strong>{{ $return->number }}</strong></td><td>{{ $return->created_at?->format('d M Y') ?: 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($return->status) }}">{{ str($return->status)->headline() }}</span></td><td>{{ $return->order?->number ?: 'Not recorded' }}</td></tr>@empty<tr><td colspan="4" class="reports-empty">No return requests recorded.</td></tr>@endforelse</tbody></table></section><section class="reports-card"><h2>Return Data Boundary</h2><p>Return and refund values come from recorded return requests and their linked orders. Missing item-level values remain unreported.</p></section></div>

    @elseif($section === 'roles')
        <section class="reports-metric-grid">@foreach($cards as $card)<article class="reports-metric"><span class="reports-metric-icon reports-tone-{{ $metricTone($card['tone']) }}"><x-icon name="{{ $card['icon'] }}" size="18" /></span><div><small>{{ $card['label'] }}</small><strong>{{ $card['value'] }}</strong><em>Live</em></div></article>@endforeach</section>
        <nav class="reports-tabs"><a class="active" href="{{ route('admin.user-system.roles') }}">Roles</a><a href="{{ route('admin.user-system.matrix') }}">Permissions</a><a href="{{ route('admin.user-system.users') }}">Users</a><a href="{{ route('admin.user-system.roles-permissions') }}">Access Control</a></nav>
        <div class="reports-roles-grid"><section class="reports-card reports-wide-table"><div class="reports-card-head"><div><h2>Roles ({{ number_format($roles->total()) }})</h2><p>Persisted roles and their current assignments.</p></div><form method="GET" action="{{ $url('roles') }}" class="reports-inline-filter"><input name="q" value="{{ request('q') }}" placeholder="Search roles..." aria-label="Search roles"><button class="reports-icon-action" type="submit" aria-label="Search roles">⌕</button></form></div><table class="reports-table"><thead><tr><th>Role Name</th><th>Description</th><th>Users</th><th>Level</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($roles as $role)<tr><td><strong>{{ $role->name }}</strong><small>{{ $role->uuid }}</small></td><td>{{ $role->description ?: 'Not recorded' }}</td><td>{{ number_format($role->users_count) }}</td><td>{{ $role->level ?? 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($role->is_active ? 'active' : 'inactive') }}">{{ $role->is_active ? 'Active' : 'Inactive' }}</span></td><td class="reports-row-actions"><a href="{{ route('admin.user-system.roles', ['selected'=>$role->id]) }}">Edit</a><form method="POST" action="{{ route('admin.user-system.roles.clone', $role->id) }}">@csrf<button type="submit">Clone</button></form><form method="POST" action="{{ route('admin.user-system.roles.toggle', $role->id) }}">@csrf<button type="submit">Toggle</button></form></td></tr>@empty<tr><td colspan="6" class="reports-empty">No roles match the selected filters.</td></tr>@endforelse</tbody></table>{{ $roles->links() }}</section>
            <section class="reports-card reports-role-detail"><h2>Role Details &amp; Permissions</h2>@if($selectedRole && $roleSummary)<form method="GET" action="{{ $url('roles') }}" class="reports-role-select"><select name="selected" aria-label="Select role" onchange="this.form.submit()">@foreach($roles as $role)<option value="{{ $role->id }}" @selected((int) request('selected') === (int) $role->id || (!request('selected') && $role->id === $selectedRole->id))>{{ $role->name }}</option>@endforeach</select></form><h3>Module Access ({{ count($permissionRows) }}) · Permissions ({{ $roleSummary['permissions'] }}) · Users ({{ $roleSummary['users'] }})</h3><table class="reports-table"><thead><tr><th>Module</th><th>View</th><th>Create</th><th>Edit</th><th>Delete</th><th>Export</th><th>Access</th></tr></thead><tbody>@forelse($permissionRows as $row)<tr><td>{{ $row['label'] }}</td><td>{{ $row['view'] }}</td><td>{{ $row['create'] }}</td><td>{{ $row['edit'] }}</td><td>{{ $row['delete'] }}</td><td>{{ $row['export'] }}</td><td>{{ $row['access'] }}</td></tr>@empty<tr><td colspan="7" class="reports-empty">No permissions are assigned to this role.</td></tr>@endforelse</tbody></table>@else<div class="reports-empty">No role is available for inspection.</div>@endif</section>
            <aside class="reports-card"><h2>Role Summary</h2>@if($roleSummary)<dl><dt>Role Name</dt><dd>{{ $roleSummary['name'] }}</dd><dt>Level</dt><dd>{{ $roleSummary['level'] }}</dd><dt>Users</dt><dd>{{ $roleSummary['users'] }}</dd><dt>Status</dt><dd>{{ $roleSummary['status'] }}</dd><dt>Created By</dt><dd>{{ $roleSummary['created_by'] }}</dd><dt>Last Updated</dt><dd>{{ $roleSummary['last_updated'] ?: 'Not recorded' }}</dd><dt>Description</dt><dd>{{ $roleSummary['description'] }}</dd></dl><div class="reports-quick-actions"><a href="{{ route('admin.user-system.roles', ['selected'=>$selectedRoleId]) }}">Edit Role</a><a href="{{ route('admin.user-system.roles.export') }}">Permission Report</a><form method="POST" action="{{ route('admin.user-system.roles.toggle', $selectedRoleId) }}" class="reports-inline-form">@csrf<button class="reports-action-link danger" type="submit">Toggle Role</button></form></div>@else<div class="reports-empty">No role summary is available.</div>@endif</aside></div>
        <div class="reports-three-grid reports-three-grid--bottom"><section class="reports-card"><h2>Permission Overview</h2><div class="reports-donut reports-donut--permission"><strong>{{ number_format($permissionOverview) }}</strong><small>Assigned Permissions</small></div></section><section class="reports-card"><h2>Users by Role</h2>@forelse($userByRole as $row)<div class="reports-progress-row"><span>{{ $row['label'] }}</span><i><b style="width:{{ min(100, $row['value']) }}%"></b></i><strong>{{ $row['value'] }}</strong></div>@empty<div class="reports-empty">No role assignments recorded.</div>@endforelse</section><section class="reports-card"><h2>Recent Role Changes</h2><table class="reports-table"><thead><tr><th>Date &amp; Time</th><th>Role</th><th>Changed By</th><th>Change Type</th></tr></thead><tbody>@forelse($roleChanges as $row)<tr><td>{{ $row['date'] ?: 'Not recorded' }}</td><td>{{ $row['role'] }}</td><td>{{ $row['by'] }}</td><td>{{ $row['type'] }}</td></tr>@empty<tr><td colspan="4" class="reports-empty">No audited changes recorded for this role.</td></tr>@endforelse</tbody></table></section></div>

    @elseif($section === 'scheduler')
        @php($form = $formDefaults)
        <section class="reports-schedule-summary">@if($scheduleSummary)<article><x-icon name="file-text" size="20" /><span><small>Report</small><strong>{{ $scheduleSummary['report'] }}</strong><small>{{ $scheduleSummary['status'] }}</small></span></article><article><x-icon name="clock" size="20" /><span><small>Next Run</small><strong>{{ $scheduleSummary['next_run'] }}</strong><small>{{ $scheduleSummary['frequency'] }}</small></span></article><article><x-icon name="calendar" size="20" /><span><small>Start Date</small><strong>{{ $scheduleSummary['start_date'] }}</strong><small>{{ $scheduleSummary['day'] }}</small></span></article><article><x-icon name="users" size="20" /><span><small>Recipients</small><strong>{{ $scheduleSummary['recipients'] }}</strong></span></article><article><x-icon name="file-text" size="20" /><span><small>Format</small><strong>{{ $scheduleSummary['format'] }}</strong><small>{{ $scheduleSummary['orientation'] }}</small></span></article><article><x-icon name="check" size="20" /><span><small>Status</small><strong>{{ $scheduleSummary['status'] }}</strong></span></article>@else<div class="reports-empty">No schedule is selected.</div>@endif</section>
        <form id="schedule-form" method="POST" action="{{ route('admin.reports.schedules.store') }}" class="reports-scheduler-form">@csrf<div class="reports-scheduler-grid">
            <section class="reports-card"><h2>1. Schedule Details</h2><label class="reports-form-label">Schedule Name *<input name="name" required value="{{ old('name', $form['name']) }}"></label><label class="reports-form-label">Description<textarea name="description">{{ old('description', $form['description']) }}</textarea></label><label>Active <input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked(old('active', $form['active']))></label><div class="reports-two-fields"><label>Start Date<input type="date" name="start_date" value="{{ old('start_date', $form['start_date']) }}"></label><label>End Date<input type="date" name="end_date" value="{{ old('end_date', $form['end_date']) }}"></label></div><label class="reports-form-label">Time<input type="time" name="time" value="{{ old('time', $form['time']) }}" required></label><label class="reports-form-label">Time Zone<input name="timezone" value="{{ old('timezone', $form['timezone']) }}"></label></section>
            <section class="reports-card"><h2>2. Report &amp; Format</h2><label class="reports-form-label">Report *<select name="report" required>@foreach($reportOptions as $option)<option value="{{ $option }}" @selected(old('report', $form['report']) === $option)>{{ $option }}</option>@endforeach</select></label><label class="reports-form-label">Output Format *<select name="format" required>@foreach(['PDF','Excel','CSV'] as $format)<option value="{{ $format }}" @selected(old('format', $form['format']) === $format)>{{ $format }}</option>@endforeach</select></label><label class="reports-form-label">Orientation<select name="orientation"><option value="landscape" @selected(old('orientation', $form['orientation']) === 'landscape')>Landscape</option><option value="portrait" @selected(old('orientation', $form['orientation']) === 'portrait')>Portrait</option></select></label><label>Include Charts <input type="checkbox" name="include_charts" value="1" @checked(old('include_charts'))></label><label>Password Protect <input type="checkbox" name="password_protect" value="1" @checked(old('password_protect'))></label></section>
            <section class="reports-card"><h2>3. Frequency</h2>@foreach(['One Time','Daily','Weekly','Monthly','Quarterly','Yearly'] as $frequency)<label class="reports-radio-row"><input type="radio" name="frequency" value="{{ $frequency }}" @checked(old('frequency', $form['frequency']) === $frequency)> {{ $frequency }}</label>@endforeach<h3>Repeat On</h3>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'] as $day)<label><input type="checkbox" name="day[]" value="{{ $day }}" @checked(in_array($day, old('day', $form['day']), true))> {{ str($day)->substr(0,3) }}</label>@endforeach</section>
            <section class="reports-card"><h2>4. Delivery Recipients</h2><div class="reports-tabs" data-report-recipient-tabs><a class="active" href="#recipient-users" data-report-recipient-tab="users" aria-selected="true">Email Recipients</a></div><input name="recipients" value="{{ old('recipients', $form['recipients']) }}" data-report-recipient-input aria-label="Report recipients" placeholder="name@example.com"><div class="reports-recipient-list">@foreach($recipients as $recipient)<span><i>{{ str($recipient)->substr(0,2)->upper() }}</i>{{ $recipient }}</span>@endforeach</div><button class="reports-card-link reports-card-link-button" type="button" data-report-add-recipient>＋ Add Recipient</button><div data-report-recipient-extra></div></section>
            <section class="reports-card"><h2>5. Delivery Method</h2>@foreach(['email'=>'Email','in_app'=>'In-App Notification','download'=>'Download Link','attachment'=>'Attach Report','library'=>'Save to Report Library'] as $value => $label)<label><input type="checkbox" name="delivery_methods[]" value="{{ $value }}" @checked(old('delivery_methods', []) && in_array($value, old('delivery_methods', []), true))> {{ $label }}</label>@endforeach</section>
            <section class="reports-card"><h2>6. Email Settings</h2><label class="reports-form-label">Email Subject<input name="email_subject" value="{{ old('email_subject', $form['email_subject']) }}"></label><label class="reports-form-label">Email Message<textarea name="email_message">{{ old('email_message', $form['email_message']) }}</textarea></label><label class="reports-form-label">Reply To<input name="reply_to" value="{{ old('reply_to', $form['reply_to']) }}"></label></section>
            <section class="reports-card"><h2>7. Advanced Options</h2><label>Run As<select name="run_as"><option value="system">System</option><option value="owner">Schedule Owner</option></select></label><label>Data Refresh<select name="data_refresh"><option value="delivery">At Time of Delivery</option><option value="cached">Use Cached Data</option></select></label><label>Include Drill-down <input type="checkbox" name="include_drilldown" value="1" @checked(old('include_drilldown'))></label><label>Max Records<input type="number" name="max_records" value="{{ old('max_records', $form['max_records']) }}" min="1" max="100000"></label><button class="reports-btn reports-btn-primary" type="submit">Save Schedule</button></section>
            <aside class="reports-card reports-schedule-summary-card"><h2>8. Schedule Summary</h2>@if($scheduleSummary)<dl><dt>Report</dt><dd>{{ $scheduleSummary['report'] }}</dd><dt>Frequency</dt><dd>{{ $scheduleSummary['frequency'] }}</dd><dt>Start Date</dt><dd>{{ $scheduleSummary['start_date'] }}</dd><dt>Time</dt><dd>{{ $scheduleSummary['time'] }}</dd><dt>Recipients</dt><dd>{{ $scheduleSummary['recipients'] }}</dd><dt>Format</dt><dd>{{ $scheduleSummary['format'] }}</dd><dt>Status</dt><dd>{{ $scheduleSummary['status'] }}</dd></dl>@else<div class="reports-empty">Save a schedule to populate this summary.</div>@endif</aside>
        </div></form>
        <div class="reports-three-grid reports-three-grid--bottom"><section class="reports-card"><h2>Saved Schedules</h2><table class="reports-table"><thead><tr><th>Name</th><th>Report</th><th>Frequency</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($schedules as $schedule)<tr><td><strong>{{ $schedule->title }}</strong><small>{{ $schedule->public_uuid }}</small></td><td>{{ data_get($schedule->data, 'report') ?: 'Not recorded' }}</td><td>{{ data_get($schedule->data, 'frequency') ?: 'Not recorded' }}</td><td><span class="reports-pill reports-pill--{{ $pillTone($schedule->status) }}">{{ str($schedule->status)->headline() }}</span></td><td><form method="POST" action="{{ route('admin.reports.schedules.toggle', $schedule) }}" class="reports-inline-form">@csrf<button class="reports-action-link" type="submit">Toggle</button></form><form method="POST" action="{{ route('admin.reports.schedules.duplicate', $schedule) }}" class="reports-inline-form">@csrf<button class="reports-action-link" type="submit">Duplicate</button></form><form method="POST" action="{{ route('admin.reports.schedules.delete', $schedule) }}" class="reports-inline-form" onsubmit="return confirm('Archive this report schedule?')">@csrf<button class="reports-action-link danger" type="submit">Archive</button></form></td></tr>@empty<tr><td colspan="5" class="reports-empty">No report schedules recorded.</td></tr>@endforelse</tbody></table>{{ $schedules->links() }}</section><section class="reports-card"><h2>Delivery History</h2><div class="reports-schedule-list">@forelse($deliveryHistory as $row)<div class="reports-schedule-row"><strong>{{ $row['date'] ?: 'Not recorded' }}</strong><span>{{ $row['recipients'] }}</span><b>{{ $row['format'] }}</b><em>{{ $row['status'] }}</em></div>@empty<div class="reports-empty">No report delivery runs recorded.</div>@endforelse</div></section><section class="reports-card"><h2>Scheduler Boundary</h2><p>Schedules are persisted with recipient validation and audited state changes. The existing deployment workflow remains unchanged.</p></section></div>
    @endif
</div>
<script src="/js/reports-reference.js?v=20260913-b20-1" defer></script>
@endsection
