<?php
namespace Tests\Feature;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\User;
use App\Models\VariantMedia;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
class VariantManagementTest extends TestCase
{
use RefreshDatabase;
private function admin():User{return User::factory()->create(['is_admin'=>true]);}
private function product(array $overrides=[]):Product{return Product::create(array_merge(['name'=>'Emerald Signature Cap','slug'=>'emerald-signature-cap','sku'=>'ER-CAP-001','description'=>'Premium cap used by variant tests.','price'=>29.99,'compare_price'=>39.99,'stock'=>100,'is_active'=>true,'status'=>'active'],$overrides));}
public function test_admin_can_open_real_variant_dashboard():void{$admin=$this->admin();$product=$this->product();ProductVariant::create(['product_id'=>$product->id,'sku'=>'ER-CAP-001-GRN-OS','colour'=>'Emerald Green','size'=>'One Size','material'=>'Cotton','price'=>29.99,'stock'=>8,'stock_total'=>10,'status'=>'active','is_active'=>true]);$this->actingAs($admin)->get(route('admin.variants.index'))->assertOk()->assertSee(['Variants','ER-CAP-001-GRN-OS','Variant Summary','UUID Traceability']);}
public function test_admin_can_create_variant_with_uuid_and_opening_stock_movement():void{$admin=$this->admin();$product=$this->product();$this->actingAs($admin)->post(route('admin.variants.store'),['product_id'=>$product->id,'sku'=>'','barcode'=>'8906123456781','colour'=>'Emerald Green','size'=>'One Size','material'=>'Cotton','style'=>'Classic','price'=>29.99,'compare_price'=>39.99,'stock'=>12,'stock_total'=>20,'status'=>'active','low_stock_threshold'=>10,'track_inventory'=>1,'backorder'=>0])->assertRedirect();$variant=ProductVariant::firstOrFail();$this->assertNotEmpty($variant->public_uuid);$this->assertStringStartsWith('ER-CAP-001-',$variant->sku);$this->assertDatabaseHas('inventory_movements',['product_variant_id'=>$variant->id,'quantity'=>12,'type'=>'opening_balance']);}
public function test_stock_update_creates_inventory_adjustment():void{$admin=$this->admin();$product=$this->product();$variant=ProductVariant::create(['product_id'=>$product->id,'sku'=>'ER-CAP-001-BLK-L','stock'=>5,'stock_total'=>10,'status'=>'active','is_active'=>true]);$this->actingAs($admin)->patch(route('admin.variants.update',$variant),['product_id'=>$product->id,'sku'=>$variant->sku,'colour'=>'Black','size'=>'Large','material'=>'Cotton','price'=>29.99,'compare_price'=>39.99,'stock'=>11,'stock_total'=>15,'status'=>'active','low_stock_threshold'=>10,'track_inventory'=>1,'backorder'=>0])->assertRedirect();$this->assertDatabaseHas('inventory_movements',['product_variant_id'=>$variant->id,'quantity'=>6,'type'=>'adjustment']);}
public function test_bulk_create_generates_option_combinations():void{$admin=$this->admin();$product=$this->product();$this->actingAs($admin)->post(route('admin.variants.bulk-create'),['product_id'=>$product->id,'colours'=>'Emerald Green,Black','sizes'=>'One Size,Large','materials'=>'Cotton','styles'=>'','price'=>29.99,'stock'=>2,'stock_total'=>4])->assertRedirect();$this->assertSame(4,ProductVariant::count());}
public function test_bulk_stock_update_and_csv_reports_work():void{$admin=$this->admin();$product=$this->product();$variant=ProductVariant::create(['product_id'=>$product->id,'sku'=>'ER-CAP-001-WHT-OS','stock'=>1,'stock_total'=>5,'status'=>'active','is_active'=>true]);$this->actingAs($admin)->post(route('admin.variants.bulk'),['variants'=>[$variant->public_uuid],'action'=>'set_stock','stock'=>9,'stock_total'=>12])->assertRedirect();$this->assertSame(9,$variant->fresh()->stock);$this->actingAs($admin)->get(route('admin.variants.export',['report'=>'stock']))->assertOk()->assertHeader('content-type','text/csv; charset=UTF-8');}
public function test_variant_media_upload_is_linked_to_selected_variant():void{Storage::fake('public');$admin=$this->admin();$product=$this->product();$variant=ProductVariant::create(['product_id'=>$product->id,'sku'=>'ER-CAP-001-MEDIA','stock'=>1,'status'=>'active','is_active'=>true]);$png=base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=');$file=UploadedFile::fake()->createWithContent('variant.png',$png);$this->actingAs($admin)->post(route('admin.variants.media.store',$variant),['type'=>'image','file'=>$file,'alt_text'=>'Emerald cap variant'])->assertRedirect();$media=VariantMedia::firstOrFail();$this->assertSame($variant->id,$media->product_variant_id);Storage::disk('public')->assertExists($media->path);}
public function test_storefront_keeps_using_active_variants_only():void{$product=$this->product();ProductVariant::create(['product_id'=>$product->id,'sku'=>'ACTIVE-VARIANT','colour'=>'Emerald Green','stock'=>10,'status'=>'active','is_active'=>true]);ProductVariant::create(['product_id'=>$product->id,'sku'=>'DISABLED-VARIANT','colour'=>'Forbidden Orange','stock'=>10,'status'=>'inactive','is_active'=>false]);$this->get(route('product',$product))->assertOk()->assertSee('Emerald Green')->assertDontSee('Forbidden Orange');}
}
