<div class="us-title-actions us-page-actions"><a class="us-btn" href="{{ route('admin.user-system.activity.export') }}">Export Log</a><a class="us-btn us-btn-primary" href="{{ route('admin.user-system.activity') }}">Refresh</a></div>
<form class="us-filterbar" method="get"><label><span>Search Activities</span><input name="q" value="{{ request('q') }}" placeholder="Search by user, action, module, IP..."></label><label><span>Activity Type</span><select name="activity_type"><option value="">All Types</option><option value="users">Users</option><option value="roles">Roles</option><option value="permissions">Permissions</option><option value="authentication">Authentication</option></select></label><label><span>User</span><select name="user"><option value="">All Users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user')===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></label><label><span>From</span><input type="date" name="from" value="{{ request('from') }}"></label><label><span>To</span><input type="date" name="to" value="{{ request('to') }}"></label><button class="us-btn">Filters</button><a class="us-btn" href="{{ route('admin.user-system.activity') }}">Reset</a></form>
<div class="us-main-grid"><section class="us-panel us-table-panel"><div class="us-panel-title"><h2>Activity Log <span>({{ $logs->total() }} Results)</span></h2></div><div class="us-table-wrap"><table class="us-table"><thead><tr><th>Date &amp; Time</th><th>User</th><th>Action</th><th>Module</th><th>Details</th><th>IP Address</th><th>Severity</th></tr></thead><tbody>
@forelse($logs as $log)
@php $u=$logUsers->get($log->user_id); $severity=app(\App\Http\Controllers\Admin\UserSystemController::class)->severityForAction($log->action); $actionLabel=\Illuminate\Support\Str::headline(str_replace('.', ' ', $log->action)); @endphp
<tr class="{{ $selectedLog?->id===$log->id?'selected':'' }}"><td><a href="{{ route('admin.user-system.activity',['selected'=>$log->id]) }}">{{ optional($log->created_at)->format('d M Y, H:i') }}</a></td><td>{{ $u?->name ?? 'System' }}</td><td><b>{{ $actionLabel }}</b></td><td>{{ \Illuminate\Support\Str::headline(\Illuminate\Support\Str::before($log->action,'.')) }}</td><td>{{ \Illuminate\Support\Str::limit(json_encode($log->after),60) }}</td><td>{{ $log->ip_address ?: '—' }}</td><td><span class="us-pill {{ $severity==='high'?'danger':($severity==='medium'?'warning':'success') }}">{{ ucfirst($severity) }}</span></td></tr>
@empty<tr><td colspan="7" class="us-empty">No security activity recorded yet.</td></tr>@endforelse
</tbody></table></div><div class="us-pagination"><span>Showing {{ $logs->firstItem()??0 }} to {{ $logs->lastItem()??0 }} of {{ $logs->total() }} entries</span>{{ $logs->links() }}</div></section>
<aside class="us-panel us-detail"><h2>Activity Details</h2>@if($selectedLog)<div class="us-role-hero"><span class="us-role-crown">↻</span><div><h3>{{ \Illuminate\Support\Str::headline(str_replace('.', ' ', $selectedLog->action)) }}</h3></div></div><dl class="us-kv"><dt>Date &amp; Time</dt><dd>{{ optional($selectedLog->created_at)->format('d M Y, H:i:s') }}</dd><dt>User</dt><dd>{{ $logUsers->get($selectedLog->user_id)?->name ?? 'System / Unknown' }}</dd><dt>Module</dt><dd>{{ \Illuminate\Support\Str::headline(\Illuminate\Support\Str::before($selectedLog->action,'.')) }}</dd><dt>IP Address</dt><dd>{{ $selectedLog->ip_address ?: '—' }}</dd><dt>Details</dt><dd><code>{{ json_encode($selectedLog->after) }}</code></dd></dl>@endif</aside></div>
<div class="us-bottom-grid four"><section class="us-panel"><h3>Activities by Type</h3><div class="us-donut"><b>{{ number_format($logs->total()) }}</b><span>Total Activities</span></div></section><section class="us-panel"><h3>Activities Over Time</h3>@include('admin.user-system.partials.spark',['items'=>$activityAnalytics['days']])</section><section class="us-panel"><h3>Top Users by Activity</h3>@include('admin.user-system.partials.bars',['items'=>$activityAnalytics['users']])</section><section class="us-panel"><h3>Quick Actions</h3><div class="us-action-list"><a href="{{ route('admin.user-system.activity.export') }}">⇩ <span>Export This Activity</span></a><a href="{{ route('admin.user-system.users') }}">♙ <span>View User Profiles</span></a><a href="{{ route('admin.user-system.matrix') }}">▦ <span>Permission Audit</span></a></div></section></div>