<div class="us-title-actions us-page-actions"><a class="us-btn" href="{{ route('admin.user-system.matrix.export') }}">Export Matrix</a><button class="us-btn" type="button" data-us-open="import-matrix">Import Matrix</button><a class="us-btn" href="{{ route('admin.user-system.roles-permissions') }}">Compare Roles</a><a class="us-btn us-btn-primary" href="{{ route('admin.user-system.matrix') }}">Refresh</a></div>
<form class="us-matrix-filter" method="get"><label><span>Role</span><select name="role"><option value="">All Roles</option>@foreach($allRoles as $role)<option value="{{ $role->id }}" @selected((string)request('role')===(string)$role->id)>{{ $role->label }}</option>@endforeach</select></label><label><span>Module</span><select name="module"><option value="">All Modules</option>@foreach($modules as $module)<option value="{{ $module }}" @selected(request('module')===$module)>{{ $module }}</option>@endforeach</select></label><label><span>Permission</span><select name="permission"><option value="">All Permissions</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('permission')===$action)>{{ ucfirst($action) }}</option>@endforeach</select></label><button class="us-btn">Apply</button><div class="us-legend"><span><i class="perm full">✓</i><b>Full Access</b><small>All permissions</small></span><span><i class="perm view">◉</i><b>View Only</b><small>Read access</small></span><span><i class="perm limited">✎</i><b>Limited Access</b><small>Partial access</small></span><span><i class="perm none">−</i><b>No Access</b><small>No permissions</small></span></div></form>
<section class="us-panel us-matrix-panel"><div class="us-table-wrap"><table class="us-table us-matrix"><thead><tr><th class="sticky-col">Modules / Permissions</th>@foreach($roles as $role)<th>{{ $role->label }}<small>{{ ucfirst($role->type) }}</small></th>@endforeach</tr></thead><tbody>
@foreach($permissionModules as $module=>$modulePermissions)
<tr class="module-row"><td colspan="{{ 1+$roles->count() }}">{{ $module }}</td></tr>
@foreach($modulePermissions as $permission)
<tr><td class="sticky-col">{{ \Illuminate\Support\Str::headline($permission->action) }}</td>
@foreach($roles as $role)
@php $cell=$matrix->get($role->id.':'.$permission->id); $level=$cell->access_level??'none'; $next=$level==='full'?'view':($level==='view'?'limited':($level==='limited'?'none':'full')); @endphp
<td><form method="post" action="{{ route('admin.user-system.matrix.update') }}">@csrf<input type="hidden" name="role_id" value="{{ $role->id }}"><input type="hidden" name="permission_id" value="{{ $permission->id }}"><input type="hidden" name="access_level" value="{{ $next }}"><button class="perm {{ $level }}" title="{{ ucfirst($level) }} access">{{ $level==='full'?'✓':($level==='view'?'◉':($level==='limited'?'✎':'−')) }}</button></form></td>
@endforeach
</tr>
@endforeach
@endforeach
</tbody></table></div><p class="us-note"><b>Note:</b> Click any cell to cycle permission access.</p></section>
<div class="us-bottom-grid four"><section class="us-panel"><h3>Permission Distribution</h3><div class="us-donut"><b>{{ number_format($totalPermissionSlots) }}</b><span>Total Permissions</span></div><div class="us-legend-list">@foreach($distribution as $label=>$value)<p><i class="perm {{ $label }}"></i><span>{{ ucfirst($label) }} Access</span><b>{{ number_format($value) }}</b></p>@endforeach</div></section><section class="us-panel"><h3>Permissions by Module</h3>@include('admin.user-system.partials.bars',['items'=>collect($moduleTotals)->map(fn($x)=>(array)$x)->all()])</section><section class="us-panel"><h3>Recent Changes</h3><div class="us-activity-list">@foreach($recentPermissionChanges as $log)<p>{{ \Illuminate\Support\Str::headline($log->action) }}<span>{{ optional($log->created_at)->format('d M H:i') }}</span></p>@endforeach</div></section><section class="us-panel"><h3>Quick Actions</h3><div class="us-action-list"><a href="{{ route('admin.user-system.roles-permissions') }}">✎ <span>Edit Permissions</span></a><a href="{{ route('admin.user-system.matrix.export') }}">⇩ <span>Export Module Permissions</span></a><a href="{{ route('admin.user-system.activity') }}">◉ <span>Permission Audit</span></a></div></section></div>
<dialog id="import-matrix" class="us-modal"><form method="post" enctype="multipart/form-data" action="{{ route('admin.user-system.matrix.import') }}">@csrf<h2>Import Permission Matrix</h2><label class="us-field">CSV File<input type="file" name="file" accept=".csv" required></label><p>Columns: Role, Module, Action, Permission, Access Level.</p><div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Import Matrix</button></div></form></dialog>