<div class="us-title-actions us-page-actions"><a class="us-btn" href="{{ route('admin.user-system.matrix') }}">Permission Matrix</a><a class="us-btn" href="{{ route('admin.user-system.roles.export') }}">Export Roles</a><button class="us-btn us-btn-primary" type="button" data-us-open="add-role">+ Create Role</button></div>
<nav class="us-tabs top"><a class="active" href="{{ route('admin.user-system.roles') }}">Roles</a><a href="{{ route('admin.user-system.matrix') }}">Permissions</a><a href="{{ route('admin.user-system.matrix') }}">Permission Matrix</a><a href="{{ route('admin.user-system.users') }}">Users</a><a href="{{ route('admin.user-system.roles-permissions') }}">Access Control</a><a href="{{ route('admin.user-system.roles') }}">Role Hierarchy</a></nav>
<div class="us-main-grid">
<section class="us-panel us-table-panel"><div class="us-panel-title"><h2>Roles <span>({{ $roles->total() }} Results)</span></h2></div><div class="us-table-wrap"><table class="us-table"><thead><tr><th>Role Name</th><th>Type</th><th>Users</th><th>Level</th><th>Status</th><th>Description</th><th>Actions</th></tr></thead><tbody>
@foreach($roles as $role)<tr class="{{ $selectedRole?->id===$role->id?'selected':'' }}"><td><a href="{{ route('admin.user-system.roles',['selected'=>$role->id]) }}"><b>{{ $role->label }}</b></a></td><td><span class="us-pill info">{{ ucfirst($role->type) }}</span></td><td>{{ $role->users_count }}</td><td>{{ $role->level }}</td><td><span class="us-pill {{ $role->is_active?'success':'danger' }}">{{ $role->is_active?'Active':'Inactive' }}</span></td><td>{{ $role->description }}</td><td class="us-row-actions"><button type="button" data-us-open="edit-role-{{ $role->id }}">✎</button><form method="post" action="{{ route('admin.user-system.roles.clone',$role) }}">@csrf<button>⧉</button></form></td></tr>@endforeach
</tbody></table></div><div class="us-pagination">{{ $roles->links() }}</div></section>
<aside class="us-panel us-detail"><h2>Role Details</h2>@if($selectedRole)<div class="us-role-hero"><span class="us-role-crown">♛</span><div><h3>{{ $selectedRole->label }}</h3><p>{{ ucfirst($selectedRole->type) }} Role</p></div></div><dl class="us-kv"><dt>Level</dt><dd>{{ $selectedRole->level }}</dd><dt>Users</dt><dd>{{ $selectedRole->users_count }}</dd><dt>Permissions</dt><dd>{{ $selectedRole->permissions_count }}</dd><dt>Status</dt><dd>{{ $selectedRole->is_active?'Active':'Inactive' }}</dd><dt>Description</dt><dd>{{ $selectedRole->description }}</dd></dl><div class="us-action-list"><button type="button" data-us-open="edit-role-{{ $selectedRole->id }}">✎ <span>Edit Role</span></button><a href="{{ route('admin.user-system.assignments',['role'=>$selectedRole->id]) }}">♙ <span>Assign Users</span></a><a href="{{ route('admin.user-system.matrix',['role'=>$selectedRole->id]) }}">▦ <span>Permission Matrix</span></a></div>@endif</aside>
</div>
<div class="us-bottom-grid four"><section class="us-panel"><h3>Roles by Level</h3>@include('admin.user-system.partials.bars',['items'=>$roleAnalytics['levels']])</section><section class="us-panel"><h3>Roles by Type</h3><div class="us-donut"><b>{{ \App\Models\Role::count() }}</b><span>Total Roles</span></div></section><section class="us-panel"><h3>Top Roles by Users</h3>@include('admin.user-system.partials.bars',['items'=>$roleAnalytics['users']])</section><section class="us-panel"><h3>Recent Role Changes</h3><div class="us-activity-list">@foreach($recentRoleChanges as $log)<p>{{ \Illuminate\Support\Str::headline($log->action) }}<span>{{ optional($log->created_at)->format('d M H:i') }}</span></p>@endforeach</div></section></div>
<dialog id="add-role" class="us-modal wide"><form method="post" action="{{ route('admin.user-system.roles.store') }}">@csrf<h2>Create Role</h2>@include('admin.user-system.partials.role-form',['editRole'=>null])<div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Create Role</button></div></form></dialog>
@foreach($roles as $role)<dialog id="edit-role-{{ $role->id }}" class="us-modal wide"><form method="post" action="{{ route('admin.user-system.roles.update',$role) }}">@csrf @method('PATCH')<h2>Edit {{ $role->label }}</h2>@include('admin.user-system.partials.role-form',['editRole'=>$role])<div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Save Role</button></div></form></dialog>@endforeach