<div class="us-title-actions us-page-actions"><button class="us-btn" type="button" data-us-open="import-users">Import Users</button><a class="us-btn" href="{{ route('admin.user-system.users.export') }}">Export</a><button class="us-btn us-btn-primary" type="button" data-us-open="add-user">+ Add User</button></div>
<form class="us-filterbar" method="get">
    <label><span>Search Users</span><input name="q" value="{{ request('q') }}" placeholder="Search by name, email..."></label>
    <label><span>Role</span><select name="role"><option value="">All Roles</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((string)request('role')===(string)$role->id)>{{ $role->label }}</option>@endforeach</select></label>
    <label><span>Department</span><select name="department"><option value="">All Departments</option>@foreach($departments as $department)<option value="{{ $department }}" @selected(request('department')===$department)>{{ $department }}</option>@endforeach</select></label>
    <label><span>Status</span><select name="status"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></label>
    <label><span>2FA Status</span><select name="two_factor"><option value="">All</option><option value="1" @selected(request('two_factor')==='1')>Enabled</option><option value="0" @selected(request('two_factor')==='0')>Disabled</option></select></label>
    <button class="us-btn">Filters</button><a class="us-btn" href="{{ route('admin.user-system.users') }}">Reset</a>
</form>
<div class="us-main-grid">
    <section class="us-panel us-table-panel"><div class="us-panel-title"><h2>Users <span>({{ $users->total() }} Results)</span></h2></div><div class="us-table-wrap"><table class="us-table"><thead><tr><th>User</th><th>Role</th><th>Department</th><th>Status</th><th>2FA</th><th>Last Login</th><th>Created On</th><th>Actions</th></tr></thead><tbody>
        @forelse($users as $user)
            <tr class="{{ $selectedUser?->id===$user->id?'selected':'' }}"><td><a class="us-person" href="{{ route('admin.user-system.users',['selected'=>$user->id]) }}"><span class="us-avatar">{{ strtoupper(substr($user->name,0,2)) }}</span><span><b>{{ $user->name }}</b><small>{{ $user->email }}</small></span></a></td><td>{{ $user->roles->first()?->label ?? 'Unassigned' }}</td><td>{{ $user->department ?: '—' }}</td><td><span class="us-pill {{ $user->status==='active'?'success':'danger' }}">{{ ucfirst($user->status) }}</span></td><td>{{ $user->two_factor_enabled?'✓':'—' }}</td><td>{{ optional($user->last_login_at)->format('d M Y, H:i') ?: '—' }}</td><td>{{ optional($user->created_at)->format('d M Y') }}</td><td class="us-row-actions"><a href="{{ route('admin.user-system.users',['selected'=>$user->id]) }}">◉</a><button type="button" data-us-open="edit-user-{{ $user->id }}">✎</button></td></tr>
        @empty
            <tr><td colspan="8" class="us-empty">No users match these filters.</td></tr>
        @endforelse
    </tbody></table></div><div class="us-pagination"><span>Showing {{ $users->firstItem()??0 }} to {{ $users->lastItem()??0 }} of {{ $users->total() }} entries</span>{{ $users->links() }}</div></section>
    <aside class="us-panel us-detail"><h2>User Details</h2>
        @if($selectedUser)
            <div class="us-profile-head"><span class="us-profile-avatar">{{ strtoupper(substr($selectedUser->name,0,2)) }}</span><div><h3>{{ $selectedUser->name }} <span class="us-pill {{ $selectedUser->status==='active'?'success':'danger' }}">{{ ucfirst($selectedUser->status) }}</span></h3><p>{{ $selectedUser->roles->first()?->label ?? 'Unassigned' }}</p><small>{{ $selectedUser->email }}</small><small>{{ $selectedUser->phone ?: '—' }}</small></div></div>
            <nav class="us-tabs"><b>Overview</b><span>Roles &amp; Permissions</span><span>Activity</span><span>Security</span></nav>
            <dl class="us-kv"><dt>User ID</dt><dd>{{ $selectedUser->employee_code ?: 'USR-'.str_pad($selectedUser->id,6,'0',STR_PAD_LEFT) }}</dd><dt>Department</dt><dd>{{ $selectedUser->department ?: '—' }}</dd><dt>Status</dt><dd>{{ ucfirst($selectedUser->status) }}</dd><dt>2FA Status</dt><dd>{{ $selectedUser->two_factor_enabled?'Enabled':'Disabled' }}</dd><dt>Last Login</dt><dd>{{ optional($selectedUser->last_login_at)->format('d M Y H:i') ?: 'Never' }}</dd></dl>
            <div class="us-detail-actions"><button class="us-btn us-btn-primary" type="button" data-us-open="edit-user-{{ $selectedUser->id }}">Edit User</button><form method="post" action="{{ route('admin.user-system.users.action',$selectedUser) }}">@csrf<input type="hidden" name="action" value="reset-password"><button class="us-btn">Reset Password</button></form></div>
        @endif
    </aside>
</div>
<div class="us-bottom-grid four"><section class="us-panel"><h3>Users by Role</h3>@include('admin.user-system.partials.bars',['items'=>$analytics['roles']])</section><section class="us-panel"><h3>Users by Department</h3>@include('admin.user-system.partials.bars',['items'=>$analytics['departments']])</section><section class="us-panel"><h3>2FA Adoption</h3><div class="us-donut"><b>{{ \App\Models\User::where('two_factor_enabled',true)->count() }}</b><span>Enabled</span></div></section><section class="us-panel"><h3>Account Status</h3><div class="us-donut"><b>{{ \App\Models\User::count() }}</b><span>Total Users</span></div></section></div>
<dialog id="add-user" class="us-modal"><form method="post" action="{{ route('admin.user-system.users.store') }}">@csrf<h2>Add User</h2>@include('admin.user-system.partials.user-form',['editUser'=>null])<div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Create User</button></div></form></dialog>
<dialog id="import-users" class="us-modal"><form method="post" enctype="multipart/form-data" action="{{ route('admin.user-system.users.import') }}">@csrf<h2>Import Users</h2><label class="us-field">CSV File<input type="file" name="file" accept=".csv,text/csv" required></label><div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Import</button></div></form></dialog>
@foreach($users as $user)
<dialog id="edit-user-{{ $user->id }}" class="us-modal"><form method="post" action="{{ route('admin.user-system.users.update',$user) }}">@csrf @method('PATCH')<h2>Edit {{ $user->name }}</h2>@include('admin.user-system.partials.user-form',['editUser'=>$user])<div class="us-detail-actions"><button type="button" class="us-btn" data-us-close>Cancel</button><button class="us-btn us-btn-primary">Save User</button></div></form></dialog>
@endforeach