@extends('layouts.admin')
@section('title','Variants')
@push('styles')<link rel="stylesheet" href="{{ asset('css/admin-variants.css') }}?v=20260910-variants-v1">@endpush
@section('content')
@php
$money=fn($value)=>'€'.number_format((float)$value,2);
$imageUrl=function($path){if(!filled($path))return null;if(str_starts_with($path,'http://')||str_starts_with($path,'https://')||str_starts_with($path,'/'))return $path;return \Illuminate\Support\Facades\Storage::disk('public')->url($path);};
$tabLabels=['all'=>'All Variants','active'=>'Active','inactive'=>'Inactive','low_stock'=>'Low Stock','out_of_stock'=>'Out of Stock','discontinued'=>'Discontinued'];
$selectedImage=$selected?($imageUrl($selected->image)?:$imageUrl($selected->media->firstWhere('type','image')?->path)?:$imageUrl($selected->product?->image)):null;
@endphp
<div class="vm-page" data-variant-page>
<section class="vm-heading"><div><h1>Variants</h1><p>Create, manage and track product variants like size, colour, material and style combinations with pricing and stock.</p></div><div class="vm-date-card"><x-icon name="calendar" size="22"/><span><small>Today</small><b>{{ now()->format('l, j F Y') }}</b><strong>{{ now()->format('h:i A') }}</strong></span></div></section>
@if(session('success'))<div class="vm-alert vm-alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="vm-alert vm-alert-error"><strong>Please correct the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="vm-layout"><main class="vm-main">
<section class="vm-stats">
<article><span class="vm-stat-icon green"><x-icon name="package" size="20"/></span><div><small>Total Variants</small><strong>{{ number_format($stats['total']) }}</strong><em>↑ live catalog</em></div></article>
<article><span class="vm-stat-icon green"><x-icon name="check" size="20"/></span><div><small>Active Variants</small><strong>{{ number_format($stats['active']) }}</strong><em>ready for sale</em></div></article>
<article><span class="vm-stat-icon red"><x-icon name="shopping-bag" size="20"/></span><div><small>Out of Stock</small><strong>{{ number_format($stats['out_of_stock']) }}</strong><em class="down">needs attention</em></div></article>
<article><span class="vm-stat-icon orange"><x-icon name="shopping-bag" size="20"/></span><div><small>Low Stock (≤ threshold)</small><strong>{{ number_format($stats['low_stock']) }}</strong><em class="down">reorder soon</em></div></article>
<article><span class="vm-stat-icon green"><x-icon name="package" size="20"/></span><div><small>Total Stock (All Variants)</small><strong>{{ number_format($stats['total_stock']) }}</strong><em>available units</em></div></article>
<article><span class="vm-stat-icon slate"><x-icon name="alert" size="20"/></span><div><small>Disabled Variants</small><strong>{{ number_format($stats['inactive']) }}</strong><em class="down">not active</em></div></article>
</section>
<nav class="vm-tabs">@foreach($tabLabels as $key=>$label)<a class="{{ $tab===$key?'active':'' }}" href="{{ route('admin.variants.index',array_filter(['tab'=>$key,'q'=>$search,'product_id'=>$productId?:null])) }}">{{ $label }}</a>@endforeach</nav>
<form class="vm-filters" method="get" action="{{ route('admin.variants.index') }}"><input type="hidden" name="tab" value="{{ $tab }}"><label class="vm-search"><x-icon name="search" size="14"/><input type="search" name="q" value="{{ $search }}" placeholder="Search variants by SKU, name, or product..."></label><button class="vm-filter-btn" type="submit"><x-icon name="filter" size="14"/> Filters</button><select name="product_id" onchange="this.form.submit()"><option value="">All Products</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($productId===$product->id)>{{ $product->name }}</option>@endforeach</select><select name="status" onchange="this.form.submit()"><option value="">All Statuses</option>@foreach(['active','inactive','discontinued'] as $s)<option value="{{ $s }}" @selected($status===$s)>{{ str($s)->headline() }}</option>@endforeach</select><select name="option_set" onchange="this.form.submit()"><option value="">All Option Sets</option>@foreach(['colour','size','material','style'] as $option)<option value="{{ $option }}" @selected($optionSet===$option)>{{ str($option)->headline() }}</option>@endforeach</select><select name="stock_status" onchange="this.form.submit()"><option value="">All Stock Status</option><option value="in_stock" @selected($stockStatus==='in_stock')>In Stock</option><option value="low_stock" @selected($stockStatus==='low_stock')>Low Stock</option><option value="out_of_stock" @selected($stockStatus==='out_of_stock')>Out of Stock</option></select><a class="vm-reset" href="{{ route('admin.variants.index') }}"><x-icon name="refresh" size="13"/> Reset</a></form>
<section class="vm-table-card"><div class="vm-table-wrap"><table class="vm-table"><thead><tr><th><input type="checkbox" data-check-all></th><th>Variant</th><th>Product</th><th>Options (Combinations)</th><th>Variant SKU</th><th>Price</th><th>Stock <small>Available / Total</small></th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($variants as $variant)
@php $rowImage=$imageUrl($variant->image)?:$imageUrl($variant->media->firstWhere('type','image')?->path)?:$imageUrl($variant->product?->image);$stockState=$variant->stock_state;$payload=['id'=>$variant->id,'product_id'=>$variant->product_id,'sku'=>$variant->sku,'barcode'=>$variant->barcode,'colour'=>$variant->colour,'size'=>$variant->size,'material'=>$variant->material,'style'=>$variant->style,'price'=>$variant->price,'compare_price'=>$variant->compare_price,'cost_price'=>$variant->cost_price,'stock'=>$variant->stock,'stock_total'=>$variant->stock_total,'status'=>$variant->status,'low_stock_threshold'=>$variant->low_stock_threshold,'track_inventory'=>$variant->track_inventory,'backorder'=>$variant->backorder]; @endphp
<tr class="{{ $selected?->id===$variant->id?'selected':'' }}"><td><input type="checkbox" value="{{ $variant->public_uuid }}" data-variant-check></td><td class="vm-thumb-cell">@if($rowImage)<img src="{{ $rowImage }}" alt="{{ $variant->sku }}">@else<span class="vm-thumb-placeholder"><x-icon name="package" size="20"/></span>@endif</td><td><strong>{{ $variant->product?->name?:'Product unavailable' }}</strong><small>Parent SKU: {{ $variant->product?->sku?:'—' }}</small><span class="vm-mini-state">{{ $variant->product?->is_active?'Active':'Inactive' }}</span></td><td class="vm-options">@if($variant->colour)<span><i></i>Colour: {{ $variant->colour }}</span>@endif @if($variant->size)<span><i></i>Size: {{ $variant->size }}</span>@endif @if($variant->material)<span><i></i>Material: {{ $variant->material }}</span>@endif @if($variant->style)<span><i></i>Style: {{ $variant->style }}</span>@endif @if(!$variant->colour&&!$variant->size&&!$variant->material&&!$variant->style)<span>Default variant</span>@endif</td><td><strong>{{ $variant->sku }}</strong><small><x-icon name="tag" size="11"/> Barcode: {{ $variant->barcode?:'—' }}</small></td><td><strong>{{ $money($variant->display_price) }}</strong><small>@if($variant->compare_price)Compare: {{ $money($variant->compare_price) }}@else Product price fallback @endif</small></td><td><strong>{{ number_format($variant->stock) }} / {{ number_format(max($variant->stock_total,$variant->stock)) }}</strong><small class="stock-{{ $stockState }}">{{ str($stockState)->headline() }}</small></td><td><span class="vm-status vm-status-{{ $variant->status }}">{{ str($variant->status)->headline() }}</span></td><td><div class="vm-row-actions"><a href="{{ route('admin.variants.index',array_merge(request()->query(),['selected'=>$variant->public_uuid])) }}"><x-icon name="eye" size="14"/></a><button type="button" data-edit-variant='@json($payload)'><x-icon name="pencil" size="14"/></button><a href="{{ route('admin.variants.audit',$variant) }}"><x-icon name="dots" size="14"/></a></div></td></tr>
@empty<tr><td colspan="9" class="vm-empty">No variants matched these filters. Add a variant or bulk-create option combinations.</td></tr>@endforelse
</tbody></table></div><footer class="vm-table-footer"><span>Showing {{ number_format($variants->firstItem()??0) }} to {{ number_format($variants->lastItem()??0) }} of {{ number_format($variants->total()) }} variants</span><div class="vm-pagination">{{ $variants->onEachSide(1)->links() }}</div><form method="get"><input type="hidden" name="tab" value="{{ $tab }}"><select name="per_page" onchange="this.form.submit()">@foreach([8,16,32,64] as $n)<option value="{{ $n }}" @selected($perPage===$n)>{{ $n }} / page</option>@endforeach</select></form></footer></section>
<section class="vm-bottom-grid">
<article class="vm-panel"><h3>Variant Options Overview</h3><dl><div><dt>Total Option Sets</dt><dd>{{ $optionOverview['total_sets'] }}</dd></div><div><dt>Total Option Values</dt><dd>{{ $optionOverview['total_values'] }}</dd></div><div><dt>Total Combinations Possible</dt><dd>{{ number_format($optionOverview['combinations_possible']) }}</dd></div><div><dt>Total Combinations Created</dt><dd>{{ number_format($optionOverview['combinations_created']) }}</dd></div></dl><button type="button" class="vm-outline" data-open-dialog="vmOptionDialog">Manage Option Sets</button></article>
<article class="vm-panel"><h3>Variant Settings</h3><form method="post" action="{{ route('admin.variants.settings') }}" class="vm-settings-form">@csrf @foreach(['auto_generate_sku'=>'Auto Generate Variant SKU','auto_manage_stock'=>'Auto Manage Stock from Unified Stock Master','sync_variant_stock'=>'Sync Variant Stock to Channels','track_variant_inventory'=>'Track Variant Inventory'] as $field=>$label)<label><span>{{ $label }}</span><input type="hidden" name="{{ $field }}" value="0"><input type="checkbox" name="{{ $field }}" value="1" @checked($settings->$field)></label>@endforeach<button class="vm-outline" type="submit">Manage Settings</button></form></article>
<article class="vm-panel"><h3>Pricing &amp; Inventory</h3><form method="post" action="{{ route('admin.variants.settings') }}" class="vm-price-settings">@csrf<label>Price Rounding<select name="price_rounding"><option value="2" @selected($settings->price_rounding===2)>2 Decimal Places</option><option value="0" @selected($settings->price_rounding===0)>Whole Amount</option></select></label><label>Inventory Policy<select name="inventory_policy"><option value="deny" @selected($settings->inventory_policy==='deny')>Deny if Out of Stock</option><option value="allow" @selected($settings->inventory_policy==='allow')>Allow Overselling</option></select></label><label class="vm-toggle-line">Backorder <input type="hidden" name="backorder" value="0"><input type="checkbox" name="backorder" value="1" @checked($settings->backorder)></label><label>Low Stock Threshold<input type="number" name="low_stock_threshold" min="0" value="{{ $settings->low_stock_threshold }}"></label><button class="vm-outline" type="submit">Save Settings</button></form></article>
<article class="vm-panel vm-media-panel"><h3>Media per Variant</h3><p>Add images, 360° views and videos for variants.</p><div class="vm-media-strip">@if($selected) @forelse($selected->media->take(3) as $media) @if($media->type==='image')<img src="{{ $imageUrl($media->path) }}" alt="{{ $media->alt_text?:$selected->sku }}">@else<span>{{ $media->type==='spin_360'?'360°':'Video' }}</span>@endif @empty @if($selectedImage)<img src="{{ $selectedImage }}" alt="{{ $selected->sku }}">@endif @endforelse @endif<button type="button" data-open-dialog="vmMediaDialog" @disabled(!$selected)>+<small>Add Media</small></button></div><button type="button" class="vm-outline" data-open-dialog="vmMediaDialog" @disabled(!$selected)>Manage Media</button></article>
<article class="vm-panel vm-preview-panel"><h3>Variant Preview</h3>@if($selected)<div class="vm-preview-stage">@if($selectedImage)<img src="{{ $selectedImage }}" alt="{{ $selected->sku }}">@else<x-icon name="package" size="54"/>@endif</div><strong>{{ $selected->product?->name }}</strong><small>{{ collect([$selected->colour,$selected->size,$selected->material,$selected->style])->filter()->implode(' • ')?:'Default combination' }}</small><small>SKU: {{ $selected->sku }}</small>@if($selected->product)<a class="vm-outline" target="_blank" href="{{ route('product',$selected->product) }}">View on Store <x-icon name="arrow-right" size="12"/></a>@endif @else<div class="vm-preview-stage"><x-icon name="package" size="54"/></div><small>No variant selected.</small>@endif</article>
</section></main>
<aside class="vm-rail"><button class="vm-primary" type="button" data-open-dialog="vmAddDialog"><x-icon name="plus" size="14"/> Add Variant <span>⌄</span></button><button class="vm-bulk-trigger" type="button" data-open-dialog="vmBulkDialog">Bulk Actions <span data-selected-count>0 selected</span></button>
<section class="vm-rail-card"><h3>Variant Summary</h3><dl><div><dt>Total Variants</dt><dd>{{ number_format($stats['total']) }}</dd></div><div><dt>Active Variants</dt><dd>{{ number_format($stats['active']) }}</dd></div><div><dt>Inactive Variants</dt><dd>{{ number_format($stats['inactive']) }}</dd></div><div><dt>Out of Stock</dt><dd>{{ number_format($stats['out_of_stock']) }}</dd></div><div><dt>Low Stock (≤ {{ $settings->low_stock_threshold }})</dt><dd>{{ number_format($stats['low_stock']) }}</dd></div><div><dt>Total Stock (All Variants)</dt><dd>{{ number_format($stats['total_stock']) }}</dd></div><div><dt>Average Price</dt><dd>{{ $money($stats['average_price']) }}</dd></div><div><dt>Highest Price</dt><dd>{{ $money($stats['highest_price']) }}</dd></div><div><dt>Lowest Price</dt><dd>{{ $money($stats['lowest_price']) }}</dd></div></dl></section>
<section class="vm-rail-card"><h3>Option Sets Used</h3><div class="vm-option-chart"><div class="vm-donut"><span><b>{{ $optionOverview['total_values'] }}</b>Total</span></div><ul>@foreach($optionOverview['sets'] as $key=>$set)<li><i class="dot-{{ $key }}"></i><span>{{ $set['label'] }} ({{ $set['values'] }})</span><b>{{ number_format($set['percent'],1) }}%</b></li>@endforeach</ul></div></section>
<section class="vm-rail-card vm-quick"><h3>Quick Actions</h3><button type="button" data-open-dialog="vmAddDialog"><x-icon name="plus" size="14"/> Add New Variant</button><button type="button" data-open-dialog="vmBulkCreateDialog"><x-icon name="copy" size="14"/> Bulk Create Variants</button><button type="button" data-open-dialog="vmBulkDialog"><x-icon name="settings" size="14"/> Bulk Update Prices / Stock</button><button type="button" data-open-dialog="vmImportDialog"><x-icon name="upload" size="14"/> Import Variants (CSV)</button><a href="{{ route('admin.variants.export') }}"><x-icon name="download" size="14"/> Export Variants</a><a href="{{ route('admin.variants.export',['report'=>'combinations']) }}"><x-icon name="file-text" size="14"/> Variant Combination Report</a><a href="{{ route('admin.variants.export',['report'=>'stock']) }}"><x-icon name="file-text" size="14"/> Variant Stock Report</a></section>
<section class="vm-rail-card vm-uuid"><h3>UUID Traceability</h3><p>Every variant is assigned a unique UUID for full traceability.</p><small>Selected Variant UUID</small><div><code data-selected-uuid>{{ $selected?->public_uuid?:'—' }}</code><button type="button" data-copy-uuid @disabled(!$selected)><x-icon name="copy" size="13"/></button></div>@if($selected)<a href="{{ route('admin.variants.audit',$selected) }}">View Variant Audit Log <x-icon name="chevron-right" size="13"/></a>@endif</section></aside></div></div>
<dialog id="vmAddDialog" class="vm-dialog"><form method="post" action="{{ route('admin.variants.store') }}" class="vm-dialog-form">@csrf<header><div><h2>Add Variant</h2><p>Create a sellable option combination for a product.</p></div><button type="button" data-close-dialog>×</button></header>@include('admin.variants.partials.form-fields')<footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Create Variant</button></footer></form></dialog>
<dialog id="vmEditDialog" class="vm-dialog"><form method="post" data-edit-form data-action-template="{{ route('admin.variants.update','__ID__') }}" class="vm-dialog-form">@csrf @method('PATCH')<header><div><h2>Edit Variant</h2><p>Update options, pricing, stock and availability.</p></div><button type="button" data-close-dialog>×</button></header>@include('admin.variants.partials.form-fields')<footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Save Variant</button></footer></form></dialog>
<dialog id="vmBulkCreateDialog" class="vm-dialog"><form method="post" action="{{ route('admin.variants.bulk-create') }}" class="vm-dialog-form">@csrf<header><div><h2>Bulk Create Variants</h2><p>Generate combinations from comma-separated option values.</p></div><button type="button" data-close-dialog>×</button></header><div class="vm-form-grid"><label class="wide">Product<select name="product_id" required><option value="">Choose product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} — {{ $product->sku }}</option>@endforeach</select></label><label>Colours<input name="colours" placeholder="Emerald Green, Beige, Black"></label><label>Sizes<input name="sizes" placeholder="One Size, Large"></label><label>Materials<input name="materials" placeholder="Cotton, Wool"></label><label>Styles<input name="styles" placeholder="Classic, Sport"></label><label>Price<input type="number" step="0.01" min="0" name="price"></label><label>Compare Price<input type="number" step="0.01" min="0" name="compare_price"></label><label>Available Stock<input type="number" min="0" name="stock" value="0" required></label><label>Total Stock<input type="number" min="0" name="stock_total" value="0"></label></div><footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Generate Variants</button></footer></form></dialog>
<dialog id="vmBulkDialog" class="vm-dialog"><form method="post" action="{{ route('admin.variants.bulk') }}" class="vm-dialog-form" data-bulk-action-form>@csrf<header><div><h2>Bulk Actions</h2><p>Applies to the variants selected in the table.</p></div><button type="button" data-close-dialog>×</button></header><div data-bulk-variant-inputs></div><div class="vm-form-grid"><label class="wide">Action<select name="action" required data-bulk-action><option value="">Choose action</option><option value="activate">Activate</option><option value="deactivate">Deactivate</option><option value="discontinue">Discontinue</option><option value="set_stock">Set Stock</option><option value="delete">Delete</option></select></label><label data-stock-field hidden>Available Stock<input type="number" min="0" name="stock"></label><label data-stock-field hidden>Total Stock<input type="number" min="0" name="stock_total"></label></div><footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Apply to Selected</button></footer></form></dialog>
<dialog id="vmImportDialog" class="vm-dialog"><form method="post" enctype="multipart/form-data" action="{{ route('admin.variants.import') }}" class="vm-dialog-form">@csrf<header><div><h2>Import Variants</h2><p>CSV must include product_sku and sku. Optional: barcode, colour, size, material, style, price, compare_price, stock, stock_total, status and low_stock_threshold.</p></div><button type="button" data-close-dialog>×</button></header><label class="vm-file-drop">CSV File<input type="file" name="file" accept=".csv,text/csv" required></label><footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Import CSV</button></footer></form></dialog>
<dialog id="vmOptionDialog" class="vm-dialog"><div class="vm-dialog-form"><header><div><h2>Option Sets in Use</h2><p>Option values are managed directly on variants and used by bulk combination generation.</p></div><button type="button" data-close-dialog>×</button></header><div class="vm-option-list">@foreach($optionOverview['sets'] as $key=>$set)<article><strong>{{ $set['label'] }}</strong><span>{{ $set['values'] }} distinct values</span><small>{{ $set['uses'] }} variant assignments</small></article>@endforeach</div><footer><button type="button" class="vm-primary" data-close-dialog>Done</button></footer></div></dialog>
<dialog id="vmMediaDialog" class="vm-dialog">@if($selected)<form method="post" enctype="multipart/form-data" action="{{ route('admin.variants.media.store',$selected) }}" class="vm-dialog-form">@csrf<header><div><h2>Media for {{ $selected->sku }}</h2><p>Upload a variant image, video, or 360° asset.</p></div><button type="button" data-close-dialog>×</button></header><div class="vm-form-grid"><label>Media Type<select name="type"><option value="image">Image</option><option value="video">Video</option><option value="spin_360">360° Asset</option></select></label><label>Alt Text<input name="alt_text" value="{{ $selected->product?->name }} {{ $selected->sku }}"></label><label class="wide">File<input type="file" name="file" required></label></div>@if($selected->media->isNotEmpty())<div class="vm-existing-media">@foreach($selected->media as $media)<article><span>{{ str($media->type)->headline() }}</span><small>{{ basename($media->path) }}</small><button type="submit" form="delete-media-{{ $media->id }}">Remove</button></article>@endforeach</div>@endif<footer><button type="button" class="vm-secondary" data-close-dialog>Cancel</button><button class="vm-primary" type="submit">Upload Media</button></footer></form>@foreach($selected->media as $media)<form id="delete-media-{{ $media->id }}" method="post" action="{{ route('admin.variants.media.destroy',[$selected,$media]) }}">@csrf @method('DELETE')</form>@endforeach @else<div class="vm-dialog-form"><header><h2>No variant selected</h2><button type="button" data-close-dialog>×</button></header></div>@endif</dialog>
<script src="{{ asset('js/admin-variants.js') }}?v=20260910-variants-v1" defer></script>
@endsection
