<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
return new class extends Migration { public function up():void{
if(DB::getDriverName()==='pgsql')DB::statement('CREATE EXTENSION IF NOT EXISTS pgcrypto');
foreach(['users','categories','products','orders','order_items','inquiries','stores','product_variants','addresses','wishlists','reviews','returns','reward_transactions','inventory_movements','payment_transactions','shipping_methods','discounts','admin_records'] as $table){
    Schema::table($table,fn(Blueprint $t)=>$t->uuid('public_uuid')->nullable()->unique());
    DB::table($table)->select('id')->orderBy('id')->chunkById(500,function($rows)use($table){
        foreach($rows as $row)DB::table($table)->where('id',$row->id)->update(['public_uuid'=>(string)Str::uuid()]);
    });
    Schema::table($table,fn(Blueprint $t)=>$t->uuid('public_uuid')->nullable(false)->change());
}
Schema::table('content_pages',function(Blueprint $t){$t->uuid('uuid')->nullable()->unique();$t->string('locale',10)->default('en')->index();$t->string('template')->default('standard');$t->boolean('navigation_visible')->default(false);$t->timestampTz('scheduled_for')->nullable()->index();$t->timestampTz('published_at')->nullable()->index();$t->timestampTz('archived_at')->nullable();$t->softDeletesTz();});
DB::table('content_pages')->select('id')->orderBy('id')->chunkById(500,function($rows){
    foreach($rows as $row)DB::table('content_pages')->where('id',$row->id)->update(['uuid'=>(string)Str::uuid()]);
});
Schema::table('content_pages',fn(Blueprint $t)=>$t->uuid('uuid')->nullable(false)->change());
Schema::create('page_templates',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->jsonb('schema');$t->boolean('active')->default(true);$t->timestampsTz();});
Schema::create('page_sections',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('content_page_id')->constrained()->cascadeOnDelete();$t->string('type');$t->string('label')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->jsonb('settings');$t->boolean('visible')->default(true);$t->timestampsTz();$t->index(['content_page_id','sort_order']);});
Schema::create('page_revisions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('content_page_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->unsignedInteger('version');$t->jsonb('snapshot');$t->string('reason')->nullable();$t->timestampsTz();$t->unique(['content_page_id','version']);});
Schema::create('product_media',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->enum('type',['image','video','spin_360','try_on']);$t->string('disk')->default('public');$t->string('path');$t->string('alt_text')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->jsonb('metadata')->nullable();$t->boolean('active')->default(true);$t->timestampsTz();$t->index(['product_id','type','sort_order']);});
Schema::create('franchise_applications',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('applicant_name');$t->string('email')->index();$t->string('phone')->nullable();$t->string('territory');$t->string('preferred_location')->nullable();$t->string('investment_range')->nullable();$t->text('business_experience')->nullable();$t->string('status')->default('new')->index();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->timestampTz('follow_up_at')->nullable()->index();$t->jsonb('data')->nullable();$t->timestampsTz();});
Schema::create('franchise_stores',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('franchise_application_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->string('code')->unique();$t->string('name');$t->string('territory');$t->jsonb('address');$t->string('status')->default('onboarding')->index();$t->date('opened_at')->nullable();$t->timestampsTz();});
Schema::create('franchise_milestones',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('franchise_application_id')->constrained()->cascadeOnDelete();$t->enum('type',['territory','agreement','training','store_setup','marketing','performance','renewal']);$t->string('status')->default('pending')->index();$t->date('due_on')->nullable();$t->date('completed_on')->nullable();$t->jsonb('data')->nullable();$t->timestampsTz();});
Schema::create('conversations',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->enum('channel',['web','chat','whatsapp','email','phone','system']);$t->string('contact');$t->string('subject')->nullable();$t->string('priority')->default('normal')->index();$t->string('status')->default('new')->index();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->timestampTz('follow_up_at')->nullable()->index();$t->jsonb('metadata')->nullable();$t->timestampsTz();});
Schema::create('conversation_messages',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->enum('direction',['inbound','outbound','internal']);$t->text('body');$t->string('delivery_status')->default('stored');$t->jsonb('payload')->nullable();$t->timestampTz('sent_at')->nullable();$t->timestampsTz();});
Schema::create('communication_templates',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->enum('channel',['email','whatsapp','chat']);$t->string('name');$t->string('subject')->nullable();$t->longText('body');$t->string('status')->default('draft')->index();$t->jsonb('variables')->nullable();$t->timestampsTz();});
Schema::create('approvals',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->nullableMorphs('approvable');$t->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('decided_by')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('pending')->index();$t->text('decision_note')->nullable();$t->timestampTz('decided_at')->nullable();$t->timestampsTz();});
Schema::create('roles',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name')->unique();$t->string('label');$t->timestampsTz();});
Schema::create('permissions',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name')->unique();$t->string('group')->index();$t->timestampsTz();});
Schema::create('permission_role',function(Blueprint $t){$t->foreignId('permission_id')->constrained()->cascadeOnDelete();$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->primary(['permission_id','role_id']);});
Schema::create('role_user',function(Blueprint $t){$t->foreignId('role_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->primary(['role_id','user_id']);});
Schema::create('integration_connections',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('service')->unique();$t->string('provider')->nullable();$t->boolean('enabled')->default(false);$t->text('encrypted_credentials')->nullable();$t->string('health')->default('not_configured');$t->timestampTz('tested_at')->nullable();$t->timestampsTz();});
Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action')->index();$t->nullableMorphs('subject');$t->uuid('request_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->jsonb('before')->nullable();$t->jsonb('after')->nullable();$t->timestampTz('created_at')->useCurrent();});
Schema::create('automation_rules',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('event');$t->jsonb('conditions');$t->jsonb('actions');$t->boolean('enabled')->default(false);$t->timestampsTz();});
Schema::create('backup_runs',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('type');$t->string('status')->index();$t->string('location')->nullable();$t->unsignedBigInteger('size_bytes')->nullable();$t->timestampTz('started_at');$t->timestampTz('completed_at')->nullable();$t->jsonb('metadata')->nullable();});
} public function down():void{foreach(['backup_runs','automation_rules','audit_logs','integration_connections','role_user','permission_role','permissions','roles','approvals','communication_templates','conversation_messages','conversations','franchise_milestones','franchise_stores','franchise_applications','product_media','page_revisions','page_sections','page_templates'] as $table)Schema::dropIfExists($table);Schema::table('content_pages',fn(Blueprint $t)=>$t->dropColumn(['uuid','locale','template','navigation_visible','scheduled_for','published_at','archived_at','deleted_at']));foreach(['users','categories','products','orders','order_items','inquiries','stores','product_variants','addresses','wishlists','reviews','returns','reward_transactions','inventory_movements','payment_transactions','shipping_methods','discounts','admin_records'] as $table)Schema::table($table,fn(Blueprint $t)=>$t->dropColumn('public_uuid'));} };
