<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::create('categories',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->integer('sort_order')->default(0);$t->timestamps();});
Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->string('sku')->unique();$t->text('description')->nullable();$t->decimal('price',12,2)->default(0);$t->decimal('compare_price',12,2)->nullable();$t->integer('stock')->default(0);$t->string('material')->nullable();$t->json('colours')->nullable();$t->json('sizes')->nullable();$t->string('image')->nullable();$t->json('spin_images')->nullable();$t->string('try_on_asset')->nullable();$t->boolean('is_new')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('orders',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('number')->unique();$t->string('status')->default('pending');$t->string('payment_status')->default('unpaid');$t->decimal('subtotal',12,2)->default(0);$t->decimal('shipping',12,2)->default(0);$t->decimal('total',12,2)->default(0);$t->string('currency',3)->default('EUR');$t->json('shipping_address')->nullable();$t->timestamps();});
Schema::create('order_items',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('sku')->nullable();$t->integer('quantity')->default(1);$t->decimal('unit_price',12,2);$t->decimal('total',12,2);$t->timestamps();});
Schema::create('inquiries',function(Blueprint $t){$t->id();$t->string('type')->index();$t->string('name');$t->string('email');$t->string('phone')->nullable();$t->string('company')->nullable();$t->string('subject')->nullable();$t->text('message')->nullable();$t->json('meta')->nullable();$t->string('status')->default('new');$t->timestamps();});
Schema::create('stores',function(Blueprint $t){$t->id();$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->string('business_name')->nullable();$t->string('business_type')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('description')->nullable();$t->json('branding')->nullable();$t->json('settings')->nullable();$t->string('status')->default('draft');$t->timestamps();});
Schema::create('product_store',function(Blueprint $t){$t->id();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->decimal('price',12,2)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['store_id','product_id']);});
} public function down():void{Schema::dropIfExists('product_store');Schema::dropIfExists('stores');Schema::dropIfExists('inquiries');Schema::dropIfExists('order_items');Schema::dropIfExists('orders');Schema::dropIfExists('products');Schema::dropIfExists('categories');}};
