<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::table('products',function(Blueprint $t){$t->string('status')->default('active')->after('is_active');$t->string('brand')->nullable();$t->string('care')->nullable();$t->string('meta_title')->nullable();$t->text('meta_description')->nullable();$t->decimal('weight',10,3)->nullable();$t->string('hs_code')->nullable();});
Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('sku')->unique();$t->string('colour')->nullable();$t->string('size')->nullable();$t->decimal('price',12,2)->nullable();$t->integer('stock')->default(0);$t->string('image')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('addresses',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('label')->default('Home');$t->string('name');$t->string('phone')->nullable();$t->string('line1');$t->string('line2')->nullable();$t->string('city');$t->string('county')->nullable();$t->string('postcode')->nullable();$t->string('country',2)->default('IE');$t->boolean('is_default')->default(false);$t->timestamps();});
Schema::create('wishlists',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['user_id','product_id']);});
Schema::create('reviews',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('rating');$t->string('title')->nullable();$t->text('body')->nullable();$t->string('status')->default('approved');$t->timestamps();$t->unique(['user_id','product_id']);});
Schema::create('returns',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('number')->unique();$t->string('type')->default('return');$t->string('reason');$t->text('details')->nullable();$t->string('status')->default('requested');$t->timestamps();});
Schema::create('reward_transactions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->integer('points');$t->string('type');$t->string('reference')->nullable();$t->string('description')->nullable();$t->timestamps();});
Schema::create('inventory_movements',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete();$t->integer('quantity');$t->string('type');$t->string('reference')->nullable();$t->text('note')->nullable();$t->timestamps();});
Schema::create('payment_transactions',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('provider')->default('manual');$t->string('transaction_id')->nullable()->index();$t->decimal('amount',12,2);$t->string('currency',3)->default('EUR');$t->string('status')->default('pending');$t->json('payload')->nullable();$t->timestamps();});
Schema::create('shipping_methods',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('country',2)->nullable();$t->decimal('price',12,2)->default(0);$t->decimal('free_over',12,2)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('discounts',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('type')->default('percent');$t->decimal('value',12,2);$t->decimal('minimum_order',12,2)->default(0);$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->integer('usage_limit')->nullable();$t->integer('used')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('content_pages',function(Blueprint $t){$t->id();$t->string('slug')->unique();$t->string('title');$t->text('intro')->nullable();$t->longText('body')->nullable();$t->string('status')->default('published');$t->json('meta')->nullable();$t->timestamps();});
Schema::create('admin_records',function(Blueprint $t){$t->id();$t->string('module')->index();$t->string('reference')->nullable()->index();$t->string('title');$t->string('status')->default('active');$t->decimal('amount',14,2)->nullable();$t->date('record_date')->nullable();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->json('data')->nullable();$t->timestamps();});
Schema::table('order_items',function(Blueprint $t){$t->foreignId('product_variant_id')->nullable()->after('product_id')->constrained()->nullOnDelete();$t->json('options')->nullable();});
Schema::table('orders',function(Blueprint $t){$t->enum('order_type',['online','corporate','bulk','franchise','franchise_retail','buyer'])->default('online')->index();$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('shipping_method')->nullable();$t->string('payment_method')->nullable();$t->string('discount_code')->nullable();$t->decimal('discount',12,2)->default(0);$t->text('notes')->nullable();});
} public function down():void{ Schema::table('orders',fn(Blueprint $t)=>$t->dropColumn(['order_type','email','phone','shipping_method','payment_method','discount_code','discount','notes'])); Schema::table('order_items',function(Blueprint $t){$t->dropConstrainedForeignId('product_variant_id');$t->dropColumn('options');}); foreach(['admin_records','content_pages','discounts','shipping_methods','payment_transactions','inventory_movements','reward_transactions','returns','reviews','wishlists','addresses','product_variants'] as $x) Schema::dropIfExists($x); Schema::table('products',fn(Blueprint $t)=>$t->dropColumn(['status','brand','care','meta_title','meta_description','weight','hs_code'])); }};
