<?php
namespace App\Http\Controllers;
use App\Models\{Category,ContentPage,Conversation,FranchiseApplication,Inquiry,Product};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class SiteController extends Controller {
    public function home(){return view('site.home',['categories'=>Category::where('is_active',true)->orderBy('sort_order')->get(),'newProducts'=>Product::where('is_active',true)->where('is_new',true)->latest()->limit(8)->get()]);}
    public function shop(Request $r){$q=Product::with('category')->where('is_active',true);if($r->filled('q'))$q->where(fn($x)=>$x->where('name','like','%'.$r->q.'%')->orWhere('sku','like','%'.$r->q.'%'));if($r->filled('category'))$q->whereHas('category',fn($c)=>$c->where('slug',$r->category));return view('site.shop',['products'=>$q->latest()->paginate(12)->withQueryString(),'categories'=>Category::where('is_active',true)->get()]);}
    public function product(Product $product){abort_unless($product->is_active,404);$product->load(['variants','reviews.user','category']);$related=Product::where('is_active',true)->where('id','!=',$product->id)->when($product->category_id,fn($q)=>$q->where('category_id',$product->category_id))->limit(4)->get();return view('site.product',compact('product','related'));}
    public function category(Category $category){return view('site.shop',['products'=>$category->products()->where('is_active',true)->paginate(12),'categories'=>Category::where('is_active',true)->get(),'activeCategory'=>$category]);}
    public function page(string $page){$allowed=['collections','new-arrivals','corporate-orders','bulk-orders','franchise','careers','global-network','factory','contact','virtual-tryon','irish-traditional','irish-heritage'];abort_unless(in_array($page,$allowed,true),404);$managedPage=ContentPage::with('sections')->where('slug',$page)->where('locale',app()->getLocale())->where('status','published')->where(fn($q)=>$q->whereNull('scheduled_for')->orWhere('scheduled_for','<=',now()))->first();return view('site.page',compact('page','managedPage'));}
    public function inquiry(Request $r){$d=$r->validate(['type'=>'required|string|max:50','name'=>'required|string|max:120','email'=>'required|email','phone'=>'nullable|string|max:50','company'=>'nullable|string|max:120','subject'=>'nullable|string|max:150','message'=>'nullable|string|max:5000']);DB::transaction(function()use($d){Inquiry::create($d);if($d['type']==='franchise')FranchiseApplication::create(['applicant_name'=>$d['name'],'email'=>$d['email'],'phone'=>$d['phone']??null,'territory'=>'Ireland','preferred_location'=>$d['company']??null,'business_experience'=>$d['message']??null,'status'=>'new','data'=>['source'=>'public_franchise_form']]);$conversation=Conversation::create(['channel'=>'web','contact'=>$d['email'],'subject'=>$d['subject']??str($d['type'])->headline(),'priority'=>$d['type']==='franchise'?'high':'normal','status'=>'new','metadata'=>['type'=>$d['type'],'name'=>$d['name'],'phone'=>$d['phone']??null,'company'=>$d['company']??null]]);$conversation->messages()->create(['direction'=>'inbound','body'=>$d['message']??'Public form submission','delivery_status'=>'stored','sent_at'=>now()]);});return back()->with('success','Thank you. Your enquiry is now in our Communication Centre.');}
}
