@extends('layouts.site')
@section('title',$eyebrow.' '.$title.' — Emerald Rozalia')
@push('styles')
<style>
.category-products .catalog-product-card .catalog-image-placeholder{position:relative;aspect-ratio:1/1;min-height:0;padding:0;overflow:hidden}
.category-products .catalog-product-card .catalog-image-placeholder img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}
</style>
@endpush
@section('content')
@php($publicMedia = app(\App\Services\PublicMediaResolver::class))
<section class="category-hero"><div class="catalog-breadcrumb"><a href="/">Home</a><x-icon name="chevron-right" size="14" /><a href="/shop">Shop</a><x-icon name="chevron-right" size="14" /><span>{{ $category->name }}</span></div><p class="eyebrow">{{ $eyebrow }}</p><h1>{{ $title }}</h1><p>{{ $intro }}</p><div class="category-values"><span><b>AUTHENTIC IRISH</b>Heritage styles</span><span><b>PREMIUM QUALITY</b>Built to last</span><span><b>MADE IN LIMERICK</b>Proudly Irish</span><span><b>TIMELESS STYLE</b>For every occasion</span></div></section>
<section class="catalog-section category-products"><aside class="catalog-filters"><div class="filter-heading"><h2>FILTERS</h2><a href="{{ request()->url() }}">RESET ALL</a></div><form method="get"><label>SEARCH<input name="q" value="{{ request('q') }}" placeholder="Product or SKU"></label><label>SORT<select name="sort"><option value="">Featured</option><option value="price_low" @selected(request('sort') === 'price_low')>Price: low to high</option><option value="price_high" @selected(request('sort') === 'price_high')>Price: high to low</option></select></label><button class="btn" type="submit">APPLY FILTERS</button></form></aside><div class="arrivals-results"><div class="results-heading"><p>{{ $category->name }} · Showing {{ $products->firstItem() ?: 0 }}–{{ $products->lastItem() ?: 0 }} of {{ $products->total() }} products</p><a href="{{ route('virtual-tryon') }}">TRY IT ON <x-icon name="arrow-right" /></a></div><div class="catalog-product-grid">@forelse($products as $product)@php($image = $publicMedia->forProduct($product))<article class="catalog-product-card"><a href="{{ route('product',$product) }}"><div class="catalog-image-placeholder" data-public-media-state="{{ $image ? 'approved' : 'awaiting-approved-media' }}">@if($image)<img src="{{ $image['url'] }}" @if($image['srcset']) srcset="{{ $image['srcset'] }}" sizes="{{ $image['sizes'] }}" @endif width="{{ $image['width'] ?: '' }}" height="{{ $image['height'] ?: '' }}" alt="{{ $image['alt'] }}">@else@include('site.partials.public-media-placeholder', ['label' => 'Product image coming soon'])@endif</div><h3>{{ $product->name }}</h3><p>{{ $product->description }}</p><strong>€{{ number_format($product->price,2) }}</strong></a><form method="post" action="{{ route('cart.add',$product) }}">@csrf<button type="submit">ADD TO CART</button></form></article>@empty<div class="empty-note">No products are currently available in this collection.@include('site.partials.product-search-contact')</div>@endforelse</div>{{ $products->links() }}</div></section>
<section class="catalog-benefits"><div><b>FAST DISPATCH</b><span>Worldwide delivery</span></div><div><b>EASY RETURNS</b><span>30-day returns</span></div><div><b>SECURE PAYMENTS</b><span>100% secure checkout</span></div><div><b>MADE IN IRELAND</b><span>Proudly made in Limerick</span></div><div><b>PREMIUM QUALITY</b><span>Finest materials</span></div></section>
@endsection
