@extends('layouts.site')
@section('title',$product->name.' — Emerald Rozalia')
@section('content')
@php
    $imageUrl = $product->image ? (str_starts_with($product->image,'/') || str_starts_with($product->image,'http') ? $product->image : Storage::url($product->image)) : null;
    $activeVariants = $product->variants->where('is_active',true);
@endphp
<div class="product-breadcrumb"><a href="/">Home</a><span>&rsaquo;</span><a href="/shop">Shop</a>@if($product->category)<span>&rsaquo;</span><a href="{{ route('category',$product->category) }}">{{ $product->category->name }}</a>@endif<span>&rsaquo;</span><span>{{ $product->name }}</span></div>
<section class="product-detail">
    <div class="viewer"><div class="viewer-tabs"><button type="button" data-view-mode="360">360&deg; VIEW</button><button type="button" data-view-mode="gallery">PHOTOS</button><a class="btn ghost" href="/virtual-tryon?product={{$product->id}}">VIRTUAL TRY-ON</a></div><div class="spin-viewer" data-spin-viewer data-images='@json($spinFrames)' tabindex="0" aria-label="360 degree product viewer">@if($imageUrl)<img data-spin-image data-initial-src="{{ $imageUrl }}" src="{{ $imageUrl }}" alt="{{ $product->name }}">@elseif($spinFrames)<img data-spin-image data-initial-src="{{ $spinFrames[0] }}" src="{{ $spinFrames[0] }}" alt="{{ $product->name }}">@else<div class="placeholder-hat">IMAGE PENDING</div>@endif<p data-spin-status>{{ $spinFrames ? 'Drag / swipe or use arrow keys to rotate.' : '360° product images will appear when media is configured.' }}</p></div><div class="viewer-features"><span><b>360&deg; VIEW</b>Explore every angle</span><span><b>ZOOM</b>See the details</span><span><b>FULL SCREEN</b>Close-up experience</span></div></div>
    <div class="product-info"><span class="eyebrow">{{ $product->category?->name ?? 'EMERALD ROZALIA' }}</span><h1>{{ $product->name }}</h1><p class="product-sku">SKU: {{ $product->sku }}</p><h2>€{{ number_format($product->price,2) }}</h2><p>{{ $product->description }}</p><div class="product-rule"></div><p><strong>Material:</strong> {{ $product->material ?: 'See product specification' }}</p><p class="stock-status"><strong>Availability:</strong> {{ $product->stock > 0 ? $product->stock.' available' : 'Made to order / check availability' }}</p>
        <form method="post" action="{{ route('cart.add',$product) }}" class="product-purchase">@csrf
            @if($activeVariants->count())<label>VARIANT<select name="variant_id" required>@foreach($activeVariants as $variant)<option value="{{ $variant->id }}">{{ $variant->colour ?: 'Standard' }}{{ $variant->size ? ' · '.$variant->size : '' }} — €{{ number_format($variant->price ?? $product->price,2) }} ({{ $variant->stock }} available)</option>@endforeach</select></label>@else @if($product->colours)<label>COLOUR<select name="colour">@foreach($product->colours as $colour)<option>{{ $colour }}</option>@endforeach</select></label>@endif @if($product->sizes)<label>SIZE<select name="size">@foreach($product->sizes as $size)<option>{{ $size }}</option>@endforeach</select></label>@endif @endif
            <label>QUANTITY<input type="number" name="quantity" value="1" min="1" max="50" required></label><button class="btn" type="submit">ADD TO CART</button>
        </form>
        @auth<form method="post" action="{{ route('wishlist.toggle',$product) }}">@csrf<button class="btn ghost" type="submit">WISHLIST</button></form>@endauth
        <div class="product-meta"><h3>Craftsmanship &amp; Care</h3><p>{{ $product->care ?: 'Store in a dry place and follow the care information supplied with your Emerald Rozalia headwear.' }}</p><p>For corporate customisation or larger quantities, use our Corporate Order or Bulk Order service.</p></div>
    </div>
</section>
<section class="section product-reviews"><h2>Customer Reviews</h2>@forelse($product->reviews as $review)<article class="panel"><strong>{{ str_repeat('★',$review->rating) }}{{ str_repeat('☆',5-$review->rating) }}</strong><h3>{{ $review->title }}</h3><p>{{ $review->body }}</p><small>{{ $review->user->name }}</small></article>@empty<p class="empty-note">Reviews will appear here after verified customer purchases.</p>@endforelse @auth<form class="review-form" method="post" action="{{ route('reviews.store',$product) }}">@csrf<select name="rating"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><input name="title" placeholder="Review title"><textarea name="body" placeholder="Your review"></textarea><button class="btn">SUBMIT REVIEW</button></form>@endauth</section>
<section class="section"><div class="home-section-heading home-section-heading--left"><h2>RELATED PRODUCTS</h2><a href="/shop">VIEW ALL &rarr;</a></div><div class="product-grid">@forelse($related as $relatedProduct)<article class="product-card"><a href="{{ route('product',$relatedProduct) }}"><div class="product-image">@if($relatedProduct->image)<img src="{{ Storage::url($relatedProduct->image) }}" alt="{{ $relatedProduct->name }}">@else<span class="catalog-image-placeholder">IMAGE PENDING</span>@endif</div><h3>{{ $relatedProduct->name }}</h3><strong>€{{ number_format($relatedProduct->price,2) }}</strong></a></article>@empty<p class="empty-note">Related products will appear as the catalogue grows.</p>@endforelse</div></section>
@endsection
