@extends('layouts.site')
@section('title','Virtual Try-On Studio — Emerald Rozalia')
@section('content')
<section class="try-hero"><div><p class="eyebrow">EMERALD ROZALIA LIMITED</p><h1>VIRTUAL <em>TRY-ON</em> STUDIO</h1><p>See how it looks on you. Find your perfect fit.</p></div><div class="try-hero-benefits"><span><b>REALISTIC PREVIEW</b>True-to-life try-on experience</span><span><b>ADJUST &amp; PERFECT</b>Move, rotate &amp; resize</span><span><b>COMPARE STYLES</b>Try multiple looks</span><span><b>100% PRIVATE</b>Your photo stays in your browser</span></div></section>
<section class="try-studio" data-try-studio data-try-assets='@json($assetMap)'>
    <aside class="try-controls"><h2>1. UPLOAD PHOTO</h2><label class="try-upload">Choose a front-facing photo<input type="file" accept="image/jpeg,image/png,image/webp" data-face-upload></label><p class="form-hint">JPG, PNG or WebP. Your photo is previewed locally and is never sent to the server.</p><hr><h2>2. ADJUST FIT</h2><label>SIZE<input type="range" min="30" max="160" value="85" data-hat-size><output data-hat-size-value>85%</output></label><label>POSITION X<input type="range" min="0" max="100" value="50" data-hat-x></label><label>POSITION Y<input type="range" min="0" max="100" value="15" data-hat-y></label><label>ROTATE<input type="range" min="-30" max="30" value="0" data-hat-rotate><output data-hat-rotate-value>0°</output></label><hr><h2>3. VIEW OPTIONS</h2><div class="try-view-options"><button type="button" class="btn" data-try-view="photo">PHOTO</button><button type="button" class="btn ghost" data-try-view="background">BACKGROUND</button></div></aside>
    <div class="try-canvas" data-try-canvas><div class="try-canvas-toolbar"><span>{{ $selected?->name ?: 'Choose a product' }}</span><button type="button" data-try-reset>RESET</button></div><div class="try-empty" data-try-empty>Upload a photo to preview your selected hat.</div><img data-face-preview alt="Your uploaded photo" hidden><img data-hat-overlay alt="Selected product Try-On overlay" hidden><div class="try-asset-missing" data-try-asset-missing>Choose a product with an approved transparent Try-On asset to display the overlay.</div></div>
    <aside class="try-controls try-style-picker"><h2>4. CHOOSE YOUR STYLE</h2><label>PRODUCT<select data-try-product-select><option value="">Select a product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($selected?->id === $product->id)>{{ $product->name }}</option>@endforeach</select></label><div class="try-selected-product" data-try-selected>{{ $selected?->name ?: 'No product selected' }}</div><p class="form-hint">Only approved, product-specific transparent assets are shown. No logo or badge is used as a substitute.</p><a class="btn" href="/shop">BROWSE PRODUCTS</a></aside>
</section>
<section class="try-privacy"><div><b>IRISH MADE QUALITY</b><span>Proudly made in Limerick, Ireland with premium materials.</span></div><div><b>NEED HELP?</b><span>Our team is here to help you find your perfect fit.</span><a href="/contact">CONTACT US</a></div></section>
@endsection
