@extends('layouts.site')
@section('title','Virtual Try-On Studio — Emerald Rozalia')
@push('scripts')<script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.1.0/model-viewer.min.js"></script><script type="module" src="/js/tryon-tracking.js?v=20260928-vision-fallback-v1"></script>@endpush
@push('styles')<link rel="stylesheet" href="/css/virtual-tryon-responsive.css?v=20260928-result-actions-v1">@endpush
@section('content')
<section class="try-hero"><div><p class="eyebrow">EMERALD ROZALIA LIMITED</p><h1>VIRTUAL <em>TRY-ON</em> STUDIO</h1><p>See how it looks on you. Find your perfect fit.</p></div><div class="try-hero-benefits"><span><b>REALISTIC PREVIEW</b>True-to-life try-on experience</span><span><b>ADJUST &amp; PERFECT</b>Move, rotate &amp; resize</span><span><b>COMPARE STYLES</b>Try multiple looks</span><span><b>100% PRIVATE</b>Your photo stays in your browser</span></div></section>
<section class="try-studio" data-try-studio data-try-assets='@json($assetMap)' data-try-meta='@json($assetMetaMap)' data-csrf="{{ csrf_token() }}">
    <aside class="try-controls"><h2>1. CAMERA OR PHOTO</h2><div class="try-camera-actions"><button type="button" class="btn" data-camera-start>START LIVE CAMERA</button><button type="button" class="btn ghost" data-camera-stop hidden>STOP CAMERA</button></div><label class="try-upload">Or choose a front-facing photo<input type="file" accept="image/jpeg,image/png,image/webp" data-face-upload></label><p class="form-hint">Live camera and uploaded photos are processed locally in your browser for face landmarks and are never sent to the server.</p><div class="try-vision-status" data-vision-status aria-live="polite">Vision AI ready to start.</div><hr><h2>2. ADJUST FIT</h2><label>SIZE<input type="range" min="30" max="160" value="85" data-hat-size><output data-hat-size-value>85%</output></label><label>POSITION X<input type="range" min="0" max="100" value="50" data-hat-x></label><label>POSITION Y<input type="range" min="0" max="100" value="15" data-hat-y></label><label>ROTATE<input type="range" min="-30" max="30" value="0" data-hat-rotate><output data-hat-rotate-value>0°</output></label><hr><h2>3. VIEW OPTIONS</h2><div class="try-view-options"><button type="button" class="btn" data-try-view="photo">PHOTO</button><button type="button" class="btn ghost" data-try-view="background">BACKGROUND</button></div></aside>
    <div class="try-canvas" data-try-canvas><div class="try-canvas-toolbar"><span>{{ $selected?->name ?: 'Choose a product' }}</span><button type="button" data-try-reset>RESET</button></div><div class="try-mode-switch" data-try-mode-switch><button type="button" data-try-mode="2d">PHOTO TRY-ON</button><button type="button" data-try-mode="3d">3D MODEL</button></div><div class="try-empty" data-try-empty>Start the camera or upload a photo to preview your selected hat.</div><video data-camera-preview playsinline muted hidden></video><img data-face-preview alt="Your uploaded photo" hidden><img data-hat-overlay alt="Selected product Try-On overlay" hidden><model-viewer data-try-model hidden camera-controls touch-action="pan-y" interaction-prompt="auto" shadow-intensity="1" exposure="1" environment-image="neutral" alt="Interactive 3D product model"></model-viewer><div class="try-model-note" data-try-model-note hidden>Drag to rotate · pinch/scroll to zoom</div><div class="try-asset-missing" data-try-asset-missing>Choose a product with an approved transparent Try-On asset to display the overlay.</div></div><div class="try-result-actions" data-try-result-actions hidden><button type="button" class="btn" data-try-download>DOWNLOAD PREVIEW</button><button type="button" class="btn ghost" data-try-share>SHARE</button><form method="POST" data-try-cart-form action="{{ $selected ? route('cart.add',$selected) : '#' }}">@csrf<input type="hidden" name="quantity" value="1"><button type="submit" class="btn" data-try-cart @disabled(!$selected)>ADD TO CART</button></form><p class="form-hint" data-try-result-status aria-live="polite"></p></div>
    <aside class="try-controls try-style-picker"><h2>4. CHOOSE YOUR STYLE</h2><label>PRODUCT<select data-try-product-select><option value="">Select a product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($selected?->id === $product->id)>{{ $product->name }}</option>@endforeach</select></label><div class="try-selected-product" data-try-selected>{{ $selected?->name ?: 'No product selected' }}</div><p class="form-hint">Only published, product-specific Try-On assets are shown. Camera/photo landmark processing runs in your browser; manual fit controls remain available as a fallback.</p><a class="btn" href="/shop" data-try-browse>BROWSE PRODUCTS</a></aside>
</section>
<section class="try-privacy"><div><b>IRISH MADE QUALITY</b><span>Proudly made in Limerick, Ireland with premium materials.</span></div><div><b>NEED HELP?</b><span>Our team is here to help you find your perfect fit.</span><a href="/contact">CONTACT US</a></div></section>
@endsection
