@extends('layouts.site') @section('title',ucwords(str_replace('-',' ',$section)).' — Emerald Rozalia') @section('content')<section class="page-hero"><span class="eyebrow">CUSTOMER DASHBOARD</span><h1>{{ucwords(str_replace('-',' ',$section))}}</h1></section><section class="account-wrap"><aside class="account-nav"><a href="/account">Dashboard</a>@foreach(['orders'=>'My Orders','wishlist'=>'Wishlist','rewards'=>'Rewards & Points','addresses'=>'Address Book','payments'=>'Payment Methods','profile'=>'Account Details','designs'=>'Custom Designs','bulk-orders'=>'Bulk Orders','returns'=>'Returns / Exchanges'] as $k=>$v)<a href="/account/{{$k}}">{{$v}}</a>@endforeach</aside><div class="account-main">
@if($section==='orders') @forelse($orders as $o)<article class="panel"><h3>{{$o->number}}</h3><p>Status: {{$o->status}} · Payment: {{$o->payment_status}} · Total €{{number_format($o->total,2)}}</p><a class="btn" href="{{route('account.invoice',$o)}}">VIEW / PRINT INVOICE</a><form method="post" action="{{route('account.return.store',$o)}}">@csrf<select name="type"><option value="return">Return</option><option value="exchange">Exchange</option></select><input name="reason" placeholder="Reason" required><textarea name="details" placeholder="Details"></textarea><button>Submit request</button></form></article>@empty<p>No orders yet.</p>@endforelse
@elseif($section==='wishlist') @forelse($wishlist as $w)<article class="panel"><a href="/product/{{$w->product->slug}}"><h3>{{$w->product->name}}</h3></a><p>€{{number_format($w->product->price,2)}}</p><form method="post" action="{{route('wishlist.toggle',$w->product)}}">@csrf<button>Remove</button></form></article>@empty<p>Your wishlist is empty.</p>@endforelse
@elseif($section==='rewards') <h2>Balance: {{$rewards->sum('points')}} points</h2>@foreach($rewards as $r)<div class="order-row"><span>{{$r->created_at->format('d M Y')}}</span><span>{{$r->description}}</span><strong>{{$r->points}}</strong></div>@endforeach
@elseif($section==='addresses') <div class="cards">@foreach($addresses as $a)<article class="panel"><h3>{{$a->label}} {{$a->is_default?'· Default':''}}</h3><p>{{$a->name}}<br>{{$a->line1}}<br>{{$a->city}} {{$a->postcode}}</p><form method="post" action="{{route('account.address.delete',$a)}}">@csrf @method('DELETE')<button>Remove</button></form></article>@endforeach</div><h2>Add Address</h2><form class="profile-form" method="post" action="{{route('account.address.store')}}">@csrf<input name="label" value="Home" required><input name="name" placeholder="Name" required><input name="phone" placeholder="Phone"><input name="line1" placeholder="Address line 1" required><input name="line2" placeholder="Address line 2"><input name="city" placeholder="City" required><input name="county" placeholder="County"><input name="postcode" placeholder="Postcode"><input name="country" value="IE" maxlength="2"><label><input type="checkbox" name="is_default" value="1"> Default</label><button class="btn">SAVE ADDRESS</button></form>
@elseif($section==='profile') <form class="profile-form" method="post" action="{{route('account.profile')}}">@csrf @method('PATCH')<label>Name<input name="name" value="{{auth()->user()->name}}" required></label><label>Email<input value="{{auth()->user()->email}}" disabled></label><label>Phone<input name="phone" value="{{auth()->user()->phone}}"></label><button class="btn">UPDATE PROFILE</button></form>
@elseif($section==='payments') <h2>Payment Methods</h2><p>For security, card details are not stored directly by Emerald Rozalia. Connect a PCI-compliant payment provider in production. Pay-on-delivery, bank transfer and manual gateway hooks are available in the included checkout.</p>
@elseif($section==='designs') <h2>Custom Designs</h2><p>Your saved cap/hat customisation projects will appear here when a design configurator is connected.</p><a class="btn" href="/corporate-orders">START A CUSTOM ORDER</a>
@elseif($section==='bulk-orders') <h2>Bulk Orders</h2><p>Use your account to request and track corporate and bulk enquiries.</p><a class="btn" href="/bulk-orders">REQUEST BULK QUOTE</a>
@elseif($section==='returns') @forelse($returns as $ret)<div class="order-row"><span>{{$ret->number}}</span><span>{{$ret->order->number}}</span><span>{{$ret->type}}</span><strong>{{$ret->status}}</strong></div>@empty<p>No return or exchange requests.</p>@endforelse @endif
</div></section>@endsection
