<?php

namespace App\Support;

final class CatalogBrazil
{
    public const STATES = [
        ['code' => 'BR-AC', 'name' => 'Acre', 'type' => 'state'],
        ['code' => 'BR-AL', 'name' => 'Alagoas', 'type' => 'state'],
        ['code' => 'BR-AP', 'name' => 'Amapá', 'type' => 'state'],
        ['code' => 'BR-AM', 'name' => 'Amazonas', 'type' => 'state'],
        ['code' => 'BR-BA', 'name' => 'Bahia', 'type' => 'state'],
        ['code' => 'BR-CE', 'name' => 'Ceará', 'type' => 'state'],
        ['code' => 'BR-DF', 'name' => 'Distrito Federal', 'type' => 'federal district'],
        ['code' => 'BR-ES', 'name' => 'Espírito Santo', 'type' => 'state'],
        ['code' => 'BR-GO', 'name' => 'Goiás', 'type' => 'state'],
        ['code' => 'BR-MA', 'name' => 'Maranhão', 'type' => 'state'],
        ['code' => 'BR-MT', 'name' => 'Mato Grosso', 'type' => 'state'],
        ['code' => 'BR-MS', 'name' => 'Mato Grosso do Sul', 'type' => 'state'],
        ['code' => 'BR-MG', 'name' => 'Minas Gerais', 'type' => 'state'],
        ['code' => 'BR-PA', 'name' => 'Pará', 'type' => 'state'],
        ['code' => 'BR-PB', 'name' => 'Paraíba', 'type' => 'state'],
        ['code' => 'BR-PR', 'name' => 'Paraná', 'type' => 'state'],
        ['code' => 'BR-PE', 'name' => 'Pernambuco', 'type' => 'state'],
        ['code' => 'BR-PI', 'name' => 'Piauí', 'type' => 'state'],
        ['code' => 'BR-RJ', 'name' => 'Rio de Janeiro', 'type' => 'state'],
        ['code' => 'BR-RN', 'name' => 'Rio Grande do Norte', 'type' => 'state'],
        ['code' => 'BR-RS', 'name' => 'Rio Grande do Sul', 'type' => 'state'],
        ['code' => 'BR-RO', 'name' => 'Rondônia', 'type' => 'state'],
        ['code' => 'BR-RR', 'name' => 'Roraima', 'type' => 'state'],
        ['code' => 'BR-SC', 'name' => 'Santa Catarina', 'type' => 'state'],
        ['code' => 'BR-SP', 'name' => 'São Paulo', 'type' => 'state'],
        ['code' => 'BR-SE', 'name' => 'Sergipe', 'type' => 'state'],
        ['code' => 'BR-TO', 'name' => 'Tocantins', 'type' => 'state'],
    ];

    public const CLUBS = [
        ['county_code' => 'BR-AC', 'name' => 'Rio Branco-AC'],
        ['county_code' => 'BR-AL', 'name' => 'CRB'],
        ['county_code' => 'BR-AL', 'name' => 'CSA'],
        ['county_code' => 'BR-AP', 'name' => 'Trem'],
        ['county_code' => 'BR-AM', 'name' => 'Amazonas FC'],
        ['county_code' => 'BR-AM', 'name' => 'Nacional-AM'],
        ['county_code' => 'BR-BA', 'name' => 'Bahia'],
        ['county_code' => 'BR-BA', 'name' => 'Vitória'],
        ['county_code' => 'BR-CE', 'name' => 'Ceará'],
        ['county_code' => 'BR-CE', 'name' => 'Fortaleza'],
        ['county_code' => 'BR-DF', 'name' => 'Brasiliense'],
        ['county_code' => 'BR-DF', 'name' => 'Gama'],
        ['county_code' => 'BR-ES', 'name' => 'Rio Branco-ES'],
        ['county_code' => 'BR-ES', 'name' => 'Desportiva Ferroviária'],
        ['county_code' => 'BR-GO', 'name' => 'Goiás'],
        ['county_code' => 'BR-GO', 'name' => 'Atlético Goianiense'],
        ['county_code' => 'BR-GO', 'name' => 'Vila Nova'],
        ['county_code' => 'BR-MA', 'name' => 'Sampaio Corrêa'],
        ['county_code' => 'BR-MT', 'name' => 'Cuiabá'],
        ['county_code' => 'BR-MS', 'name' => 'Operário-MS'],
        ['county_code' => 'BR-MG', 'name' => 'Atlético Mineiro'],
        ['county_code' => 'BR-MG', 'name' => 'Cruzeiro'],
        ['county_code' => 'BR-MG', 'name' => 'América Mineiro'],
        ['county_code' => 'BR-PA', 'name' => 'Remo'],
        ['county_code' => 'BR-PA', 'name' => 'Paysandu'],
        ['county_code' => 'BR-PB', 'name' => 'Botafogo-PB'],
        ['county_code' => 'BR-PR', 'name' => 'Athletico Paranaense'],
        ['county_code' => 'BR-PR', 'name' => 'Coritiba'],
        ['county_code' => 'BR-PR', 'name' => 'Paraná Clube'],
        ['county_code' => 'BR-PE', 'name' => 'Sport Recife'],
        ['county_code' => 'BR-PE', 'name' => 'Náutico'],
        ['county_code' => 'BR-PE', 'name' => 'Santa Cruz'],
        ['county_code' => 'BR-PI', 'name' => 'Altos'],
        ['county_code' => 'BR-RJ', 'name' => 'Flamengo'],
        ['county_code' => 'BR-RJ', 'name' => 'Fluminense'],
        ['county_code' => 'BR-RJ', 'name' => 'Vasco da Gama'],
        ['county_code' => 'BR-RJ', 'name' => 'Botafogo'],
        ['county_code' => 'BR-RN', 'name' => 'ABC'],
        ['county_code' => 'BR-RN', 'name' => 'América de Natal'],
        ['county_code' => 'BR-RS', 'name' => 'Grêmio'],
        ['county_code' => 'BR-RS', 'name' => 'Internacional'],
        ['county_code' => 'BR-RS', 'name' => 'Juventude'],
        ['county_code' => 'BR-RO', 'name' => 'Porto Velho'],
        ['county_code' => 'BR-RR', 'name' => 'São Raimundo-RR'],
        ['county_code' => 'BR-SC', 'name' => 'Avaí'],
        ['county_code' => 'BR-SC', 'name' => 'Figueirense'],
        ['county_code' => 'BR-SC', 'name' => 'Chapecoense'],
        ['county_code' => 'BR-SC', 'name' => 'Criciúma'],
        ['county_code' => 'BR-SP', 'name' => 'Corinthians'],
        ['county_code' => 'BR-SP', 'name' => 'Palmeiras'],
        ['county_code' => 'BR-SP', 'name' => 'São Paulo'],
        ['county_code' => 'BR-SP', 'name' => 'Santos'],
        ['county_code' => 'BR-SP', 'name' => 'Red Bull Bragantino'],
        ['county_code' => 'BR-SP', 'name' => 'Ponte Preta'],
        ['county_code' => 'BR-SP', 'name' => 'Guarani'],
        ['county_code' => 'BR-SE', 'name' => 'Confiança'],
        ['county_code' => 'BR-SE', 'name' => 'Sergipe'],
        ['county_code' => 'BR-TO', 'name' => 'Tocantinópolis'],
    ];
}
