<?php

namespace App\Support;

final class CatalogEngland
{
    public const COUNTIES = [
        ['code' => 'ENG-BDF', 'name' => 'Bedfordshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-BRK', 'name' => 'Berkshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-BST', 'name' => 'Bristol', 'type' => 'ceremonial county'],
        ['code' => 'ENG-BKM', 'name' => 'Buckinghamshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-CAM', 'name' => 'Cambridgeshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-CHS', 'name' => 'Cheshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-LND', 'name' => 'City of London', 'type' => 'ceremonial county'],
        ['code' => 'ENG-CON', 'name' => 'Cornwall', 'type' => 'ceremonial county'],
        ['code' => 'ENG-CMA', 'name' => 'Cumbria', 'type' => 'ceremonial county'],
        ['code' => 'ENG-DBY', 'name' => 'Derbyshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-DEV', 'name' => 'Devon', 'type' => 'ceremonial county'],
        ['code' => 'ENG-DOR', 'name' => 'Dorset', 'type' => 'ceremonial county'],
        ['code' => 'ENG-DUR', 'name' => 'County Durham', 'type' => 'ceremonial county'],
        ['code' => 'ENG-ERY', 'name' => 'East Riding of Yorkshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-ESX', 'name' => 'East Sussex', 'type' => 'ceremonial county'],
        ['code' => 'ENG-ESS', 'name' => 'Essex', 'type' => 'ceremonial county'],
        ['code' => 'ENG-GLS', 'name' => 'Gloucestershire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-GLN', 'name' => 'Greater London', 'type' => 'ceremonial county'],
        ['code' => 'ENG-GTM', 'name' => 'Greater Manchester', 'type' => 'ceremonial county'],
        ['code' => 'ENG-HAM', 'name' => 'Hampshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-HEF', 'name' => 'Herefordshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-HRT', 'name' => 'Hertfordshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-IOW', 'name' => 'Isle of Wight', 'type' => 'ceremonial county'],
        ['code' => 'ENG-KEN', 'name' => 'Kent', 'type' => 'ceremonial county'],
        ['code' => 'ENG-LAN', 'name' => 'Lancashire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-LEI', 'name' => 'Leicestershire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-LIN', 'name' => 'Lincolnshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-MSY', 'name' => 'Merseyside', 'type' => 'ceremonial county'],
        ['code' => 'ENG-NFK', 'name' => 'Norfolk', 'type' => 'ceremonial county'],
        ['code' => 'ENG-NYK', 'name' => 'North Yorkshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-NTH', 'name' => 'Northamptonshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-NBL', 'name' => 'Northumberland', 'type' => 'ceremonial county'],
        ['code' => 'ENG-NTT', 'name' => 'Nottinghamshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-OXF', 'name' => 'Oxfordshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-RUT', 'name' => 'Rutland', 'type' => 'ceremonial county'],
        ['code' => 'ENG-SHR', 'name' => 'Shropshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-SOM', 'name' => 'Somerset', 'type' => 'ceremonial county'],
        ['code' => 'ENG-SYK', 'name' => 'South Yorkshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-STS', 'name' => 'Staffordshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-SFK', 'name' => 'Suffolk', 'type' => 'ceremonial county'],
        ['code' => 'ENG-SRY', 'name' => 'Surrey', 'type' => 'ceremonial county'],
        ['code' => 'ENG-TWR', 'name' => 'Tyne and Wear', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WAR', 'name' => 'Warwickshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WMD', 'name' => 'West Midlands', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WSX', 'name' => 'West Sussex', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WYK', 'name' => 'West Yorkshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WIL', 'name' => 'Wiltshire', 'type' => 'ceremonial county'],
        ['code' => 'ENG-WOR', 'name' => 'Worcestershire', 'type' => 'ceremonial county'],
    ];

    public const CLUBS = [
        ['county_code' => 'ENG-BDF', 'name' => 'Luton Town'],
        ['county_code' => 'ENG-BRK', 'name' => 'Reading'],
        ['county_code' => 'ENG-BST', 'name' => 'Bristol City'],
        ['county_code' => 'ENG-BST', 'name' => 'Bristol Rovers'],
        ['county_code' => 'ENG-BKM', 'name' => 'Milton Keynes Dons'],
        ['county_code' => 'ENG-BKM', 'name' => 'Wycombe Wanderers'],
        ['county_code' => 'ENG-CAM', 'name' => 'Cambridge United'],
        ['county_code' => 'ENG-CAM', 'name' => 'Peterborough United'],
        ['county_code' => 'ENG-CON', 'name' => 'Truro City'],
        ['county_code' => 'ENG-CMA', 'name' => 'Carlisle United'],
        ['county_code' => 'ENG-CMA', 'name' => 'Barrow'],
        ['county_code' => 'ENG-DBY', 'name' => 'Derby County'],
        ['county_code' => 'ENG-DBY', 'name' => 'Chesterfield'],
        ['county_code' => 'ENG-DEV', 'name' => 'Plymouth Argyle'],
        ['county_code' => 'ENG-DEV', 'name' => 'Exeter City'],
        ['county_code' => 'ENG-DEV', 'name' => 'Torquay United'],
        ['county_code' => 'ENG-DOR', 'name' => 'AFC Bournemouth'],
        ['county_code' => 'ENG-DUR', 'name' => 'Hartlepool United'],
        ['county_code' => 'ENG-DUR', 'name' => 'Darlington'],
        ['county_code' => 'ENG-ERY', 'name' => 'Hull City'],
        ['county_code' => 'ENG-ESX', 'name' => 'Brighton & Hove Albion'],
        ['county_code' => 'ENG-ESS', 'name' => 'Colchester United'],
        ['county_code' => 'ENG-ESS', 'name' => 'Southend United'],
        ['county_code' => 'ENG-GLS', 'name' => 'Cheltenham Town'],
        ['county_code' => 'ENG-GLS', 'name' => 'Forest Green Rovers'],
        ['county_code' => 'ENG-GLN', 'name' => 'Arsenal'],
        ['county_code' => 'ENG-GLN', 'name' => 'Chelsea'],
        ['county_code' => 'ENG-GLN', 'name' => 'Tottenham Hotspur'],
        ['county_code' => 'ENG-GLN', 'name' => 'West Ham United'],
        ['county_code' => 'ENG-GLN', 'name' => 'Crystal Palace'],
        ['county_code' => 'ENG-GLN', 'name' => 'Fulham'],
        ['county_code' => 'ENG-GLN', 'name' => 'Brentford'],
        ['county_code' => 'ENG-GLN', 'name' => 'Queens Park Rangers'],
        ['county_code' => 'ENG-GLN', 'name' => 'Millwall'],
        ['county_code' => 'ENG-GLN', 'name' => 'Charlton Athletic'],
        ['county_code' => 'ENG-GLN', 'name' => 'Leyton Orient'],
        ['county_code' => 'ENG-GLN', 'name' => 'AFC Wimbledon'],
        ['county_code' => 'ENG-GTM', 'name' => 'Manchester United'],
        ['county_code' => 'ENG-GTM', 'name' => 'Manchester City'],
        ['county_code' => 'ENG-GTM', 'name' => 'Bolton Wanderers'],
        ['county_code' => 'ENG-GTM', 'name' => 'Wigan Athletic'],
        ['county_code' => 'ENG-GTM', 'name' => 'Stockport County'],
        ['county_code' => 'ENG-GTM', 'name' => 'Rochdale'],
        ['county_code' => 'ENG-GTM', 'name' => 'Oldham Athletic'],
        ['county_code' => 'ENG-HAM', 'name' => 'Southampton'],
        ['county_code' => 'ENG-HAM', 'name' => 'Portsmouth'],
        ['county_code' => 'ENG-HRT', 'name' => 'Watford'],
        ['county_code' => 'ENG-HRT', 'name' => 'Stevenage'],
        ['county_code' => 'ENG-KEN', 'name' => 'Gillingham'],
        ['county_code' => 'ENG-LAN', 'name' => 'Blackburn Rovers'],
        ['county_code' => 'ENG-LAN', 'name' => 'Burnley'],
        ['county_code' => 'ENG-LAN', 'name' => 'Blackpool'],
        ['county_code' => 'ENG-LAN', 'name' => 'Preston North End'],
        ['county_code' => 'ENG-LAN', 'name' => 'Accrington Stanley'],
        ['county_code' => 'ENG-LAN', 'name' => 'Morecambe'],
        ['county_code' => 'ENG-LEI', 'name' => 'Leicester City'],
        ['county_code' => 'ENG-LIN', 'name' => 'Lincoln City'],
        ['county_code' => 'ENG-LIN', 'name' => 'Grimsby Town'],
        ['county_code' => 'ENG-LIN', 'name' => 'Scunthorpe United'],
        ['county_code' => 'ENG-MSY', 'name' => 'Liverpool'],
        ['county_code' => 'ENG-MSY', 'name' => 'Everton'],
        ['county_code' => 'ENG-MSY', 'name' => 'Tranmere Rovers'],
        ['county_code' => 'ENG-NFK', 'name' => 'Norwich City'],
        ['county_code' => 'ENG-NYK', 'name' => 'Middlesbrough'],
        ['county_code' => 'ENG-NYK', 'name' => 'Harrogate Town'],
        ['county_code' => 'ENG-NTH', 'name' => 'Northampton Town'],
        ['county_code' => 'ENG-NBL', 'name' => 'Blyth Spartans'],
        ['county_code' => 'ENG-NTT', 'name' => 'Nottingham Forest'],
        ['county_code' => 'ENG-NTT', 'name' => 'Notts County'],
        ['county_code' => 'ENG-NTT', 'name' => 'Mansfield Town'],
        ['county_code' => 'ENG-OXF', 'name' => 'Oxford United'],
        ['county_code' => 'ENG-SHR', 'name' => 'Shrewsbury Town'],
        ['county_code' => 'ENG-SOM', 'name' => 'Yeovil Town'],
        ['county_code' => 'ENG-SYK', 'name' => 'Sheffield United'],
        ['county_code' => 'ENG-SYK', 'name' => 'Sheffield Wednesday'],
        ['county_code' => 'ENG-SYK', 'name' => 'Barnsley'],
        ['county_code' => 'ENG-SYK', 'name' => 'Rotherham United'],
        ['county_code' => 'ENG-SYK', 'name' => 'Doncaster Rovers'],
        ['county_code' => 'ENG-STS', 'name' => 'Stoke City'],
        ['county_code' => 'ENG-STS', 'name' => 'Port Vale'],
        ['county_code' => 'ENG-STS', 'name' => 'Burton Albion'],
        ['county_code' => 'ENG-SFK', 'name' => 'Ipswich Town'],
        ['county_code' => 'ENG-TWR', 'name' => 'Newcastle United'],
        ['county_code' => 'ENG-TWR', 'name' => 'Sunderland'],
        ['county_code' => 'ENG-WMD', 'name' => 'Aston Villa'],
        ['county_code' => 'ENG-WMD', 'name' => 'Birmingham City'],
        ['county_code' => 'ENG-WMD', 'name' => 'Wolverhampton Wanderers'],
        ['county_code' => 'ENG-WMD', 'name' => 'West Bromwich Albion'],
        ['county_code' => 'ENG-WMD', 'name' => 'Walsall'],
        ['county_code' => 'ENG-WSX', 'name' => 'Crawley Town'],
        ['county_code' => 'ENG-WYK', 'name' => 'Leeds United'],
        ['county_code' => 'ENG-WYK', 'name' => 'Huddersfield Town'],
        ['county_code' => 'ENG-WYK', 'name' => 'Bradford City'],
        ['county_code' => 'ENG-WIL', 'name' => 'Swindon Town'],
        ['county_code' => 'ENG-WOR', 'name' => 'Kidderminster Harriers'],
    ];
}
