<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Project 1 cPanel') - Emerald Rozalia</title><link rel="stylesheet" href="/css/app.css"></head><body class="admin-body">
@php
$orderTypes=['order-online'=>'online','order-corporate'=>'corporate','order-bulk'=>'bulk','order-franchise'=>'franchise','order-franchise-retail'=>'franchise_retail','order-buyer'=>'buyer'];
$modules=['website-products'=>'Website & Products','media-manager'=>'Product Media Manager','page-manager'=>'Page Manager','online-sales'=>'Online Sales','order-online'=>'Online Order Master','order-corporate'=>'Corporate Order Master','order-bulk'=>'Bulk Order Master','order-franchise'=>'Franchise Order Master','order-franchise-retail'=>'Franchise Retail Orders','order-buyer'=>'Buyer Order Master','customers'=>'Customers','franchise-management'=>'Franchise Management','communication-center'=>'Communication Centre','returns-refunds'=>'Returns & Refunds','reports'=>'Reports','users-roles'=>'Users & Roles','integrations'=>'Integrations','settings'=>'Settings','audit-logs'=>'Audit & Logs','automation'=>'Automation','backup-recovery'=>'Backup & Recovery','system-maintenance'=>'System Maintenance'];
@endphp
<aside class="admin-sidebar"><a href="{{route('admin.dashboard')}}" class="admin-logo"><img src="/assets/brand/emerald-rozalia-wordmark.png" alt="Emerald Rozalia Limited"></a><small>PROJECT 1 - SINGLE CPANEL</small><a href="{{route('admin.dashboard')}}">⌂ Dashboard</a>
@foreach($modules as $slug=>$label) @php($href=isset($orderTypes[$slug])?route('admin.order-master',$orderTypes[$slug]):($slug==='page-manager'?route('admin.pages'):($slug==='integrations'?route('admin.integration-status'):route('admin.resource',$slug)))) <a href="{{$href}}">{{$label}}</a> @endforeach
<a href="{{route('admin.bulk-upload')}}">Bulk Product Upload</a></aside>
<div class="admin-shell"><header class="admin-top"><span>☘ Irish Made. Limerick Born. Worn Everywhere.</span><div class="context-switchers"><form method="post" action="/context/language">@csrf<select name="locale" onchange="this.form.submit()">@foreach(\App\Models\Language::where('active',true)->get() as $l)<option value="{{$l->locale}}" @selected(($activeLocale??'en')===$l->locale)>{{$l->native_name}}</option>@endforeach</select></form><form method="post" action="/context/currency">@csrf<select name="currency" onchange="this.form.submit()">@foreach(\App\Models\Currency::where('active',true)->get() as $c)<option value="{{$c->code}}" @selected(($activeCurrency??'EUR')===$c->code)>{{$c->code}} {{$c->symbol}}</option>@endforeach</select></form>@auth @if(auth()->user()->is_admin)<form method="post" action="/context/company">@csrf<select name="company_id" onchange="this.form.submit()">@foreach(\App\Models\Company::where('active',true)->get() as $co)<option value="{{$co->id}}" @selected(($tenantCompany?->id)===$co->id)>{{$co->name}}</option>@endforeach</select></form>@endif @endauth</div><span>HQ: Limerick, Ireland</span><form method="post" action="/logout">@csrf<button>Logout</button></form></header><main class="admin-main">@if(session('success'))<div class="flash success">{{session('success')}}</div>@endif @if($errors->any())<div class="flash error">{{implode(' ', $errors->all())}}</div>@endif @yield('content')</main></div><script src="/js/app.js"></script></body></html>
