@extends('layouts.admin')

@section('title', 'Country Master')

@push('styles')
<style>
.master-page{padding:22px;display:grid;gap:18px;color:#17231b}.master-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.master-head h1{margin:4px 0;font-size:26px}.master-head p{margin:0;color:#66756c}.master-kicker{font-size:12px;font-weight:800;color:#087c3f;text-transform:uppercase}.master-nav,.master-filter{display:flex;gap:8px;flex-wrap:wrap}.master-btn{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:8px 13px;border:1px solid #d4ded7;border-radius:8px;background:#fff;color:#122219;font-weight:700;text-decoration:none;cursor:pointer}.master-btn.primary{background:#087c3f;border-color:#087c3f;color:#fff}.master-card{background:#fff;border:1px solid #dce5df;border-radius:12px;padding:16px}.master-filter input,.master-filter select,.master-add input,.master-add select,.master-table input,.master-table select{height:38px;border:1px solid #ccd8d0;border-radius:7px;padding:0 9px;background:#fff}.master-filter input{min-width:220px}.master-add{display:grid;grid-template-columns:90px minmax(180px,1fr) 120px 120px 120px 110px auto;gap:8px;align-items:end}.master-add label{display:grid;gap:5px;font-size:11px;font-weight:700}.master-table-wrap{overflow:auto}.master-table{width:100%;border-collapse:collapse;font-size:13px;min-width:930px}.master-table th,.master-table td{padding:9px 8px;border-bottom:1px solid #edf1ee;text-align:left}.master-table th{background:#f8faf8;font-size:11px;text-transform:uppercase;color:#67756c}.master-badge{display:inline-flex;padding:3px 7px;border-radius:999px;background:#edf7f0;color:#087c3f;font-size:11px;font-weight:800}.master-alert{padding:11px 13px;border-radius:8px;background:#eaf7ef;color:#056c35;font-weight:700}.master-alert.error{background:#fff0ef;color:#a12620}.master-pagination{padding-top:12px}@media(max-width:950px){.master-add{grid-template-columns:repeat(2,minmax(0,1fr))}.master-head{display:grid}}@media(max-width:560px){.master-page{padding:12px}.master-add{grid-template-columns:1fr}.master-filter>*{width:100%;min-width:0!important}}
</style>
@endpush

@section('content')
<div class="master-page">
    <header class="master-head"><div><span class="master-kicker">Website &amp; Products · Categories</span><h1>Country Master</h1><p>All countries/territories are available here. EU and UEFA flags control the country dropdowns used by the category taxonomy builder.</p></div><nav class="master-nav"><a class="master-btn" href="{{ route('admin.categories.index') }}">Categories</a><a class="master-btn" href="{{ route('admin.categories.taxonomy') }}">Taxonomy Builder</a><a class="master-btn" href="{{ route('admin.categories.clubs') }}">Club Master</a></nav></header>
    @if(session('success'))<div class="master-alert">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="master-alert error">{{ $errors->first() }}</div>@endif

    <section class="master-card"><form class="master-filter" method="get" action="{{ route('admin.categories.countries') }}"><input type="search" name="q" value="{{ $search }}" placeholder="Search country or code..."><select name="scope"><option value="all" @selected($scope==='all')>All Countries</option><option value="eu" @selected($scope==='eu')>EU Countries</option><option value="uefa" @selected($scope==='uefa')>UEFA Countries / Associations</option></select><select name="status"><option value="active" @selected($status==='active')>Active</option><option value="inactive" @selected($status==='inactive')>Inactive</option><option value="all" @selected($status==='all')>All Statuses</option></select><button class="master-btn" type="submit">Filter</button><a class="master-btn" href="{{ route('admin.categories.countries') }}">Reset</a></form></section>

    <section class="master-card"><h2 style="margin-top:0">Add custom country / football association</h2><form class="master-add" method="post" action="{{ route('admin.categories.countries.store') }}">@csrf<label>Code<input name="code" required maxlength="3" placeholder="XK"></label><label>Name<input name="name" required maxlength="160"></label><label>EU<select name="is_eu"><option value="0">No</option><option value="1">Yes</option></select></label><label>UEFA<select name="is_uefa"><option value="0">No</option><option value="1">Yes</option></select></label><label>Status<select name="is_active"><option value="1">Active</option><option value="0">Inactive</option></select></label><label>Sort<input type="number" name="sort_order" min="0" max="100000" value="0"></label><button class="master-btn primary" type="submit">Add Country</button></form></section>

    <section class="master-card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h2 style="margin:0">Countries</h2><span class="master-badge">{{ number_format($countries->total()) }} shown</span></div><div class="master-table-wrap" style="margin-top:12px"><table class="master-table"><thead><tr><th>Code</th><th>Name</th><th>EU</th><th>UEFA</th><th>Active</th><th>Clubs</th><th>Sort</th><th>Action</th></tr></thead><tbody>
        @foreach($countries as $country)
            @php($countryFormId='country-master-'.$country->id)
            <tr><td><form id="{{ $countryFormId }}" method="post" action="{{ route('admin.categories.countries.update',$country) }}">@csrf @method('PATCH')</form><input form="{{ $countryFormId }}" name="code" value="{{ $country->code }}" maxlength="3" required style="width:70px"></td><td><input form="{{ $countryFormId }}" name="name" value="{{ $country->name }}" maxlength="160" required style="min-width:190px;width:100%"></td><td><select form="{{ $countryFormId }}" name="is_eu"><option value="1" @selected($country->is_eu)>Yes</option><option value="0" @selected(!$country->is_eu)>No</option></select></td><td><select form="{{ $countryFormId }}" name="is_uefa"><option value="1" @selected($country->is_uefa)>Yes</option><option value="0" @selected(!$country->is_uefa)>No</option></select></td><td><select form="{{ $countryFormId }}" name="is_active"><option value="1" @selected($country->is_active)>Active</option><option value="0" @selected(!$country->is_active)>Inactive</option></select></td><td>{{ number_format($country->clubs_count) }}</td><td><input form="{{ $countryFormId }}" type="number" name="sort_order" value="{{ $country->sort_order }}" min="0" max="100000" style="width:80px"></td><td><button form="{{ $countryFormId }}" class="master-btn" type="submit">Save</button></td></tr>
        @endforeach
    </tbody></table></div><div class="master-pagination">{{ $countries->links() }}</div></section>
</div>
@endsection
