@extends('layouts.admin')
@section('title','Product Media Manager')
@section('content')
<div class="admin-title"><div><small>WEBSITE &amp; PRODUCTS</small><h1>Product Media Manager</h1><p>Upload and manage product images, video, 360° media and Virtual Try-On assets.</p></div></div>
<section class="panel media-product-picker"><form method="get"><label>PRODUCT<select name="product_id" onchange="this.form.submit()"><option value="">Select a product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($selected?->id === $product->id)>{{ $product->name }} ({{ $product->media_count }} active media)</option>@endforeach</select></label></form>@if($selected)<div><strong>{{ $selected->name }}</strong><small>SKU: {{ $selected->sku }} · Stock: {{ $selected->stock }} · Price: €{{ number_format($selected->price,2) }}</small></div>@endif</section>
@if($selected)
<section class="media-manager-grid"><div class="panel"><div class="panel-heading"><h2>Add Media</h2><span class="panel-caption">Images → Video → 360° → Try-On</span></div><form class="media-form" method="post" action="{{ route('admin.media.store') }}" enctype="multipart/form-data">@csrf<input type="hidden" name="product_id" value="{{ $selected->id }}"><label>Media type<select name="type" required><option value="image">Product image</option><option value="video">Product video</option><option value="spin_360">360° product view</option><option value="try_on">Virtual Try-On</option></select></label><label>Storage disk<select name="disk"><option value="public">Public</option><option value="local">Local/private</option></select></label><label>Upload file<input type="file" name="file" accept="image/*,video/mp4,video/webm"></label><p class="form-hint">Or provide a path that already exists on the selected disk.</p><label>Existing path<input name="path" placeholder="product-media/example.webp"></label><label>Alt text<input name="alt_text" maxlength="255" placeholder="Describe this media for accessibility"></label><label>Gallery order<input type="number" name="sort_order" min="0" value="0"></label><label class="checkbox-label"><input type="checkbox" name="active" value="1" checked> Active and visible</label><button class="btn" type="submit">ADD MEDIA</button></form></div><div class="panel"><div class="panel-heading"><h2>Media status</h2><span class="panel-caption">{{ $media->count() }} active/recorded</span></div><div class="media-summary"><div><b>{{ $media->where('type','image')->count() }}</b><span>Images</span></div><div><b>{{ $media->where('type','video')->count() }}</b><span>Videos</span></div><div><b>{{ $media->where('type','spin_360')->count() }}</b><span>360° media</span></div><div><b>{{ $media->where('type','try_on')->count() }}</b><span>Try-On assets</span></div></div><p class="form-hint">Only active media is exposed through the product media relation. Original source photography should be uploaded through this workflow when approved.</p></div></section>
<section class="panel"><div class="panel-heading"><h2>Media summary &amp; gallery order</h2><span class="panel-caption">Drag/reorder can be added after the approved media archive is available.</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Type</th><th>Path</th><th>Alt text</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($media as $item)<tr><td>{{ $item->sort_order }}</td><td>{{ str($item->type)->replace('_',' ')->headline() }}</td><td><code>{{ $item->path }}</code></td><td>{{ $item->alt_text ?: '—' }}</td><td>{{ $item->active ? 'Active' : 'Inactive' }}</td><td class="table-actions"><form method="post" action="{{ route('admin.media.update',$item) }}">@csrf @method('PATCH')<input type="hidden" name="type" value="{{ $item->type }}"><input type="hidden" name="sort_order" value="{{ $item->sort_order }}"><input type="hidden" name="active" value="{{ $item->active ? 1 : 0 }}"><input name="alt_text" value="{{ $item->alt_text }}" aria-label="Alt text for {{ $item->path }}"><button>Save alt text</button></form><form method="post" action="{{ route('admin.media.destroy',$item) }}">@csrf @method('DELETE')<button>Remove</button></form></td></tr>@empty<tr><td colspan="6">No media has been recorded for this product.</td></tr>@endforelse</tbody></table></div></section>
@else
<section class="panel"><p>Select a product to manage its media. Products are loaded from the active catalogue.</p></section>
@endif
@endsection
