<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AdminRecord;
use App\Models\FranchiseApplication;
use App\Models\FranchiseStore;
use App\Models\User;
use App\Services\AuditTrail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class FranchiseManagementController extends Controller
{
    public const SECTIONS = ['franchise-dashboard','franchise-applications','franchise-territories','franchise-agreements','franchisees','franchise-retail-stores','training-documents','marketing-assets','performance-targets','renewals','franchise-reports','data-management'];

    public function show(Request $request, string $section): View
    {
        $config = $this->blueprint($section); abort_unless($config, 404);
        $query = $this->query($section, $config['source']);
        $this->filters($query, $request, $config);
        $records = $query->paginate(10)->withQueryString();
        $records->setCollection($records->getCollection()->map(fn($row) => $this->row($row, $config)));
        $metrics = $this->metrics($section);
        $admins = User::query()->where('is_admin', true)->orderBy('name')->get(['id','name']);
        $search = trim((string)$request->query('q','')); $status=(string)$request->query('status',''); $tab=(string)$request->query('tab','all');
        return view('admin.franchise.index', compact('section','config','records','metrics','admins','search','status','tab'));
    }

    public function store(Request $request, string $section)
    {
        $config=$this->blueprint($section); abort_unless($config,404);
        if($config['source']==='application') return $this->storeApplication($request,$config);
        if($config['source']==='store') return $this->storeStore($request,$config);
        $data=$this->genericData($request,$config);
        $record=AdminRecord::create(['module'=>$section,'title'=>$data['title'],'reference'=>$data['reference']??null,'status'=>$data['status'],'amount'=>$data['amount']??null,'record_date'=>$data['record_date']??null,'user_id'=>auth()->id(),'data'=>$this->meta($data)]);
        AuditTrail::record($section.'.created',$record,null,$record->toArray());
        return back()->with('success',$config['singular'].' created.');
    }

    public function update(Request $request,string $section,int $id)
    {
        $config=$this->blueprint($section); abort_unless($config,404);
        if($config['source']==='application') return $this->updateApplication($request,$config,$id);
        if($config['source']==='store') return $this->updateStore($request,$config,$id);
        $record=AdminRecord::query()->where('module',$section)->findOrFail($id); $before=$record->toArray(); $data=$this->genericData($request,$config);
        $record->update(['title'=>$data['title'],'reference'=>$data['reference']??null,'status'=>$data['status'],'amount'=>$data['amount']??null,'record_date'=>$data['record_date']??null,'data'=>$this->meta($data,$record->data??[])]);
        AuditTrail::record($section.'.updated',$record,$before,$record->fresh()->toArray());
        return back()->with('success',$config['singular'].' updated.');
    }

    public function destroy(string $section,int $id)
    {
        $config=$this->blueprint($section); abort_unless($config,404);
        $record=$config['source']==='application'?FranchiseApplication::findOrFail($id):($config['source']==='store'?FranchiseStore::findOrFail($id):AdminRecord::query()->where('module',$section)->findOrFail($id));
        $before=$record->toArray(); AuditTrail::record($section.'.deleted',$record,$before,null); $record->delete();
        return back()->with('success',$config['singular'].' deleted.');
    }

    public function export(Request $request,string $section): StreamedResponse
    {
        $config=$this->blueprint($section); abort_unless($config,404); $query=$this->query($section,$config['source']); $this->filters($query,$request,$config);
        $rows=$query->limit(5000)->get()->map(fn($row)=>$this->row($row,$config)); $columns=$config['columns'];
        return response()->streamDownload(function()use($rows,$columns){$h=fopen('php://output','w');fputcsv($h,array_column($columns,'label'));foreach($rows as $row)fputcsv($h,array_map(fn($c)=>strip_tags((string)($row[$c['key']]??'')),$columns));fclose($h);},$section.'-'.now()->format('Ymd-His').'.csv',['Content-Type'=>'text/csv']);
    }

    private function query(string $section,string $source): Builder
    {
        return match($source){'application'=>FranchiseApplication::query()->latest('id'),'store'=>FranchiseStore::query()->latest('id'),default=>AdminRecord::query()->where('module',$section)->latest('id')};
    }

    private function filters(Builder $query,Request $request,array $config): void
    {
        $q=trim((string)$request->query('q','')); $status=(string)$request->query('status',''); $tab=(string)$request->query('tab','all'); if($status===''&&isset($config['statuses'][$tab]))$status=$tab;
        if($q!==''){
            if($config['source']==='application')$query->where(fn(Builder $b)=>$b->where('applicant_name','like','%'.$q.'%')->orWhere('email','like','%'.$q.'%')->orWhere('territory','like','%'.$q.'%'));
            elseif($config['source']==='store')$query->where(fn(Builder $b)=>$b->where('name','like','%'.$q.'%')->orWhere('code','like','%'.$q.'%')->orWhere('territory','like','%'.$q.'%'));
            else $query->where(fn(Builder $b)=>$b->where('title','like','%'.$q.'%')->orWhere('reference','like','%'.$q.'%'));
        }
        if($status!==''&&isset($config['statuses'][$status])){
            if($config['source']==='application')$query->whereIn('status',$status==='under-review'?['under-review','under_review','pending','review']:[$status]);
            elseif($config['source']==='store')$query->whereIn('status',match($status){'active'=>['active','open'],'pending'=>['pending','onboarding'],'inactive'=>['inactive','suspended'],default=>[$status]});
            else $query->where('status',$status);
        }
    }

    private function row(mixed $record,array $config): array
    {
        if($config['source']==='application'){
            $status=match((string)$record->status){'pending','under_review','review'=>'under-review','on_boarding'=>'onboarding',default=>(string)$record->status}; if(!isset($config['statuses'][$status]))$status='new';
            $edit=['applicant_name'=>$record->applicant_name,'email'=>$record->email,'phone'=>$record->phone,'territory'=>$record->territory,'preferred_location'=>$record->preferred_location,'investment_range'=>$record->investment_range,'status'=>$status,'assigned_to'=>$record->assigned_to,'source'=>data_get($record->data,'source','Website')];
            return ['id'=>$record->id,'reference'=>'LEAD-'.str_pad((string)$record->id,8,'0',STR_PAD_LEFT),'primary'=>$record->applicant_name,'secondary'=>$record->email,'territory'=>$record->territory,'record_type'=>$record->investment_range?:'Franchise Lead','status'=>$status,'status_label'=>$config['statuses'][$status],'source'=>data_get($record->data,'source','Website'),'date'=>optional($record->created_at)->format('d M Y h:i A')?:'—','end_date'=>'—','assigned'=>$record->assigned_to?(User::query()->find($record->assigned_to)?->name?:'Unassigned'):'Unassigned','value'=>$record->investment_range?:'—','amount'=>'—','growth'=>'—','notes'=>$record->preferred_location?:'','edit'=>$edit];
        }
        if($config['source']==='store'){
            $meta=$record->address??[]; $status=match((string)$record->status){'open'=>'active','onboarding'=>'pending','suspended'=>'inactive',default=>(string)$record->status}; if(!isset($config['statuses'][$status]))$status='pending'; $sales=data_get($meta,'monthly_sales');
            $edit=['code'=>$record->code,'name'=>$record->name,'franchisee_name'=>data_get($meta,'franchisee_name'),'territory'=>$record->territory,'status'=>$status,'manager_name'=>data_get($meta,'manager_name'),'manager_email'=>data_get($meta,'manager_email'),'opened_at'=>optional($record->opened_at)->format('Y-m-d'),'monthly_sales'=>$sales];
            return ['id'=>$record->id,'reference'=>$record->code,'primary'=>$record->name,'secondary'=>data_get($meta,'franchisee_name','—')?:'—','territory'=>$record->territory,'record_type'=>'Retail Store','status'=>$status,'status_label'=>$config['statuses'][$status],'source'=>'Franchise Network','date'=>optional($record->opened_at)->format('d M Y')?:'—','end_date'=>'—','assigned'=>data_get($meta,'manager_name','Unassigned')?:'Unassigned','value'=>is_numeric($sales)?'€'.number_format((float)$sales,2):'€0.00','amount'=>is_numeric($sales)?'€'.number_format((float)$sales,2):'€0.00','growth'=>'—','notes'=>data_get($meta,'manager_email',''),'edit'=>$edit];
        }
        $m=$record->data??[]; $status=(string)$record->status; $edit=['title'=>$record->title,'reference'=>$record->reference,'status'=>$status,'amount'=>$record->amount,'record_date'=>optional($record->record_date)->format('Y-m-d'),'secondary'=>data_get($m,'secondary'),'territory'=>data_get($m,'territory'),'record_type'=>data_get($m,'record_type'),'source'=>data_get($m,'source'),'assigned_to_name'=>data_get($m,'assigned_to_name'),'end_date'=>data_get($m,'end_date'),'value'=>data_get($m,'value'),'growth'=>data_get($m,'growth'),'notes'=>data_get($m,'notes')];
        return ['id'=>$record->id,'reference'=>$record->reference?:'REC-'.str_pad((string)$record->id,6,'0',STR_PAD_LEFT),'primary'=>$record->title,'secondary'=>data_get($m,'secondary','—')?:'—','territory'=>data_get($m,'territory','—')?:'—','record_type'=>data_get($m,'record_type','—')?:'—','status'=>$status,'status_label'=>$config['statuses'][$status]??Str::headline($status),'source'=>data_get($m,'source','—')?:'—','date'=>optional($record->record_date)->format('d M Y')?:optional($record->updated_at)->format('d M Y h:i A')?:'—','end_date'=>filled(data_get($m,'end_date'))?Carbon::parse(data_get($m,'end_date'))->format('d M Y'):'—','assigned'=>data_get($m,'assigned_to_name','—')?:'—','value'=>data_get($m,'value','—')?:'—','amount'=>$record->amount!==null?'€'.number_format((float)$record->amount,2):'—','growth'=>data_get($m,'growth','—')?:'—','notes'=>data_get($m,'notes',''),'edit'=>$edit];
    }

    private function storeApplication(Request $r,array $config){$d=$this->applicationData($r,$config);$record=FranchiseApplication::create(['applicant_name'=>$d['applicant_name'],'email'=>$d['email'],'phone'=>$d['phone']??null,'territory'=>$d['territory'],'preferred_location'=>$d['preferred_location']??null,'investment_range'=>$d['investment_range']??null,'status'=>$d['status'],'assigned_to'=>$d['assigned_to']??null,'data'=>['source'=>$d['source']??'Website']]);AuditTrail::record('franchise.application.created',$record,null,$record->toArray());return back()->with('success','Franchise application created.');}
    private function updateApplication(Request $r,array $config,int $id){$record=FranchiseApplication::findOrFail($id);$before=$record->toArray();$d=$this->applicationData($r,$config);$record->update(['applicant_name'=>$d['applicant_name'],'email'=>$d['email'],'phone'=>$d['phone']??null,'territory'=>$d['territory'],'preferred_location'=>$d['preferred_location']??null,'investment_range'=>$d['investment_range']??null,'status'=>$d['status'],'assigned_to'=>$d['assigned_to']??null,'data'=>array_merge($record->data??[],['source'=>$d['source']??'Website'])]);AuditTrail::record('franchise.application.updated',$record,$before,$record->fresh()->toArray());return back()->with('success','Franchise application updated.');}
    private function applicationData(Request $r,array $c):array{return $r->validate(['applicant_name'=>['required','string','max:180'],'email'=>['required','email','max:180'],'phone'=>['nullable','string','max:60'],'territory'=>['required','string','max:180'],'preferred_location'=>['nullable','string','max:180'],'investment_range'=>['nullable','string','max:180'],'status'=>['required',Rule::in(array_keys($c['statuses']))],'assigned_to'=>['nullable','integer',Rule::exists('users','id')->where('is_admin',true)],'source'=>['nullable','string','max:100']]);}
    private function storeStore(Request $r,array $config){$d=$this->storeData($r,$config);$record=FranchiseStore::create(['code'=>$d['code'],'name'=>$d['name'],'territory'=>$d['territory'],'status'=>$d['status'],'opened_at'=>$d['opened_at']??null,'address'=>$this->storeMeta($d)]);AuditTrail::record('franchise.store.created',$record,null,$record->toArray());return back()->with('success','Franchise retail store created.');}
    private function updateStore(Request $r,array $config,int $id){$record=FranchiseStore::findOrFail($id);$before=$record->toArray();$d=$this->storeData($r,$config,$id);$record->update(['code'=>$d['code'],'name'=>$d['name'],'territory'=>$d['territory'],'status'=>$d['status'],'opened_at'=>$d['opened_at']??null,'address'=>array_merge($record->address??[],$this->storeMeta($d))]);AuditTrail::record('franchise.store.updated',$record,$before,$record->fresh()->toArray());return back()->with('success','Franchise retail store updated.');}
    private function storeData(Request $r,array $c,?int $id=null):array{$unique=Rule::unique('franchise_stores','code');if($id)$unique->ignore($id);return $r->validate(['code'=>['required','string','max:100',$unique],'name'=>['required','string','max:180'],'franchisee_name'=>['nullable','string','max:180'],'territory'=>['required','string','max:180'],'status'=>['required',Rule::in(array_keys($c['statuses']))],'manager_name'=>['nullable','string','max:180'],'manager_email'=>['nullable','email','max:180'],'opened_at'=>['nullable','date'],'monthly_sales'=>['nullable','numeric','min:0','max:999999999.99']]);}
    private function storeMeta(array $d):array{return ['franchisee_name'=>$d['franchisee_name']??null,'manager_name'=>$d['manager_name']??null,'manager_email'=>$d['manager_email']??null,'monthly_sales'=>isset($d['monthly_sales'])?(float)$d['monthly_sales']:null];}
    private function genericData(Request $r,array $c):array{return $r->validate(['title'=>['required','string','max:180'],'reference'=>['nullable','string','max:100'],'status'=>['required',Rule::in(array_keys($c['statuses']))],'amount'=>['nullable','numeric','min:0','max:999999999.99'],'record_date'=>['nullable','date'],'secondary'=>['nullable','string','max:180'],'territory'=>['nullable','string','max:180'],'record_type'=>['nullable','string','max:120'],'source'=>['nullable','string','max:120'],'assigned_to_name'=>['nullable','string','max:180'],'end_date'=>['nullable','date'],'value'=>['nullable','string','max:120'],'growth'=>['nullable','string','max:120'],'notes'=>['nullable','string','max:3000']]);}
    private function meta(array $d,array $old=[]):array{return array_merge($old,array_intersect_key($d,array_flip(['secondary','territory','record_type','source','assigned_to_name','end_date','value','growth','notes'])));}

    private function metrics(string $section): array
    {
        $apps=FranchiseApplication::query();$stores=FranchiseStore::query();$m=AdminRecord::query()->where('module',$section);$metric=fn($label,$value,$icon,$tone,$sub)=>compact('label','value','icon','tone','sub');
        return match($section){
            'franchise-dashboard'=>[$metric('Total Applications',$apps->count(),'users','green','All franchise leads'),$metric('Active Franchisees',$this->statusCount('franchisees',['active']),'check','green','Operating partners'),$metric('Retail Stores',$stores->count(),'shopping-bag','blue','Network stores'),$metric('Agreements',$this->moduleCount('franchise-agreements'),'file-text','orange','Tracked agreements'),$metric('Renewals Due',$this->statusCount('renewals',['due-soon','overdue']),'refresh','purple','Needs attention')],
            'franchise-applications'=>[$metric('Total Leads',$apps->count(),'users','green','All applications'),$metric('New This Week',(clone $apps)->where('created_at','>=',now()->subDays(7))->count(),'file-text','green','Last 7 days'),$metric('Under Review',(clone $apps)->whereIn('status',['pending','under-review','under_review','review'])->count(),'clock','orange','In evaluation'),$metric('Approved',(clone $apps)->where('status','approved')->count(),'check','green','Approved leads'),$metric('Conversion Rate',$this->conversion().'%', 'star','purple','Converted / total')],
            'franchise-retail-stores'=>[$metric('Total Stores',$stores->count(),'shopping-bag','green','All stores'),$metric('Active Stores',(clone $stores)->whereIn('status',['active','open'])->count(),'check','green','Open and operating'),$metric('Pending Approval',(clone $stores)->whereIn('status',['pending','onboarding'])->count(),'clock','orange','Awaiting approval'),$metric('Inactive Stores',(clone $stores)->whereIn('status',['inactive','suspended','terminated'])->count(),'alert','red','Needs action'),$metric('This Month Sales','€'.number_format($this->storeSales(),2),'chart','purple','Recorded store sales')],
            'franchise-reports'=>[$metric('Total Applications',$apps->count(),'users','green','Pipeline'),$metric('Active Franchisees',$this->statusCount('franchisees',['active']),'shopping-bag','purple','Partners'),$metric('Retail Stores',$stores->count(),'shopping-bag','blue','Stores'),$metric('Agreements Signed',$this->statusCount('franchise-agreements',['active','completed']),'file-text','orange','Agreements'),$metric('Target Achievement',$this->avgPercent('performance-targets','value').'%','star','orange','Average target')],
            default=>[$metric('Total '.$this->blueprint($section)['singular'].'s',$m->count(),'users','green','All tracked records'),$metric('Active',(clone $m)->whereIn('status',['active','published','top-performer','renewed'])->count(),'check','green','Active records'),$metric('Pending',(clone $m)->whereIn('status',['pending','under-review','due-soon','needs-attention'])->count(),'clock','orange','Needs review'),$metric('At Risk',(clone $m)->whereIn('status',['at-risk','overdue','expired','suspended'])->count(),'alert','red','Needs action'),$metric('Tracked Value','€'.number_format((float)$m->sum('amount'),2),'chart','purple','Total recorded value')]
        };
    }
    private function moduleCount(string $m):int{return AdminRecord::query()->where('module',$m)->count();}
    private function statusCount(string $m,array $s):int{return AdminRecord::query()->where('module',$m)->whereIn('status',$s)->count();}
    private function conversion():string{$t=FranchiseApplication::query()->count();return $t?number_format(FranchiseApplication::query()->whereIn('status',['converted','onboarding','approved'])->count()/$t*100,1):'0.0';}
    private function storeSales():float{return (float)FranchiseStore::query()->get()->sum(fn($s)=>(float)data_get($s->address,'monthly_sales',0));}
    private function avgPercent(string $m,string $key):string{$v=AdminRecord::query()->where('module',$m)->get()->map(function($r)use($key){preg_match('/-?\d+(?:\.\d+)?/',(string)data_get($r->data,$key,''),$x);return isset($x[0])?(float)$x[0]:null;})->filter(fn($v)=>$v!==null);return $v->isEmpty()?'0.0':number_format((float)$v->average(),1);}

    private function blueprint(string $section): ?array
    {
        $appCols=[['key'=>'reference','label'=>'Lead ID'],['key'=>'primary','label'=>'Applicant / Company'],['key'=>'territory','label'=>'Territory'],['key'=>'status','label'=>'Status'],['key'=>'source','label'=>'Source'],['key'=>'date','label'=>'Date'],['key'=>'assigned','label'=>'Assigned To']];
        $common=['integrations'=>['Communication Center','Reports & Analytics','Users & Roles','Unified Stock Master','Unified Finance'],'benefits'=>[['Unified UUID / Traceability','Every record is fully traceable.'],['Unified Stock Master','Operational stock stays connected.'],['Unified Finance','Financial activity remains linked.'],['One Project 1 cPanel','One system. One source of truth.']]];
        $pages=[
            'franchise-dashboard'=>['title'=>'Franchise Dashboard','subtitle'=>'Central overview of franchise pipeline, stores, agreements and performance.','singular'=>'Franchise record','source'=>'application','editable'=>false,'purpose'=>'See the complete franchise network from first lead through onboarding, retail operations and renewal.','features'=>['Live application pipeline','Territory and agreement visibility','Retail store status','Performance and target monitoring','Renewal and follow-up visibility'],'statuses'=>['new'=>'New','under-review'=>'Under Review','approved'=>'Approved','rejected'=>'Rejected','onboarding'=>'Onboarding','converted'=>'Converted'],'tabs'=>['all'=>'Overview','new'=>'New Leads','under-review'=>'Under Review','approved'=>'Approved','onboarding'=>'Onboarding'],'columns'=>$appCols],
            'franchise-applications'=>['title'=>'Applications & Leads','subtitle'=>'Manage all franchise applications from initial inquiry to onboarding.','singular'=>'Application','source'=>'application','editable'=>true,'purpose'=>'Central hub to capture, track and manage franchise leads and applications from inquiry to onboarding and conversion.','features'=>['Real-time lead and application metrics','Status pipeline with visual indicators','Advanced search and filtering','Assign applications to team members','Quick view and edit actions','Create new application','Source tracking'],'statuses'=>['new'=>'New','under-review'=>'Under Review','approved'=>'Approved','rejected'=>'Rejected','onboarding'=>'Onboarding','converted'=>'Converted'],'tabs'=>['all'=>'All Applications','new'=>'New','under-review'=>'Under Review','approved'=>'Approved','rejected'=>'Rejected','onboarding'=>'Onboarding','converted'=>'Converted'],'columns'=>$appCols],
            'franchise-territories'=>['title'=>'Territories','subtitle'=>'Manage franchise territories, availability, ownership and network coverage.','singular'=>'Territory','source'=>'record','editable'=>true,'purpose'=>'Control territory availability, ownership, coverage and performance across the franchise network.','features'=>['Territory availability tracking','Franchisee assignment','Store and coverage visibility','Territory performance status','Search and filters','Full audit trail'],'statuses'=>['active'=>'Active','available'=>'Available','reserved'=>'Reserved','at-risk'=>'At Risk','inactive'=>'Inactive'],'tabs'=>['all'=>'All Territories','active'=>'Active','available'=>'Available','reserved'=>'Reserved','at-risk'=>'At Risk'],'columns'=>[['key'=>'reference','label'=>'Territory ID'],['key'=>'primary','label'=>'Territory'],['key'=>'secondary','label'=>'Franchisee'],['key'=>'status','label'=>'Status'],['key'=>'value','label'=>'Stores'],['key'=>'amount','label'=>'Revenue'],['key'=>'date','label'=>'Last Updated']]],
            'franchise-agreements'=>['title'=>'Agreements','subtitle'=>'Create, manage and track all franchise agreements.','singular'=>'Agreement','source'=>'record','editable'=>true,'purpose'=>'Create, manage and monitor all franchise agreements, terms and obligations.','features'=>['Create and customize agreements','Digital signature & version control','Track validity and renewals','Link agreements to territories and stores','Set terms, fees and obligations','Automated renewal reminders','Export agreements and reports'],'statuses'=>['active'=>'Active','under-review'=>'Under Review','expiring-soon'=>'Expiring Soon','expired'=>'Expired','draft'=>'Draft','terminated'=>'Terminated','archived'=>'Archived','completed'=>'Fully Executed'],'tabs'=>['all'=>'All Agreements','active'=>'Active','expiring-soon'=>'Expiring Soon','expired'=>'Expired','draft'=>'Draft','under-review'=>'Under Review','terminated'=>'Terminated','archived'=>'Archived'],'columns'=>[['key'=>'reference','label'=>'Agreement ID'],['key'=>'primary','label'=>'Franchisee'],['key'=>'territory','label'=>'Territory'],['key'=>'record_type','label'=>'Agreement Type'],['key'=>'status','label'=>'Status'],['key'=>'date','label'=>'Start Date'],['key'=>'end_date','label'=>'End Date'],['key'=>'assigned','label'=>'Signed By']]],
            'franchisees'=>['title'=>'Franchisees','subtitle'=>'Manage all franchisees and their business relationship.','singular'=>'Franchisee','source'=>'record','editable'=>true,'purpose'=>'Manage franchisee profiles, status, agreements, territories and overall business relationship.','features'=>['Centralized franchisee management','Status and lifecycle tracking','Territory and agreement visibility','Store count and performance link','Quick view and edit actions','Access to documents & history','Integrated communication'],'statuses'=>['active'=>'Active','pending'=>'Pending','suspended'=>'Suspended','terminated'=>'Terminated'],'tabs'=>['all'=>'All Franchisees','active'=>'Active','pending'=>'Pending Approval','suspended'=>'Suspended','terminated'=>'Terminated','by-territory'=>'By Territory','by-agreement'=>'By Agreement'],'columns'=>[['key'=>'reference','label'=>'Franchisee ID'],['key'=>'primary','label'=>'Franchisee Name'],['key'=>'secondary','label'=>'Primary Contact'],['key'=>'territory','label'=>'Territory'],['key'=>'record_type','label'=>'Agreement'],['key'=>'status','label'=>'Status'],['key'=>'date','label'=>'Joined Date'],['key'=>'value','label'=>'Stores']]],
            'franchise-retail-stores'=>['title'=>'Franchise Retail Stores','subtitle'=>'Manage all franchise retail stores and their performance.','singular'=>'Store','source'=>'store','editable'=>true,'purpose'=>'Oversee all franchise retail stores, track performance, status and key operational details.','features'=>['Centralized store management','Real-time performance tracking','Store status & lifecycle management','Territory and franchisee visibility','Manager & contact information','Sales overview and analytics','Export store data and reports'],'statuses'=>['active'=>'Active','pending'=>'Pending','inactive'=>'Inactive','terminated'=>'Terminated'],'tabs'=>['all'=>'All Stores','active'=>'Active','pending'=>'Pending Approval','inactive'=>'Inactive','by-territory'=>'By Territory','by-franchisee'=>'By Franchisee','top-performers'=>'Top Performers'],'columns'=>[['key'=>'reference','label'=>'Store ID'],['key'=>'primary','label'=>'Store Name'],['key'=>'secondary','label'=>'Franchisee'],['key'=>'territory','label'=>'Territory'],['key'=>'status','label'=>'Status'],['key'=>'assigned','label'=>'Store Manager'],['key'=>'date','label'=>'Opened Date'],['key'=>'value','label'=>'Monthly Sales']]],
            'training-documents'=>['title'=>'Training & Documents','subtitle'=>'Manage training programs, learning progress and important documents.','singular'=>'Training item','source'=>'record','editable'=>true,'purpose'=>'Manage training programs, learning progress and important documents across the franchise network.','features'=>['Create and manage training modules','Upload and organize documents','Assign content by role and territory','Mandatory training enforcement','Track progress and completion','Issue and manage certificates','Version control and history'],'statuses'=>['published'=>'Published','active'=>'Active','draft'=>'Draft','completed'=>'Completed','archived'=>'Archived'],'tabs'=>['all'=>'All Content','modules'=>'Training Modules','documents'=>'Documents','mandatory'=>'Mandatory','by-role'=>'By Role','by-territory'=>'By Territory'],'columns'=>[['key'=>'record_type','label'=>'Type'],['key'=>'primary','label'=>'Title'],['key'=>'secondary','label'=>'Category / Topic'],['key'=>'territory','label'=>'Audience'],['key'=>'source','label'=>'Mandatory'],['key'=>'status','label'=>'Status'],['key'=>'growth','label'=>'Completion Rate'],['key'=>'date','label'=>'Last Updated']]],
            'marketing-assets'=>['title'=>'Marketing Assets','subtitle'=>'Manage brand assets, marketing materials and campaign resources.','singular'=>'Marketing asset','source'=>'record','editable'=>true,'purpose'=>'Organize and distribute brand assets and marketing materials across the franchise network.','features'=>['Centralized marketing asset library','Asset version control & approvals','Campaign and purpose tagging','Territory and franchisee targeting','Asset usage tracking & downloads','Expiration alerts & renewals','Quick search, filters & categories'],'statuses'=>['active'=>'Active','scheduled'=>'Scheduled','expiring-soon'=>'Expiring Soon','expired'=>'Expired','draft'=>'Draft','archived'=>'Archived'],'tabs'=>['all'=>'All Assets','images'=>'Images','videos'=>'Videos','documents'=>'Documents','templates'=>'Templates','campaigns'=>'Campaigns','guidelines'=>'Brand Guidelines'],'columns'=>[['key'=>'primary','label'=>'Asset Name'],['key'=>'record_type','label'=>'Type'],['key'=>'secondary','label'=>'Category'],['key'=>'source','label'=>'Campaign / Purpose'],['key'=>'territory','label'=>'Territories'],['key'=>'status','label'=>'Status'],['key'=>'date','label'=>'Last Updated'],['key'=>'amount','label'=>'Downloads']]],
            'performance-targets'=>['title'=>'Performance & Targets','subtitle'=>'Track performance, measure results and manage targets across the franchise network.','singular'=>'Performance record','source'=>'record','editable'=>true,'purpose'=>'Monitor performance, track target achievement and identify top performers and areas that need improvement.','features'=>['Real-time performance tracking','Target setting & management','KPI scorecards & leaderboards','Territory & franchisee comparisons','Store level performance visibility','At risk identification & alerts','Growth trends & analytics'],'statuses'=>['top-performer'=>'Top Performer','above-target'=>'Above Target','on-target'=>'On Target','needs-attention'=>'Needs Attention','at-risk'=>'At Risk'],'tabs'=>['all'=>'Overview','targets'=>'Targets','kpis'=>'KPIs','scorecard'=>'Scorecard','leaderboards'=>'Leaderboards','by-territory'=>'By Territory','by-franchisee'=>'By Franchisee','by-store'=>'By Store'],'columns'=>[['key'=>'reference','label'=>'Rank'],['key'=>'primary','label'=>'Franchisee / Store'],['key'=>'territory','label'=>'Territory'],['key'=>'amount','label'=>'Revenue'],['key'=>'secondary','label'=>'Orders'],['key'=>'value','label'=>'Target Achievement'],['key'=>'growth','label'=>'YTD Growth'],['key'=>'status','label'=>'Status']]],
            'renewals'=>['title'=>'Renewals','subtitle'=>'Manage upcoming renewals, expirations and lifecycle of franchise agreements and related assets.','singular'=>'Renewal','source'=>'record','editable'=>true,'purpose'=>'Oversee and manage upcoming renewals for agreements, franchises and stores to ensure business continuity.','features'=>['Upcoming and overdue renewals','Automated reminders & alerts','Renewal value tracking','Agreement & store renewals','Renewal history & audit trail','Approve, renew or extend','Calendar & timeline view'],'statuses'=>['upcoming'=>'Upcoming','due-soon'=>'Due Soon','overdue'=>'Overdue','renewed'=>'Renewed','cancelled'=>'Cancelled'],'tabs'=>['all'=>'All Renewals','upcoming'=>'Upcoming','overdue'=>'Overdue','renewed'=>'Renewed','by-agreement'=>'By Agreement','by-franchisee'=>'By Franchisee','by-territory'=>'By Territory','by-store'=>'By Store'],'columns'=>[['key'=>'reference','label'=>'Item ID'],['key'=>'primary','label'=>'Franchisee / Store'],['key'=>'secondary','label'=>'Agreement'],['key'=>'record_type','label'=>'Type'],['key'=>'end_date','label'=>'Expiry Date'],['key'=>'value','label'=>'Due In'],['key'=>'status','label'=>'Status'],['key'=>'amount','label'=>'Renewal Value'],['key'=>'date','label'=>'Last Action']]],
            'franchise-reports'=>['title'=>'Franchise Reports','subtitle'=>'Comprehensive performance, pipeline and operational overview of all franchise activities.','singular'=>'Report','source'=>'record','editable'=>true,'purpose'=>'Bring application, franchisee, store, agreement, sales and performance reporting into one operational view.','features'=>['Pipeline reporting','Store and territory performance','Agreement and renewal reporting','Orders & sales analysis','Comparative analysis','Exportable reports'],'statuses'=>['active'=>'Active','draft'=>'Draft','completed'=>'Completed','archived'=>'Archived'],'tabs'=>['all'=>'Overview','applications'=>'Applications','franchisees'=>'Franchisees','stores'=>'Franchise Retail Stores','agreements'=>'Agreements','sales'=>'Orders & Sales','performance'=>'Performance & Targets','renewals'=>'Renewals'],'columns'=>[['key'=>'reference','label'=>'Report ID'],['key'=>'primary','label'=>'Report'],['key'=>'record_type','label'=>'Type'],['key'=>'status','label'=>'Status'],['key'=>'date','label'=>'Generated'],['key'=>'assigned','label'=>'Owner']]],
            'data-management'=>['title'=>'Data Management','subtitle'=>'Manage data quality, backups, imports, exports and retention across the franchise network.','singular'=>'Data activity','source'=>'record','editable'=>true,'purpose'=>'Maintain data accuracy, security and availability through proper lifecycle management.','features'=>['Data quality monitoring','Automated & manual backups','Import & export management','Data retention & archival','Cleanup & storage optimization','UUID based data traceability'],'statuses'=>['active'=>'Healthy','import'=>'Import','export'=>'Export','backup'=>'Backup','cleanup'=>'Cleanup','archived'=>'Archived'],'tabs'=>['all'=>'Overview','quality'=>'Data Quality','backups'=>'Backups','imports'=>'Imports','exports'=>'Exports','retention'=>'Data Retention','cleanup'=>'Cleanup & Archive','uuid'=>'UUID Traceability'],'columns'=>[['key'=>'record_type','label'=>'Type'],['key'=>'primary','label'=>'Description'],['key'=>'assigned','label'=>'Performed By'],['key'=>'date','label'=>'Date & Time'],['key'=>'status','label'=>'Status']]],
        ];
        return isset($pages[$section])?array_merge($common,$pages[$section]):null;
    }
}
